### ISSUE TITLE
[Question] Classnames properties on non-series elements

### ISSUE THREAD

**Issue by sharynneazhar** [uber/react-vis#1002]
I see in the documentation the line below:

> Non-series elements (i.e. gridlines or hints) do not take a className property.

I would like to pass styles to the `Hint` components using a classname to keep our codebase consistent and more maintainable. Any reason why these components don't have classnames available?

**Comment by mcnuttandrew** [comment]
I don't think there is a real reason. Hint appears to take a className while gridlines does not. I would gladly accept a PR adding that functionality

**Comment by sharynneazhar** [comment]
Sounds good. I will take you up on that and submit a PR 🙂
