### ISSUE TITLE
Stacked bar series with negative values are not drawn below 0 on the YAxis

### ISSUE THREAD

**Issue by ABBVelocityDev** [uber/react-vis#1007]
Stacked bar series with all positive values render as expected:
```
function Chart({data}) {
  return <XYPlot width={300} height={300} stackBy="y">
          <VerticalGridLines />
          <HorizontalGridLines />
          <XAxis />
          <YAxis />
          <VerticalBarSeries data={[{x: 1, y: 10}, {x: 2, y: 5}, {x: 3, y: 15}]} />
          <VerticalBarSeries data={[{x: 1, y: 12}, {x: 2, y: 2}, {x: 3, y: 11}]} />
          <VerticalBarSeries data={[{x: 1, y: 5}, {x: 2, y: 7}, {x: 3, y: 4}]} />
        </XYPlot>
}
```
![image](https://user-images.githubusercontent.com/32575266/46881244-f2a16300-ce18-11e8-88c0-31d24d14d239.png)

However, if y-axis values are less than zero my expectation is that the bars with negative values will stack below 0 on the Y axis.  However, they appear to draw downward from the top of the previous bar.
```
function Chart({data}) {
  return <XYPlot width={300} height={300} stackBy="y">
          <VerticalGridLines />
          <HorizontalGridLines />
          <XAxis />
          <YAxis />
          <VerticalBarSeries data={[{x: 1, y: 10}, {x: 2, y: 5}, {x: 3, y: 15}]} />
          <VerticalBarSeries data={[{x: 1, y: 12}, {x: 2, y: 2}, {x: 3, y: -5}]} />
          <VerticalBarSeries data={[{x: 1, y: 5}, {x: 2, y: 7}, {x: 3, y: -5}]} />
        </XYPlot>
}
```
![image](https://user-images.githubusercontent.com/32575266/46881389-54fa6380-ce19-11e8-8e69-92d100be127a.png)

Is there a way to configure the chart to stack all bars with negative values below 0 on the Y axis?

**Comment by mcnuttandrew** [comment]
There is not currently a way to do stacked bars with a negative start position. The stacking strategy tries to cover a wide variety of use cases and so makes so sacrifices of generality. This is not to say you can't achieve your goal with react-vis, you totally can you need to effectively roll your own stacking.

The bottom of rectangular cells are defined by y0 and their tops by y, you can use this in conjunction with some manipulation to put things into place in the way that you desire. Something like
```js
const cells = [{x: 1, y: 10}, {x: 2, y: 5}, {x: 3, y: 15}];
let base = -10;
cells.map((row, idx) => {
  const newRow = {
    ...row,
    y: row.y + base,
    y0: base
  };
  base = newRow.y;
  return newRow;
})
```
Here constructed with side effects, but could also be done through purely function reduce

**Comment by ABBVelocityDev** [comment]
Thanks for the idea.  This gets me closer, but doesn't appear to completely meet my needs.  This approach appears to require the series to be ordered with all negative values first, followed by positive values.  However, I can't guarantee that ordering in my chart data.

So, if I have my negative value(s) first in series order, all is well.
```
function Chart({data}) {
  return <XYPlot width={300} height={300} stackBy="y">
          <VerticalGridLines />
          <HorizontalGridLines />
          <XAxis />
          <YAxis />
          <VerticalBarSeries data={[{x: 1, y0: 0, y: 10}, {x: 2, y0: 0, y: 5}, {x: 3, y0: -5, y: 0}]} />
          <VerticalBarSeries data={[{x: 1, y0: 10, y: 22}, {x: 2, y0: 5, y: 7}, {x: 3, y0: 0, y: 4}]} />
          <VerticalBarSeries data={[{x: 1, y0: 22, y: 33}, {x: 2, y0: 7, y: 11}, {x: 3, y0: 4, y: 8}]} />
        </XYPlot>;
}
```
![image](https://user-images.githubusercontent.com/32575266/46908860-189d3500-cef7-11e8-99d2-cce39617de8c.png)

But if my negative values(s) appear in a series listed after a positive value, the position of the bars is not as desired.  Unfortunately my data can have negative values in 0, 1, or 2 of the 3 series, and there is no guarantee as to which one(s) may be negative for a given X-axis value/category.
```
function Chart({data}) {
  return <XYPlot width={300} height={300} stackBy="y">
          <VerticalGridLines />
          <HorizontalGridLines />
          <XAxis />
          <YAxis />
          <VerticalBarSeries data={[{x: 1, y0: 0, y: 10}, {x: 2, y0: 0, y: 5}, {x: 3, y0: 0, y: 4}]} />
          <VerticalBarSeries data={[{x: 1, y0: 10, y: 22}, {x: 2, y0: 5, y: 7}, {x: 3, y0: -5, y: 0}]} />
          <VerticalBarSeries data={[{x: 1, y0: 22, y: 33}, {x: 2, y0: 7, y: 11}, {x: 3, y0: 4, y: 8}]} />
        </XYPlot>;
}
```
![image](https://user-images.githubusercontent.com/32575266/46908887-539f6880-cef7-11e8-988e-5b63cb08fd71.png)

If I remove the "stackBy" attribute, the bars appear where I want them to vertically, but no longer align on top of each other horizontally, which is not the desired look:
```
function Chart({data}) {
  return <XYPlot width={300} height={300}>
          <VerticalGridLines />
          <HorizontalGridLines />
          <XAxis />
          <YAxis />
          <VerticalBarSeries data={[{x: 1, y0: 0, y: 10}, {x: 2, y0: 0, y: 5}, {x: 3, y0: 0, y: 4}]} />
          <VerticalBarSeries data={[{x: 1, y0: 10, y: 22}, {x: 2, y0: 5, y: 7}, {x: 3, y0: -5, y: 0}]} />
          <VerticalBarSeries data={[{x: 1, y0: 22, y: 33}, {x: 2, y0: 7, y: 11}, {x: 3, y0: 4, y: 8}]} />
        </XYPlot>;
}
```
![image](https://user-images.githubusercontent.com/32575266/46908904-8e090580-cef7-11e8-9b8c-cc14b98355c5.png)

Any additional thoughts or suggestions would be much appreciated.

**Comment by mcnuttandrew** [comment]
Given that you appear to be working on a linear x axis, I'd suggest using rect series instead of bar series with no stacking, that way you get to control exactly the width of the bars.

**Comment by ABBVelocityDev** [comment]
Thank you for that direction.  I've been able to achieve the desired result using the RectSeries.  Thanks!

![image](https://user-images.githubusercontent.com/32575266/46976848-8b91e180-d098-11e8-8e1a-2d9f83f7b094.png)

**Comment by Krustal** [comment]
@ABBVelocityDev would you be able to share an example?
