### ISSUE TITLE
pass style objects / class names to series

### ISSUE THREAD

**Issue by jckr** [uber/react-vis#101]
I'd like to be able to have complete style control on the series. two ways that could be done: 
passing a style argument to the series, with an object that d3 could just assign to the style.
also, I'd like to be able to pass specific classes to series. I'm thinking we can just pass a string with a class name to add to begin with, and if needs be be more specific. But being able to have full, css-like access to each individual series would be really nice.

**Comment by mcnuttandrew** [comment]
Hey guys, I added the ability to specify class names for series which should enable pretty complete styling for any series element you might want. Given that react-vis currently requires a css import, I feel that allowing for inline styling is a little out of scope for now. I'm going to mark this as done, let me know if I missed anything

**Comment by jckr** [comment]
while I originally asked classes over styles, I feel that passing styling
objects is actually more important. that could be another PR, however, I
think that it might actually be possible to pass "style" objects now
without modification, but I haven't tried it.
