### ISSUE TITLE
Crosshair does not work when xType="time"

### ISSUE THREAD

**Issue by ejmudrak** [uber/react-vis#1029]
The xType="time" is working great on a LineSeries, but when I attempt to display a Crosshair that appears over the corresponding x-axis value, I get errors due to Date being an object.

The data used by the crosshair `values` prop is the same as what the LineSeries is receiving.

<img width="313" alt="screen shot 2018-11-01 at 8 38 49 pm" src="https://user-images.githubusercontent.com/9815085/47887618-c163f380-de16-11e8-9dcf-4441fc10eec6.png">

The error message:

<img width="320" alt="screen shot 2018-11-01 at 8 39 04 pm" src="https://user-images.githubusercontent.com/9815085/47887657-04be6200-de17-11e8-8174-8debd147a244.png">

**Comment by mcnuttandrew** [comment]
May be related to #1031

**Comment by ejmudrak** [comment]
I'm not sure that this is related, time is working fine on the x-axis, I believe there is just a format issue with the Crosshair component. 

<img width="788" alt="screen shot 2018-11-08 at 12 51 10 pm" src="https://user-images.githubusercontent.com/9815085/48217375-31add000-e355-11e8-899c-c306374946b6.png">

**Comment by mathewleland** [comment]
For actual hints and crosshairs, you don't want to use an actual date object.  I would recommend using d3's time format function to turn it into a string that you would like to see on hover.  Or you could just say, for example, `EriksCrossHairValue.x.toString()`to really make it functional for now.

**Comment by ejmudrak** [comment]
Sure! I've made them into strings already, but for the crosshair x to appear over the correct x-axis coordinate, it needs to be the same format as what is supplied to `LineSeries`. Otherwise the crosshair always appears off the left of the graph like so:

<img width="359" alt="screen shot 2018-11-08 at 1 41 50 pm" src="https://user-images.githubusercontent.com/9815085/48219994-11cdda80-e35c-11e8-8eae-5d745ae21a31.png">

**Comment by truncs** [comment]
@ejmudrak I was having the same issue and the way to get around it is by adding a titleFormat to the Crosshair which would convert from a date object to a string which which is a valid react child. This way you don't disrupt the auto positioning of the crosshair.

```
            <Crosshair values={crosshair}
              titleFormat={(d) => ({title: 'Date', value: d[0].x.toLocaleDateString()})}
          />
```
