### ISSUE TITLE
Hint not work if put it inside another component.

### ISSUE THREAD

**Issue by Jiahao01121** [uber/react-vis#1041]
```Hint``` doesn't work if create a functional component and insert that functional component inside the ```XYPlot```.

Eg:
```js
const Tooltip = ({ value }) => {
  return <Hint
    value={value}
  />
}

class Chart extends React.Component {
  ...
  render() {
     <FlexibleXYPlot>
       {hover && <Tooltip value={hover}/>}
     </FlexibleXYPlot>
  }
}
```

error mssg: 
![screenshot 2018-11-13 16 47 41](https://user-images.githubusercontent.com/21186588/48452405-d9673b80-e763-11e8-85f0-74e5ddc56767.png)

**Comment by mcnuttandrew** [comment]
Hint expects a whole bunch of props which are automatically injected from XYPlot, i bet if you change your tool tip to be

```jsx

const Tooltip = (props) => {
  return <Hint
   {...props}
    value={value}
  />
}
```

it might work.

**Comment by Jiahao01121** [comment]
> Hint expects a whole bunch of props which are automatically injected from XYPlot, i bet if you change your tool tip to be
> 
> ```js-jsx
> const Tooltip = (props) => {
>   return <Hint
>    {...props}
>     value={value}
>   />
> }
> ```
> 
> it might work.

It works! Thanks for the quick response.

I am wondering if this is also applicable for all the other element that have to nested inside `XYPlot`?
Also this is something maybe worth to write into react-vis documentation?

Thanks!

**Comment by mcnuttandrew** [comment]
I think this is exactly this issue: #194 I would support a PR that throws a console warn when hint doesn't get what it wants
