### ISSUE TITLE
ChartLabel 'undefined' when deep rendering a component with react-dom TestUtils

### ISSUE THREAD

**Issue by aliciasedlock** [uber/react-vis#1048]
**Issue:**
We use react-vis for many charts in our app.
I recently upgraded to take advantage of the new ChartLabel component. I added it to many exists charts that are used, and that are tested via the react-dom `renderIntoDocument` in its test utils.

When I run these tests with JSDom, the ChartLabel's presence creates this error:
```
TypeError: Cannot read property 'prototype' of undefined
      at isSeriesChild (node_modules/react-vis/dist/utils/series-utils.js:55:30)
      at node_modules/react-vis/dist/utils/series-utils.js:67:21
      at Array.filter (<anonymous>)
      at getSeriesChildren (node_modules/react-vis/dist/utils/series-utils.js:66:53)
      at new XYPlot (node_modules/react-vis/dist/plot/xy-plot.js:161:55)

```

When checking what the import is during the test, the ChartLabel component is undefined. I'm pulling in pieces of react-vis via require.

If I remove the ChartLabel component from the chart, the tests pass.
Viewing the app locally also doesn't throw errors, and the chart label displays as expected.
Not sure if this component does anything different than others, as I've never run into an issue of not having charts render via this method in testing.

**Comment by aliciasedlock** [comment]
Nevermind - file this under user error. 😅

**Comment by chasmfiend** [comment]
If you don't mind me asking, I'm running into the same error, do you remember what you fixed?

**Comment by hegerni** [comment]
I'm not positive if my error is the same, but I'm getting a "TypeScript error: Module '"react-vis"' has no exported member 'ChartLabel'." I think I am importing everything correctly, but I guess maybe not. Would either of you be willing to help me get my ChartLabel to appear properly? I'm new to this so it's probably something dumb. For reference I am currently trying to import it on the same line as all my other components with the from 'react-vis' afterward.
