### ISSUE TITLE
Width and height of the treemap chart

### ISSUE THREAD

**Issue by GojkoC** [uber/react-vis#1052]
Hi, thanks for the great library. 
I'm trying to get certain height and width for the treemap chart, but child div's are not expanding to the full width and height of the base div. Does someone have any idea how to fix this.

**Comment by GojkoC** [comment]
Never mind, I resolved it by adding margin prop with zero values.

**Comment by endmaster89** [comment]
Hi, @GojkoC  I have trouble with making treemap chat responsive.
Do you know the tricks?

**Comment by GojkoC** [comment]
@endmaster89 I didn't have the need for responsive chart, so I can't help you. You can try controlling the width and height of the wrapper div of the chart.
