### ISSUE TITLE
Horizontal Bar Series renders labels off of chart

### ISSUE THREAD

**Issue by tonyneel923** [uber/react-vis#1058]
When offsetting the labels from the bars the labels flow off of the page when you shrink the page down. Below is the code and an image.

``const FinancialBarChart = props => {
  return (
    <FinancailChart>
      <YtdHeader {...props.data} />
      <HeaderLabel size={'20px'} padding={'50%'}>
        Details
      </HeaderLabel>
      <FlexibleXYPlot height={800} yType="ordinal" margin={MARGIN_PLOT}>
        <YAxis style={{ fill: 'white' }} />
        <HorizontalBarSeries
          animation={{ duration: 0.5 }}
          data={props.data.barChartData}
          color="gray"
          fill="#28b7e0"
          // stroke="red"
          style={{ rx: '10', ry: '10' }}
        />
        <LabelSeries
          animation={{ duration: 0.5 }}
          style={{ fill: 'white', fontSize: '20px' }}
          data={map(d => {
            return {
              ...d,
              xOffset: 20,
            };
          }, props.data.barChartData || [])}
          labelAnchorX='end-alignment'
          labelAnchorY='middle-alignment'
        />
      </FlexibleXYPlot>
    </FinancailChart>
  );
};``

![image](https://user-images.githubusercontent.com/5866014/49392317-5181ab00-f6eb-11e8-965a-66f84d71bbb7.png)

**Comment by justice-art** [comment]
Hi @tonyneel923 !
Have you fixed it?
