### ISSUE TITLE
Colored Label in the middle of a chart

### ISSUE THREAD

**Issue by CarinSchreiner** [uber/react-vis#1060]
Hi,
I'm trying to place a colored label in the Middle of my Radialchart.

Till now I tried two different ways:

With Hint:

                          `<RadialChart
                                className={'average-chart'}
                                innerRadius={100}
                                radius={140}
                                getAngle={d => d.theta}
                                data={averageData}
                                width={300}
                                height={300}
                                padAngle={0.04}
                                colorType="literal"
                                center={{x: 0, y: 0}} 
                                >
                                <Hint value={{angle0: 0, angle: 6.28319, radius0: -1, radius: 0, x: 0, y: 0 }}
                                      align={{vertical: 'top', horizontal: 'left'}}>
                                    <Card style={{ backgroundColor: '#282c34', borderColor: '#282c34', color: averageColor, anchor: "middle", fontSize: "25px" }}>
                                        {averageValue}
                                    </Card>
                                </Hint>
                            </RadialChart>`

<img width="304" alt="bildschirmfoto 2018-12-06 um 08 59 59" src="https://user-images.githubusercontent.com/37693925/49570539-34411c80-f937-11e8-8b56-684fb1ddaae2.png">

I tried to change the values (angle0, angle, radius etc.) to push the Hint in the middle of the chart, but it seems like the position of the Hint is affected by the rest of my page, so it never stays in the middle of the chart when the content on my page is changing. I also tried to apply style={{textAnchor : 'middle'}} but it didn't changed a thing.

With LabelSeries

                            `<RadialChart
                                className={'donut-chart-example'}
                                innerRadius={100}
                                radius={140}
                                getAngle={d => d.theta}
                                data={averageData}
                                width={300}
                                height={300}
                                padAngle={0.04}
                                colorType="literal"
                                center={{x: 0, y: 0}}

                            >
                                <LabelSeries data={[{x: 0, y: 0, label: averageValue, style:{textAnchor: 'middle', color: averageColor}}]}/>
                            </RadialChart>`

OR

                            `<RadialChart
                                className={'donut-chart-example'}
                                innerRadius={100}
                                radius={140}
                                getAngle={d => d.theta}
                                data={averageData}
                                width={300}
                                height={300}
                                padAngle={0.04}
                                colorType="literal"
                                center={{x: 0, y: 0}}

                            >
                                <LabelSeries data={[{x: 0, y: 0, label: averageValue, style:{textAnchor: 'middle', color: averageColor}}]}
                                      align={{vertical: 'top', horizontal: 'left'}}>
                                    <Card style={{ backgroundColor: '#282c34', borderColor: '#282c34', color: averageColor, anchor: "middle", fontSize: "25px" }}>
                                        {averageValue}
                                    </Card>
                                </LabelSeries>
                            </RadialChart>`

<img width="303" alt="bildschirmfoto 2018-12-06 um 09 23 51" src="https://user-images.githubusercontent.com/37693925/49571275-1eccf200-f939-11e8-9f96-752a936140c9.png">

This time the Label is perfectly adjusted in the middle of the chart, but I seems like I can't change the color of the text.

**Comment by mcnuttandrew** [comment]
Hey @CarinSchreiner 

Your on the right track! I think there are specific ways that you push your two approaches to work as desired, but I have some alternative suggestions for you:

- If you don't need your visualization to be svg (eg if it's rendering only on a webpage) then it might be a little easier to center your label using flexes, something like

```
<div
  style={{
    display: 'flex', 
    alignItems: 'center',
    justifyContent: 'center'
  }}>
  <RadialChart
    className={'donut-chart-example'}
    innerRadius={100}
    radius={140}
    getAngle={d => d.theta}
    data={[{theta: 6, color: 'yellow'}, {theta: 3}]}
    width={300}
    height={300}
    padAngle={0.04}
    colorType="literal"
    center={{x: 0, y: 0}}

    />
    <div style={{
      background: 'gray',
      position: 'absolute',
      padding: '5px',
    }}>
    AVG VAL: 2
    </div>
</div>
```

- On the other hand if you do need just svg, you could combine a labelseries with a polygon series:

```
<RadialChart
  className={'donut-chart-example'}
  innerRadius={100}
  radius={140}
  getAngle={d => d.theta}
  data={[{theta: 6, color: 'yellow'}, {theta: 3}]}
  width={300}
  height={300}
  padAngle={0.04}
  colorType="literal"
  >
  <PolygonSeries data={[
    {x: -0.2, y: -0.2},
    {x: 0.2, y: -0.2},
    {x: 0.2, y: 0.2},
    {x: -0.2, y: 0.2}
  ]} 
  color="red" 
  style={{
    stroke: 'black'
  }}/>
  <LabelSeries data={[{x: 0, y: 0, label: 'avg val', style: {}}]} />
</RadialChart>
```

Hope that helps

**Comment by CarinSchreiner** [comment]
Hey @mcnuttandrew 

Thank you for your fast reply. I chose the first option and it works totally fine.

<img width="321" alt="bildschirmfoto 2018-12-13 um 10 08 10" src="https://user-images.githubusercontent.com/37693925/49927771-091e7600-febf-11e8-8388-99a4f006166b.png">

That helped a lot. Thank you
