### ISSUE TITLE
Allow styling (beyond color/opacity) for individual bars in VerticalBarSeries

### ISSUE THREAD

**Issue by stdmn** [uber/react-vis#1070]
I left a note on #838 but that issue was already closed, so I'm making a new issue.

It would be immensely useful to have the ability to style an individual element beyond just the color. For example, I'm trying to re-create Kepler.gl's timeline element using react-vis (the original uses a custom-drawn SVG). In order to properly render the selection effect (bar width), there needs to be a way to tell each element what width it should be.

Taking a quick gander at the code, it seems most of the attributes of each element are determined by the parent, not by the embedded information in each data point.

Are there any plans to make it possible to style individual elements?

<img width="1038" alt="kepler gl" src="https://user-images.githubusercontent.com/17128916/50302749-07255b80-0459-11e9-9bbf-3e2b0ed00cd3.png">

**Comment by mukesh-urbanpiper** [comment]
@stdmn Hey, did you find any solution for this?

**Comment by stdmn** [comment]
I ended up doing a bit of a hack and using the [Rect Series](http://uber.github.io/react-vis/documentation/series-reference/rect-series) which allow you to specify the x0 and x1 for each bar. So for the ones I wanted to be 50% of full width I'd do x0 + .25 * (x1 - x0) and x1 - .25 * (x1 - x0).
