### ISSUE TITLE
Invalid link in documentation / missing empty chart code

### ISSUE THREAD

**Issue by goszczynskip** [uber/react-vis#1073]
When looking at documentation there is **dontCheckIfEmpty (optional)** parameter description in **XYPlot** section. Presented example of empty chart has link to source file. This link is giving 404. 
Invalid link `https://github.com/uber/react-vis/blob/master/showcase/plot/empty-chart.js`
![obraz](https://user-images.githubusercontent.com/22256011/50480536-c2f80500-09dc-11e9-8d0a-471cb1f29660.png)

**Comment by mcnuttandrew** [comment]
(I would happily accept a PR fixing this!)
