### ISSUE TITLE
Hint or Crosshair in Labeled Heatmap

### ISSUE THREAD

**Issue by GustavoCarvalho** [uber/react-vis#1074]
How can I implement Crosshair or Hint in Labeled Heatmap? I've tried it anyway. I want the heatmap label to show the popup as soon as the mouse passes over the heatmap cell. Like the Mark Series Canvas example.

**Comment by mcnuttandrew** [comment]
Hey @GustavoCarvalho 

I added hovering using hint to both of the heatmap series examples, you can check it out here: #1078

**Comment by mcnuttandrew** [comment]
I'm going to close this as the example has been merged in.
