### ISSUE TITLE
Add the better documentation on how to use the scales in react-vis

### ISSUE THREAD

**Issue by ranjithnori** [uber/react-vis#108]
Please provide an example of how to use fill scale and innerRadius scale. Here's how I tried to do it. It didn't work as expected. I couldn't find any examples about the same.

```js
<RadialChart
  radiusDomain={[0,20]}
  innerRadiusDomain={[5,9]}
  data={[
    {angle: 2, fill: '#1a3141', radius: 10, innerRadius: 7},
    {angle: 7, fill: '#ff6f00', radius: 10, innerRadius: 7},
    {angle: 5, fill: '#1a3242', radius: 10, innerRadius: 7}
  ]}
  width={300}
  height={300} />
```

**Comment by pawel2105** [comment]
Why is this issue closed? The documentation still isn't really clear.

**Comment by mcnuttandrew** [comment]
Underlying this ticket is a bug in the way that the radial chart was processing the inner/outer radii. The documentation for scale still **should** be improved, however in the new 2.0.0-beta release this should be a lot better/more logical to manipulate.
