### ISSUE TITLE
CustomSVGSeries: provide positionFunctions

### ISSUE THREAD

**Issue by FunkMonkey** [uber/react-vis#1085]
It would be nice if the `customComponent` functions in a `CustomSVGSeries` could have access to the `positionFunctions` used to transform data coordinates to pixel coordinates. I just had a situation where I needed to draw a rect, where the width depended on additional data. Thus I need the `positionFunctions` for the other corners...

This fix should be pretty easy, just add `positionFunctions` as the fourth parameter in [custom-svg-series.js#103 and 109](https://github.com/uber/react-vis/blob/master/src/plot/series/custom-svg-series.js#L103). It's all there already...

Thanks a lot!

**Comment by mcnuttandrew** [comment]
I would gladly accept a PR to this effect!
