### ISSUE TITLE
Specify custom x/y accessors

### ISSUE THREAD

**Issue by austinhyde** [uber/react-vis#109]
Suppose I have some data that looks like

```javascript
let data = [
  { date: moment(), value: 0 },
  { date: moment().add(1, 'min'), value: 0.5 },
  { date: moment().add(2, 'min'), value: 1 }
];
```

I'd like to display it in a `MarkSeries`and use `date` for the x value and `value` for the y value. The [xy-plot docs](https://github.com/uber/react-vis/blob/master/docs/xy-plot.md#x) list `x` and `y` props, which I'd expect to behave like accessors:

> ##### X
> Type: number|Object
> Exact X position of all series points in pixels or a series object.

That *seems* like what I'd expect, except... why would I want to set all X values to a static number, and what is a "series object"?

Skimming the library code quickly shows the [following usage of the x and y props](https://github.com/uber/react-vis/blob/master/src/lib/plot/series/mark-series.js#L59):

```javascript
...
      .attr('cx', this._getAttributeFunctor('x'))
      .attr('cy', this._getAttributeFunctor('y'));
```

Since that does indeed seem like what I want, I tried it:

```javascript
<MarkSeries data={data} x={d => d.date.valueOf()} y={d => d.value} />
```

Except that apparently this literally means "use this function as the x value", since this is what gets rendered:

```html
<circle r="5" cx="function x(d) {
    return d.date.valueOf();
}" cy="function y(d) {
    return d.value;
}" style="opacity: 1; fill: rgb(255, 127, 14); stroke: rgb(255, 127, 14);"></circle>
```

IMHO, this is a fairly obvious violation of [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). So, the crux of this feature request is basically:

1. If it is not currently possible to provide custom accessors, either add an additional check that would interpret function `x`/`y` props as accessors, or add explicit props to handle this case
2. Clarify existing prop documentation, and add documentation describing how to specify custom accessors

In the meantime, the obvious workaround is to simply map the data beforehand, but this is sometimes not desired.

**Comment by bulyonov** [comment]
@austinhyde Thank you for your comment.

The goal of the library was to keep the API as simple as possible and rely on the user in the questions of performance and data preparation. We want the user to provide well structured data and deal with such corner cases as null or undefined values of objects (currently they will be treated as zeros). Besides that, the value accessors will unfortunately solve only the part of the problem: the values are frequently stored in much more complex (e.g. nested) objects.

I created the task to improve the documentation for the scales: there are some certain gaps in it. Meanwhile please check out the [existing docs for scales and date](https://github.com/uber/react-vis/blob/master/docs/scales-and-data.md), probably you'll find some of the answers there.

**Comment by bulyonov** [comment]
I also created [a related task](148) to track the progress of the documentation update: currently the docs for scales are very poor.
