### ISSUE TITLE
x-axis is not rounded correctly

### ISSUE THREAD

**Issue by timfpark** [uber/react-vis#110]
For some datasets, I am getting x-axis values that are not rounded correctly (in a way that looks like JavaScript math issues):

![screen shot 2016-07-01 at 11 06 29 am](https://cloud.githubusercontent.com/assets/712001/16530260/18a854a6-3f7c-11e6-9c5b-3bd926a27f3f.png)

I'm using the following data:

`[{"x":0.13372623292811447,"y":8730.31524},{"x":0.13767990338492847,"y":8730.31524},{"x":0.14021854318724314,"y":8730.31524},{"x":0.14459258531430835,"y":8733.59608},{"x":0.14800638604875163,"y":8733.59608},{"x":0.15206944322541138,"y":8733.59608},{"x":0.15589290660094193,"y":8730.31524},{"x":0.15860517763068477,"y":8730.31524},{"x":0.16360614955208888,"y":8730.31524},{"x":0.16629781423563672,"y":8730.31524},{"x":0.16899335460828133,"y":8730.31524},{"x":0.17372068269523036,"y":8730.31524},{"x":0.17733982284321775,"y":8717.19188},{"x":0.18057300786272124,"y":8717.19188},{"x":0.18574030211043183,"y":8717.19188},{"x":0.18778633875369594,"y":8717.19188},{"x":0.19259757534779726,"y":8707.34936},{"x":0.19453529666066735,"y":8707.34936},{"x":0.19924344686698048,"y":8707.34936},{"x":0.20178002970220332,"y":8707.34936},{"x":0.2042674345250027,"y":8707.34936},{"x":0.209027041453048,"y":8707.34936},{"x":0.21327188430386196,"y":8710.6302},{"x":0.2177737369627652,"y":8710.6302},{"x":0.2218624072771569,"y":8710.6302},{"x":0.22667147355165565,"y":8713.911039999999},{"x":0.2321813063785132,"y":8717.19188},{"x":0.23877503918494336,"y":8717.19188},{"x":0.2441586917489518,"y":8717.19188},{"x":0.24945764943397827,"y":8717.19188},{"x":0.25370822690092737,"y":8717.19188},{"x":0.25641857274100627,"y":8723.75356},{"x":0.25882780470735706,"y":8723.75356},{"x":0.2638082071705127,"y":8723.75356},{"x":0.26664587966783404,"y":8723.75356},{"x":0.26832477299566954,"y":8723.75356},{"x":0.2733579972806675,"y":8723.75356},{"x":0.2752776761027687,"y":8723.75356},{"x":0.2783734024377751,"y":8723.75356},{"x":0.28245611072583077,"y":8723.75356},{"x":0.28775145529811513,"y":8723.75356},{"x":0.2903362806708258,"y":8723.75356},{"x":0.2941538236063945,"y":8723.75356},{"x":1.5444990373775116,"y":8723.75356},{"x":1.5491845904068675,"y":8723.75356},{"x":1.5521358745099059,"y":8723.75356},{"x":1.555886284512655,"y":8723.75356},{"x":1.5609847665625602,"y":8723.75356},{"x":1.565241070919272,"y":8723.75356},{"x":1.5697297636333833,"y":8723.75356},{"x":1.5722594778320198,"y":8723.75356},{"x":1.5747300377331137,"y":8723.75356},{"x":1.5798770891728646,"y":8723.75356},{"x":1.5864565572467677,"y":8717.19188},{"x":1.5922122694191871,"y":8717.19188},{"x":1.5978949674875182,"y":8717.19188},{"x":1.6032786200515268,"y":8717.19188},{"x":1.6081509473155968,"y":8713.911039999999},{"x":1.614573037723672,"y":8713.911039999999},{"x":1.6207216268428868,"y":8710.6302},{"x":1.6262786256801522,"y":8707.34936},{"x":1.6316034600548248,"y":8707.34936},{"x":1.636508530865456,"y":8707.34936},{"x":1.6416592994422725,"y":8707.34936},{"x":1.6463744659946031,"y":8717.19188},{"x":1.6512891049183542,"y":8717.19188},{"x":1.6553799024220655,"y":8717.19188},{"x":1.6590558075069963,"y":8717.19188},{"x":1.6609926306871121,"y":8717.19188},{"x":1.663144766237228,"y":8730.31524},{"x":1.6649006568403961,"y":8730.31524},{"x":1.6676788431357485,"y":8730.31524},{"x":1.6695628421863549,"y":8730.31524},{"x":1.6737140159392359,"y":8730.31524},{"x":1.6764371706684351,"y":8730.31524},{"x":1.6785244605036236,"y":8730.31524},{"x":1.6806741692885814,"y":8730.31524},{"x":1.684736369912649,"y":8733.59608},{"x":1.687551882372338,"y":8733.59608},{"x":1.6897834004559997,"y":8733.59608},{"x":1.6923438784223217,"y":8730.31524},{"x":1.6947079104944547,"y":8730.31524},{"x":1.6972293576311177,"y":8730.31524},{"x":1.7019078499031963,"y":8730.31524},{"x":1.7039884603937856,"y":8730.31524}]
`
with an XYPlot that looks like this:

`    <XYPlot width={620} height={190}>
            <XAxis
              labelFormat={v => `${v} mi.`}
            />
            <YAxis
              labelFormat={v => `${v} ft.`}
            />
            <AreaSeries marginLeft={70} marginTop={20} fill="#9DC7F1" color="#7CB5EC" opacity="0.9" data={this.getElevationData()}/>
    </XYPlot>`

**Comment by bulyonov** [comment]
Hey 	@timfpark!

I understood your point, but it doesn't seem to be the problem on our side. You get the value in `labelFormat` function which is not formatted at all. This means, that your function is responsible for formatting this value. Precision issues in JavaScript are quite common, you should format the number first and *after that* append the "mi." in the end.

I also highly suggest to check out the latest version of react-vis: some of the formatting issues are gone there (please take a look at [the list of changes first](https://github.com/uber/react-vis#change-log)).
