### ISSUE TITLE
Touch support for Highlight

### ISSUE THREAD

**Issue by stroemdev** [uber/react-vis#1102]
When using highlight with touch devices you cannot drag or brush. 

Today using the device emulator in Chrome, the touch events just navigates around the page:

![9sugx9vd0p](https://user-images.githubusercontent.com/8787786/52346555-1ddf3c00-2a20-11e9-9875-9cf65db86cd9.gif)

I started prototyping this feature registering onTouchMove event listener instead of using the onTouchMove property of the rect element. This event listener is registered as an "active" event listener (https://developers.google.com/web/updates/2017/01/scrolling-intervention) so that preventDefault is available when the component is brushing or dragging.  

With "native" event listener
![lszpi00ldi](https://user-images.githubusercontent.com/8787786/52346596-34859300-2a20-11e9-91d8-afa77e83fafa.gif)

Taking this approach any movement in the chart will be "prevented" and interpreted as a brush/drag. 
And might impact overall performance on the page when this listener is active.

I just wanted to check if there is any interest in making this change in the core library or if I should continue the work in a fork.

**Comment by deelam** [comment]
I would like this feature.

**Comment by kitipong-sage** [comment]
I like this feature.

**Comment by adammartiska** [comment]
I would really appreciate this feature, because we need to implement this functionality! Is there any progress for this?

**Comment by rlaffers** [comment]
I have fixed touch event support for brushing in my fork https://github.com/rlaffers/react-vis/tree/touch-events-brushing
This is based off the 1.11.7 release, so I can't PR this into master. Maybe I will find time to port those changes into the 2.x react-vis version (master) - but feel free to do it yourself if you need touch event support in 2.x react-vis.
