### ISSUE TITLE
Custom LabelSeries component

### ISSUE THREAD

**Issue by achakravarty** [uber/react-vis#1103]
Currently, the `LabelSeries` component only supports a text component. Is there a plan to support the usage of custom components instead of just text in the LabelSeries. I am aware that the styling can be done via the `style` prop, but was feeling it would be great if custom components could be added.

I am thinking something on the lines of
```js
<LabelSeries data={data}>
    {(attrs) => <CustomComponent {...attrs}/>}
</LabelSeries>
```
Or
```js
<LabelSeries data={data} component={CustomComponent}/>
```

Or maybe the data component could be enhanced to include the component directly i.e
```js
const data = [{ x: 0, y: 0, label: <CustomComponent/> }]
```

**Comment by mcnuttandrew** [comment]
I would check out the CustomSVG Series which was made for exactly just such a use case https://uber.github.io/react-vis/documentation/series-reference/custom-svg-series

**Comment by mcnuttandrew** [comment]
I'm going to close this as the above solution is the recome
