### ISSUE TITLE
 margins on xy plot

### ISSUE THREAD

**Issue by emasreed** [uber/react-vis#1107]
This code is producing a chart with a huge margin to the right that I can not change with css even when using an !important tag to override the native styling.

![image](https://user-images.githubusercontent.com/22358350/52790639-0b26c180-3035-11e9-863c-67c2ff7845bc.png)

```
<div className="plot">
                <div className='chart'>
                <XYPlot xType="ordinal" width={500} height={300} xDistance={100} stackBy="y">
                    <HorizontalGridLines/>
                    <VerticalGridLines/>
                    <XAxis/>
                    <YAxis/>
                    {bars}
                    {lines}
                    {lineMarks}
                    {filledLine}
                </XYPlot>
                </div>

                    <DiscreteColorLegend items={values} colors={colorRange} width={100}/>

            </div>
```

**Comment by IgorWilbert** [comment]
Hi @emasreed ! Not sure if I understand the issue. If you want to decrease the width of the right margin, couldn't you just change the values of `width={500} height={300}`? Or would you like to just align it to the center? Thanks!

**Comment by emasreed** [comment]
It was actually an issue with the react-strap wrapper. Because I wasn't changing the height at the column level, it was not changing the actual height. Therefore, the column height was being passed to the chart and it was therefore adding a margin to get to the full height of the column.
