### ISSUE TITLE
SearchableDiscreteColorLegend does not implement onMouseEnter and onMouseLeave

### ISSUE THREAD

**Issue by SatorSquare** [uber/react-vis#1112]
I would like to have an on hover interaction with the items of a SearchableDiscreteColorLegend however it does not seem to expose the onMouseEnter and onMouseLeave properties of the DiscreteColorLegend that it wraps. Would it be possible to expose these properties, or is there some limiting factor?

**Comment by mcnuttandrew** [comment]
I would support a PR to add these properties!

**Comment by philjestin** [comment]
May I take a stab at this?
