### ISSUE TITLE
Disabling axis label sorting?

### ISSUE THREAD

**Issue by zawadzkip** [uber/react-vis#1119]
I'm using a VerticalBarSeries with a number y axis and string x axis values. 

`const data = [ {x:'Sunday', y: 5}, {x: 'Monday', y: 10},  {x:'Friday', y:6}];`

I pass in the values sorted by Sunday, Monday, Friday order, similar to what a standard calendar week would be. But I believe the axis is overriding this order, and alphabetically sorting. So my axis values above would come out to be "Friday", "Monday", "Sunday".

Is there any way to force the xaxis to respect my order for the data provided?

**Comment by zawadzkip** [comment]
Mistake on my part. Closing this.

**Comment by pateketu** [comment]
what was the mistake?

**Comment by zawadzkip** [comment]
@pateketu Unfortunately I don't remember exactly and I don't want to lead you down the wrong path.
