### ISSUE TITLE
React-vis crashes if animation is defined for all chart types

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#114]
I'm seeing a bug wherein if animation duration is set via a prop like:

`animation: {duration: 500},`

Then I get a crash error from react-vis like

![screen shot 2016-07-21 at 10 27 33 am](https://cloud.githubusercontent.com/assets/6854312/17032372/c533aa7a-4f2d-11e6-84d7-784e867dc99b.png)

This is completely avoidable by not declaring animation. This appears to affect all chart types

**Comment by bulyonov** [comment]
Fixed in #115 and #126
