### ISSUE TITLE
All datasets disabled clears view

### ISSUE THREAD

**Issue by JelleBlaauw** [uber/react-vis#1175]
I have a chart with a legend looking like this:
![image](https://user-images.githubusercontent.com/20815406/57515145-3ce8b500-7312-11e9-9121-6bdcc4cccda7.png)

Whenever I click an item in the legend, it toggles whether or not the dataset (two series) is enabled. This is done by the code below:

```js
_clickHandler = item => {
    const {items} = this.state;
    item.disabled = !item.disabled;
    this.setState({items});
};
```
(and further on...)
```js
<FlexibleWidthXYPlot
    animation={true}
    xType="ordinal"
    stackBy="y"
    margin={{right: 40}}
    height={300}>
    <DiscreteColorLegend
        onItemClick={this._clickHandler}
        style={{position: 'absolute', left: '50px', top: '10px'}}
        orientation="horizontal"
        items={DATASETS}
    />
    <HorizontalGridLines/>
    <XAxis/>
    <YAxis/>
    <YAxis orientation="right"/>
    {
        DATASETS
            .map(({title, color, disabled}, index) => {
                    return disabled ? false : [
                        <VerticalBarSeries
                            onNearestX={index === 0 ? (value, {index}) => this.setState({crosshairValues: DATA.map(d => d[index])}) : null}
                            cluster={title}
                            color={new TinyColor(color).lighten(10).toHexString()}
                            data={DATA[index]}
                        />,
                        <VerticalBarSeries
                            cluster={title}
                            color={color}
                            data={DATA[index + 1]}
                        />
                    ]
                }
            )
    }
</FlexibleWidthXYPlot>
```
However, when I disabled all datasets, the whole chart disappears, along with axes and legend. This way I cannot restore the visibility of any of the datasets, since, well, everything's gone.

How can I retain the chart and legend without any enabled series?

**Comment by mcnuttandrew** [comment]
There's a somewhat obscure prop on XYPlot that i think will handle this: dontCheckIfEmpty https://uber.github.io/react-vis/documentation/api-reference/xy-plot 

If that doesn't work then you could make an empty version of your datasets and use that as default when DATASETS is empty.

**Comment by JelleBlaauw** [comment]
I know about `dontCheckIfEmpty`, but unfortunately this did not solve my issue. An empty version of my datasets seems like a plan, but it feels rather custom/hacky for something that should be built in, in my opinion. Anyway, thanks for now, I'll try and implement your suggestion.

**Comment by JelleBlaauw** [comment]
Alright, it was really easy to implement, but I thought I'd share my solution anyway. In my `render` method, I added the following:
```js
const allDatasetsDisabled = datasets.every(({disabled}) => disabled);
const fallBackData = data[0].map(({x}) => ({x: x, y: 1}));
```
and in my `<FlexibleWidthXYPlot/>` I changed `animation={true}` to `animation={!allDatasetsDisabled}`, so that it won't cause animations when you switch from no datasets to a visible one.

Also, my loop responsible for drawing the series now looks like this:
```js
{
    allDatasetsDisabled
        ? <VerticalBarSeries
            data={fallBackData}
            color="transparent"
        />
        : data.map((_data, dataIndex) => {
            return !datasets[~~(dataIndex / 2)].disabled
                ? <VerticalBarSeries
                    key={dataIndex}
                    data={_data}
                    cluster={datasets[~~(dataIndex / 2)].title}
                    color={this._colorHandler(datasets, dataIndex)}
                    onNearestX={crosshairDataIndex === dataIndex
                        ? this._onNearestXHandler(data)
                        : null}
                />
                : false
        })
}
```
That's all! :)

**Comment by JelleBlaauw** [comment]
Oh, by the way, it's better to determine `allDatasetsDisabled`'s value in your `updateState` functionality, and `fallBackData` in your constructor, but that's not really relevant to react-vis.
