### ISSUE TITLE
Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by nklijia** [uber/react-vis#118]
I am using the makeWidthFlexible() funciton to make the plot auto updating the size.
But many times, I am getting this error
"Cannot read property 'offsetWidth' of undefined"

This error is from this line 
https://github.com/uber/react-vis/blob/master/src/lib/make-vis-flexible.js#L115

**Comment by salincakli** [comment]
getDOMNode() was replaced by reactDOM.findDOMNode with React v 0.15

**Comment by chrisirhc** [comment]
Looks like this can happen when the `containerElement` isn't found in the DOM so there's an additional check needed there.

**Comment by bulyonov** [comment]
Resolving this issue, since #120 was merged in. The fix will be on the next release (0.5)
