### ISSUE TITLE
How to draw a venn diagram using react-vis?

### ISSUE THREAD

**Issue by didiaoshengjianbao** [uber/react-vis#1198]
When I am using react-vis I found I am failed to draw a venn diagram, did the react-vis support drawing venn or how can I draw a simplist venn with tooltip using react-vis?

**Comment by mcnuttandrew** [comment]
Unfortunately venn-diagrams are shockingly tricky! I'd consult this library if there are super necessary: https://github.com/benfred/venn.js/ If you are commited to using react-vis, i'd probably sketch out the venn diagram you want and then use MarkSeries to draw them (if it's circles) or Polygon series's
