### ISSUE TITLE
nonAnimatedProps doesn't work

### ISSUE THREAD

**Issue by duc-duong-energetiq** [uber/react-vis#1216]
I found `nonAnimatedProps` doesn't work or I am doing wrong. There is also a lack of example for how to use `nonAnimatedProps`

Here is the work, I just want to suppress animation for `color` or `y` props, but it seems nothing happens

https://stackblitz.com/edit/react-utlbb9

also found out in the source code, none of `series` code has `nonAnimatedProps` checking and excluding, only `axis` code has that logic

**Comment by Fensterbank** [comment]
@duc-duong-energetiq These are the animated props:
```
const defaultAnimatedProps = [
  'xRange',
  'yRange',
  'xDomain',
  'yDomain',
  'width',
  'height',
  'marginLeft',
  'marginTop',
  'marginRight',
  'marginBottom',
  'tickSize',
  'tickTotal',
  'tickSizeInner',
  'tickSizeOuter'
];
```
see https://github.com/uber/react-vis/blob/7a20f3b14f1d4a21f9965f1c589f32ed2bac8a9b/src/plot/axis/axis.js#L33

There is really no documentation of it, I found it by searching around in the code.
You have to try out which property prevents the animation you want to prevent. ;)

It is passed directly to the prop, e.g. `animation={{ nonAnimatedProps: ['xDomain'] }}`.

**Comment by duc-duong-energetiq** [comment]
> @duc-duong-energetiq These are the animated props:
> 
> ```
> const defaultAnimatedProps = [
>   'xRange',
>   'yRange',
>   'xDomain',
>   'yDomain',
>   'width',
>   'height',
>   'marginLeft',
>   'marginTop',
>   'marginRight',
>   'marginBottom',
>   'tickSize',
>   'tickTotal',
>   'tickSizeInner',
>   'tickSizeOuter'
> ];
> ```
> 
> see
> 
> https://github.com/uber/react-vis/blob/7a20f3b14f1d4a21f9965f1c589f32ed2bac8a9b/src/plot/axis/axis.js#L33
> 
> There is really no documentation of it, I found it by searching around in the code.
> You have to try out which property prevents the animation you want to prevent. ;)
> 
> It is passed directly to the prop, e.g. `animation={{ nonAnimatedProps: ['xDomain'] }}`.

Thanks for supporting, but nevermind, this company, and the library should be gone for good, I changed to other well maintained and supported library.
