### ISSUE TITLE
`animation` default property not set in plots

### ISSUE THREAD

**Issue by alphastorm** [uber/react-vis#123]
The [animation docs](https://github.com/uber/react-vis/blob/master/docs/animation.md) say that child components will be animated by default.  However, the property is not set in [defaultProps](https://github.com/uber/react-vis/blob/master/src/lib/plot/xy-plot.js#L68).  This appears to affect all chart types.

**Comment by bulyonov** [comment]
Fixed in #126. Please refer to the updated docs when 0.6 will be releaed.
