### ISSUE TITLE
Problem with horisontal legend.

### ISSUE THREAD

**Issue by aplinxy9plin** [uber/react-vis#1235]
Have some problem with horizontal orientation. I wrote orientation="horizontal", but my legend look like 2nd screenshot...
![image](https://user-images.githubusercontent.com/6073897/62937840-ea7ad100-bdf7-11e9-90e4-9922c719f87d.png)
![image](https://user-images.githubusercontent.com/6073897/62937882-0aaa9000-bdf8-11e9-8c8c-e4fb85304584.png)

**Comment by wroughtec** [comment]
Have you included the stylesheet in the app?

**Comment by mcnuttandrew** [comment]
I believe this will be fixed if the stylesheet is imported. Additionally, this problem will automagically fix itself once the styletron/styled-components story is completed (#1334
