### ISSUE TITLE
Waterfall chart

### ISSUE THREAD

**Issue by marvin-solano** [uber/react-vis#1236]
Hello, this is a question, not an issue.

Is there any way to configure the bar charts to work as a waterfall?

**Comment by marvin-solano** [comment]
I was able to "mimic" this by using the **y0** property of the vertical bar chart:
https://uber.github.io/react-vis/documentation/series-reference/bar-series

**Comment by larissa-n** [comment]
That's helpful! Mind sharing an example? Thank you!
