### ISSUE TITLE
add min-width to Rect Series

### ISSUE THREAD

**Issue by Degooya** [uber/react-vis#1265]
Could you please add the possibility to add a min-width for the rectangles ? My bars are so extremely thin, you can barely see them less then 0.2 px. I know you could do that with css but that doesn't work for Firefox

**Comment by ToniIltanen** [comment]
you could also set the xDomain differently, to allow more size to your bars. 
x0 - x1 is the width of the bar, so if the x0 is ex. 250 and x is 255, the width is 5. The rest is up to the x axis.

example, if your x values are 0-100, you could se the xDomain to 0-1000 and assign the the range of x0 and x1 to 10, scaling up to the x axis.

**Comment by mcnuttandrew** [comment]
I think @ToniIltanen 's approach is right here. Adding a minwidth for the rect series isn't really appropriate as it would invalidate the meaning of the continuous axis. If you need something malleable in that manner, probably use a barseries?
