### ISSUE TITLE
How to set the position of LabelSeries relative to VerticalBarSeries?

### ISSUE THREAD

**Issue by Novizh** [uber/react-vis#1268]
I want to add label on top of each vertical bar series using LabelSeries, the label should be the value of y. I understand the LabelSeries format data reference of x and y must be a **number**, but how to apply it in vertical bars which has x value of **string** ?

**Comment by Novizh** [comment]
Turns out, I just have to change the datatype from **string** to **any**, but I have three bar series which related to the same X, and the label position is centered to X, not relative to the bar.

**Comment by teatalay** [comment]
Same here
https://github.com/uber/react-vis/issues/1264

**Comment by Ghivan** [comment]
Any updates, also have the same issue: labels on multiple series are centered according x (string) value. Also stacked series labels do not render properly

**Comment by Novizh** [comment]
I'm sorry, no more update for this issue, the project deadline forced me to use another chart library, but I think #1264 have figured out what I intended to do in the first place.
