### ISSUE TITLE
@types/react-vis not available which causes issues in build

### ISSUE THREAD

**Issue by akshaybheda** [uber/react-vis#1278]
@types/react-vis package is not available. It causes issue and i have to define types for each project

**Comment by EvgenyGulyaev** [comment]
You cand use my types => https://github.com/EvgenyGulyaev/types-react-vis

**Comment by mcnuttandrew** [comment]
WIP: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes

**Comment by EvgenyGulyaev** [comment]
Great Job @mcnuttandrew

**Comment by mcnuttandrew** [comment]
Now landed! @types/react-vis available now on your favorite internet
