### ISSUE TITLE
Delete the area left for axes

### ISSUE THREAD

**Issue by blackpatton17** [uber/react-vis#1281]
I made a graph without axes by ignoring to add ```<XAxis />``` and ```<YAxis />```. However, the result still leaves space for axes. Are there any methods to delete the blank areas?

**Comment by achernetsky** [comment]
Hi there,

@blackpatton17, please, try to set `margin` property of  `XYPlot` to `{"left": 0, "right": 0, "top": 0, "bottom": 0}`.
