### ISSUE TITLE
Making axis sticky for large charts

### ISSUE THREAD

**Issue by reinjunon** [uber/react-vis#1285]
Is there a way to make the axis stick while scrolling? Much like freeze panes in excel. I have a scatter plot that contains a wide range of data and after scrolling, i'm not able to see the axis values.

**Comment by mcnuttandrew** [comment]
That's a very interesting idea! I don't think this is a feature that is likely to be addressed from within the library itself, but I think you could easily do it yourself! In particular you could do this by creating two charts: one on top of the other (with the top one having higher z-index as well as position absolute and pointer-events none). Then use normal overflow methods to scroll the bottom one. 

If you make a demo of this you should file a PR to add it to the showcases, that's a wonderful idea.
