### ISSUE TITLE
Ordered list of categories on Y axis

### ISSUE THREAD

**Issue by Brandon-Pampuch** [uber/react-vis#1286]
Is there any way to create an ordered list of ticks on the Y-axis? In most examples in this library and others like it I see numbers on the Y-axis.  Some provide a way to create categories, but since the data is often determining the range of the Y-axis they don't allow you to order these. Thanks in advance!

**Comment by mcnuttandrew** [comment]
Yea totally! Order in ordinal data  is typically informed by the order it is specified. So, first sort your data according to the order you wish it to appear, and then specify yType="ordinal" on XYPlot.
