### ISSUE TITLE
Y axis is clipped when values > 1k

### ISSUE THREAD

**Issue by wolfgangmeyers** [uber/react-vis#1292]
![image](https://user-images.githubusercontent.com/1783800/70766276-21afaf00-1d12-11ea-8fa3-7eaad7f33833.png)

**Comment by bn3t** [comment]
It would be the same for X values when the label is big (like a date/time) and the label orientation is changed.

**Comment by mcnuttandrew** [comment]
to address this you need to specify a margin object to XYPlot, such as {left: 100, top: 10, right: 10, bottom: 20}
