### ISSUE TITLE
Is it possible to use non-numerical values for X-axis?

### ISSUE THREAD

**Issue by minamesephy** [uber/react-vis#1305]
I've had success using React Vis in the past for simple numerical data sets, but now I'm running into an issue. 

I have a few lines series I need to plot along the same X axis values. Each line in the data set I'm trying to plot has the same set of ~90 X axis values but they're not numerical. 

Also, I want to ideally show *every* X value in the plot in the order I specify in the data array. 

Is this possible or does React Vis not handle this situation?

**Comment by mabong1** [comment]
You can set `xType="ordinal"` (You can do the same for Y axis) for non numerical values on the chart plot options. I think it will solve your issue.

```
<XYPlot height={200} width={400} xType="ordinal">
   <YAxis />
   <XAxis />
   <LineSeries
       data={[
         { x: "mon", y: 1 },
         { x: "tue", y: 2 },
         { x: "wed", y: 3 },
         { x: "thu", y: 4 },
         { x: "fri", y: 5 },
         { x: "sat", y: 6 },
         { x: "sun", y: 7 }
       ]}
   />
</XYPlot>
```

Live example : https://codesandbox.io/s/nifty-buck-1j6g9
