### ISSUE TITLE
scale minutes or hours on Y Axis also format Y Axis tick values to render ticks in hours or minutes

### ISSUE THREAD

**Issue by sradhaShet** [uber/react-vis#1311]
data:[{"x":"2020-03-27","y":300.5},{"x":"2020-03-28","y":216.9167},{"x":"2020-03-29","y":10000.6667},{"x":"2020-03-30","y":344.3548},{"x":"2020-03-31","y":385.8814},{"x":"2020-04-01","y":13018.0},{"x":"2020-04-02","y":6991.0303}

**Comment by mcnuttandrew** [comment]
you should be able to do this by setting the yType="time" and then specifying a tickFormat function on the appropriate axis
