### ISSUE TITLE
add documentation for non-zero based area charts

### ISSUE THREAD

**Issue by Firenze11** [uber/react-vis#134]
<img width="191" alt="screen shot 2016-08-31 at 3 27 30 pm" src="https://cloud.githubusercontent.com/assets/4994677/18148682/0a4daaa2-6f90-11e6-9a3f-3be654b3332d.png">

There is a way to specify a "y0" field in data and create non-zreo based area charts like the chart above. There should be documentation regarding this.

**Comment by mcnuttandrew** [comment]
I added an example called AreaChartElevated that I think should handle your request. Let me know if you need anything else
