### ISSUE TITLE
documentation & examples: links to github 404

### ISSUE THREAD

**Issue by MS44118** [uber/react-vis#1340]
found some broken links in http://uber.github.io/react-vis/

for exemple, docs/examples/responsive-vis.md links to 
- Scatterplot source code
- Barchart source code

files are not anymore in this directory:
https://github.com/uber/react-vis/blob/master/

but in this one:
https://github.com/uber/react-vis/blob/master/packages/

**Comment by karansinghgit** [comment]
A lot of the links are broken throughout the documentation.

**Comment by a-peltier** [comment]
Thank you for signaling it, I am going to look into it.

**Comment by Xiot** [comment]
We still need to publish the new documentation.
We'll close this again when we do.

**Comment by chrisirhc** [comment]
Fixed via #1342
