### ISSUE TITLE
The searchable legend doesn't look good on Safari

### ISSUE THREAD

**Issue by bulyonov** [uber/react-vis#141]
- `input type="search"` does not accept styles in the way as they passed in to it in SearchableDiscreteColorLegend;
- `flex: 0` for the input field of the container is not working on Safari as well.

**Comment by mcnuttandrew** [comment]
Chrome:
<img width="364" alt="screen shot 2017-01-20 at 10 16 56 am" src="https://cloud.githubusercontent.com/assets/6854312/22160297/a1b151ae-def9-11e6-939f-1691d37fcc63.png">

Safari:
<img width="363" alt="screen shot 2017-01-20 at 10 16 59 am" src="https://cloud.githubusercontent.com/assets/6854312/22160307/ad5dba74-def9-11e6-9084-82e6e5840d01.png">

**Comment by mcnuttandrew** [comment]
I'm going to mark this as closed, feel free to re-open
