### ISSUE TITLE
YAxis with right orientation misplaced

### ISSUE THREAD

**Issue by waywaaard** [uber/react-vis#143]
I tried changing the orientation of a simple **YAxis** without any other changes, but it is always misplaced. The screens are from the master with `<YAxis orientation="right" />`.

I've not set any margin, so the values are not visible right now.

![image](https://cloud.githubusercontent.com/assets/1634468/18254114/e2aed64c-739a-11e6-8388-e9f0ecc7ab7a.png)

![image](https://cloud.githubusercontent.com/assets/1634468/18254118/eb102b9c-739a-11e6-89b3-582025491595.png)

![image](https://cloud.githubusercontent.com/assets/1634468/18254123/f4408eb4-739a-11e6-8554-9635c421d2a4.png)

**Comment by bulyonov** [comment]
Fixed in 0.6.1. Thank you for reporting the issue!
