### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by jb-reefer** [uber/react-vis#1442]
Looks like the last commit was nearly 2 years ago - maybe there should be an abandoned banner? I see a lot of PRs coming in, don't want people to work on a project that won't be updated.

**Comment by danielvolosov** [comment]
I would like to know as well. I see several recent sources still recommend this library, but based on the commit history I wouldn't mind knowing the status/future plans as well.

**Comment by jo-bert** [comment]
https://github.com/uber/react-vis/issues/1303
It's deprecated.

**Comment by mcnuttandrew** [comment]
That's correct, it is deprecated.
