### ISSUE TITLE
Security Vulnerability in d3-color

### ISSUE THREAD

**Issue by dmckirnan** [uber/react-vis#1455]
High priority vulnerability has been patched in d3-color by upgrading to v3.1. react-vis is behind multiple majors

<img width="901" alt="Screen Shot 2022-09-29 at 10 24 54 AM" src="https://user-images.githubusercontent.com/24486997/193100846-ddece7d2-a1fb-471e-910f-da9181b8cdc7.png">

**Comment by kenns29** [comment]
This should be addressed now by these PRs

https://github.com/uber/react-vis/pull/1462
https://github.com/uber/react-vis/pull/1463
https://github.com/uber/react-vis/pull/1466
