### ISSUE TITLE
Proposal: Archive this repository

### ISSUE THREAD

**Issue by Sequoia** [uber/react-vis#1458]
This repository has not been under active development for some time. I missed the deprecation notice and used it just this week, I wish I'd known this repo is effectively frozen & looked for an alternative. I have added a harder-to-miss deprecation notice.

# Is there any reason not to archive this repository?

This would clearly indicate to users that work on this repo has ended & they can choose to use it or not fully informed of this fact.

**Comment by Sequoia** [comment]
Well then . . . without further ado? Would you like to click the archive button? Thanks!

**Comment by mcnuttandrew** [comment]
i was kind of waiting for some other people to chime in, maybe @chrisirhc ?

**Comment by mcnuttandrew** [comment]
also lol it appears i do not have that control over it any more (member vs collaborator i guess), so i couldn't do it anyway

**Comment by hazeled** [comment]
Seconded, seems like this should be archived

**Comment by Sequoia** [comment]
cc @jonathanbaker7 can you help here?

**Comment by jonathanbaker7** [comment]
Yes, I can.  Please have someone from the @uber/viz team log a ticket in our internal Jira, and we will get this project marked for archive and transfer to the [Uber-Archive](https://github.com/uber-archive) organization.

**Comment by koooge** [comment]
Hi there, is this repo active or not, in fact? If tis repo is archive, I need to consider migrating to another lib.

**Comment by jonathanbaker7** [comment]
Unfortunately, this library is no longer under maintenance.  It will be moved to archive shortly.  I suggest you either fork it, find another library, or feel free to take it over if you want to do maintenance.
