### ISSUE TITLE
Unable To Resolve Module In 1.11.11

### ISSUE THREAD

**Issue by spencercharestpaypal** [uber/react-vis#1470]
It appears `react-vis` can no longer be resolved due to changes made in https://github.com/uber/react-vis/pull/1469. It looks to me like either the build file `dist/dist.min.js` should be renamed to `dist/index.js` or that `package.json` `main` field should be updated to `dist/dist.min.js`. `main` is currently pointing to `dist/index.js` which no longer exist after the changes made in the referenced PR.

**Comment by kenns29** [comment]
I think we should rename main to dist/dist.min.js ... sorry, for some reason my test in external repo

**Comment by kenns29** [comment]
considering this is a faulty publish, lemme revert the latest version (1.11.12) to the 1.11.7. Once we made the fix to the build system, I will bump the version to 1.12.0

**Comment by spencercharestpaypal** [comment]
Thanks so much @kenns29 for the quick response! I'll update to `1.11.12`.

**Comment by watson** [comment]
@kenns29 Hi, the new 1.11.12 version seems to be based off an older version of the code and doesn't for instance include the updates to the `d3-*` packages. Could it be that you accidentally published to npm from your local out-of-date fork of react-vis

**Comment by kenns29** [comment]
> @kenns29 Hi, the new 1.11.12 version seems to be based off an older version of the code and doesn't for instance include the updates to the `d3-*` packages. Could it be that you accidentally published to npm from your local out-of-date fork of `react-vis`?

@watson 1.11.11 has a bug that the main file in package.json doesn't match the correct file in dist, and it breaks the library for browser users. I have to revert the publish (by publishing the content of 1.11.7 to 1.11.12) to prevent breaking the library for people who do auto-update. Need to spend more time to fix the build system and prepare for a minor release instead of patch (the next one should be 1.12.0).

**Comment by rkok** [comment]
Waiting eagerly for the fix, so that we can install the fixes from #1455 to stop `npm audit --production` from complaining.

@kenns29 Thank you for your work keeping the repository alive.

**Comment by ak2hr** [comment]
@kenns29 are the 1.12.0 changes still actively being worked on/planned for release? Nothing immediately pressing, but the d3 vulnerabilities are still a thorn in the side of my team's application. 

Thanks again for your efforts!

**Comment by kenns29** [comment]
It’s still planned, but I’m currently on parental leave, and I will get back to this in around May. I may be able to work on this causally when I can find some spare time. We mainly need to fix the browser bundle with the updates. I expect this to finish by June.

**Comment by ak2hr** [comment]
Sounds good, thanks for the quick reply. And congrats on the kid!
