### ISSUE TITLE
IE10 support

### ISSUE THREAD

**Issue by thienanle** [uber/react-vis#158]
I'm getting this when trying to render a chart in IE10.

> `Object doesn't support property or method 'getParentConfig'`

Works fine in Edge. Am I don't something wrong, or is the library not supported in Internet Explorer 10 or less? And if the latter, are there plans to support it?

**Comment by sapottier** [comment]
Same issue

**Comment by ericsoco** [comment]
I'd say that unless there's a substantial PR to introduce IE10 support, it's pretty unlikely to happen...@mcnuttandrew, any thoughts?

**Comment by mcnuttandrew** [comment]
I would not say that there are currently plans to support IE10, though at some point we certainly could.

**Comment by jckr** [comment]
since the issue was open ie10 market share became virtually inexistant and MS stopped supporting it, so wont fix this one :(

**Comment by aganoza** [comment]
Solution for a create-react-app project is the same as outlined in this issue for victory

https://github.com/FormidableLabs/victory/issues/474#issuecomment-370941314

In webpack.config.dev.js and webpack.config.prod.js

```js
// Process JS with Babel.
{
  test: /\.(js|jsx|mjs)$/,
  include: [
    paths.appSrc,
    path.resolve(paths.appNodeModules, 'react-vis'), //<--this
  ],
  loader: require.resolve('babel-loader'),
  options: {
    plugins: [
      "transform-proto-to-assign", //<--and this
    ],
    // This is a feature of `babel-loader` for webpack (not Babel itself).
    // It enables caching results in ./node_modules/.cache/babel-loader/
    // directory for faster rebuilds.
    cacheDirectory: true,
  },
},
```
