### ISSUE TITLE
Ability to set an active data point

### ISSUE THREAD

**Issue by greatermeans** [uber/react-vis#161]
I have a bar graph that looks like the below image. The current color scheme only allows for one color to be chosen for all the bars; whereas I would like to set a color for an active bar and another color for the rest. Please let me know if this is currently doable!

![image](https://cloud.githubusercontent.com/assets/17058760/20119176/7fcb14e2-a5d5-11e6-98b9-34e3d31b94ec.png)

**Comment by mcnuttandrew** [comment]
Hey @greatermeans I've generally found myself doing this by wrapping the chart in a stateful component that has a notion of "selected bar", using colorType='literal' for the color scale, and then modifying the data

**Comment by greatermeans** [comment]
@mcnuttandrew thanks for the response, do you have an example by any chance?

**Comment by mcnuttandrew** [comment]
I have one in an upcoming PR, something like this https://github.com/uber/react-vis/blob/mouse-out-radial/src/example/radial-chart/custom-radius-radial-chart.js but for barchart?

**Comment by greatermeans** [comment]
@mcnuttandrew awesome dude, was able to replicate!

**Comment by mcnuttandrew** [comment]
Dope! It's generally my opinion that sort of state maintaince is the job of the wrapping application, so i'm gonna close this issue as a wont fix? Feel free to re-open if you disagree

**Comment by greatermeans** [comment]
@mcnuttandrew fine to close. This worked on stackedbarchart and barchart. For some reason, LineMarkSeries doesn't respond to opacity. If you have any suggestions, please let me know!
