### ISSUE TITLE
How to specify scale range for MarkSeries?

### ISSUE THREAD

**Issue by pawel2105** [uber/react-vis#170]
I've got a scatterplot graph that renders something like the following:

<img width="517" alt="screen shot 2016-11-16 at 10 16 08 am" src="https://cloud.githubusercontent.com/assets/811477/20339558/bfbf8f4a-abe5-11e6-8c9f-a5e2532593f2.png">

I'm passing the data attribute using an array like:

```
[{"0":"alg","1":36.4,"2":14.6,"x":36.4,"y":14.6},{"0":"arg","1":21.8,"2":8.1,"x":21.8,"y":8.1},{"0":"ast","1":21.6,"2":8.7,"x":21.6,"y":8.7}, {"etc. etc."}]
```
In the process of trying to make this graph interactive, I'm trying to allow filtering down to a single data point. But the resulting graph looks like:

<img width="384" alt="screen shot 2016-11-16 at 10 16 17 am" src="https://cloud.githubusercontent.com/assets/811477/20339562/c652ed84-abe5-11e6-83a9-7ec27ed7dad4.png">

when the new data attribute is a single data point:

```
[{"0":"can","1":24.8,"2":7.8,"x":24.8,"y":7.8}]
```

How can I specify the scale range so that the scales won't break like this?

**Comment by pawel2105** [comment]
Figured out that I can specify the yDomain and the xDomain:

```
<MarkSeries data={filteredData} yDomain={yDomain} xDomain={xDomain} />
```

**Comment by mcnuttandrew** [comment]
Hey @pawel2105

Can you provide an example fiddle or repo?

**Comment by mcnuttandrew** [comment]
Hey all, @jckr just put up some really wonderful docs scales, (http://uber.github.io/react-vis/#/documentation/overview/scales-and-data) which should hopefully deal with this issue. If not feel free to re-open.

**Comment by ryanmeisters** [comment]
Seems that link is broken. Is there an updated one?
