### ISSUE TITLE
Deprecate Table?

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#177]
There are lots better react tables out there in the ecosystem than the one in our package. It seems like it would probably be pretty reasonable to deprecate the table in favor of those. Would be delighted to hear other opinions

**Comment by Apercu** [comment]
Yes, yes, yes. This component seems pretty out-of-scope of the project to me.

We should start by a simple warning for now, and remove it entirely with the next major release.

I can handle this if you'd like

**Comment by mcnuttandrew** [comment]
Table is now deprecated!
