### ISSUE TITLE
tickSizeOuter and tickSizeInner for XAxis and YAxis are in my opinion inverted

### ISSUE THREAD

**Issue by alee8** [uber/react-vis#179]
First time I used these props, I discovered it applied to the wrong side.  That is, I think tickSizeOuter should be called tickSizeInner and tickSizeInner should be tickSizeOuter.  

The rationale is that the plot area is the inner part of the chart (and hence the XAxis and YAxis).

**Comment by mcnuttandrew** [comment]
This was addressed in #277
