### ISSUE TITLE
Different CSS class names to differentiate XAxis from YAxis so they can be separately styled

### ISSUE THREAD

**Issue by alee8** [uber/react-vis#180]
On an XYPlot, the same class name is used for the XAxis as well as the YAxis. If you want to use CSS to change the styling, you would have to use nth-of-type to have any chance of changing styling on one of the axes.  However, this is brittle and is dependent on which Axis is specified first and second.

**Comment by mcnuttandrew** [comment]
Hey @alee8 I'm gonna close this as the solution is prod. Feel free to reopen if i've missed something

**Comment by alee8** [comment]
Thanks for the heads up and the fix.  Will definitely use it now.

Alison
