### ISSUE TITLE
Export the components that underly the build of Axes, GridLines, Plots, etc.

### ISSUE THREAD

**Issue by alee8** [uber/react-vis#181]
Seems like a great way to build on the existing components for custom purposes.  I certainly have a desire to do so.  For example, custom XYPlot, X/YAxis, Vertical/HorizontalGridLines.

**Comment by mcnuttandrew** [comment]
@alee8 this is done after #183 right?

**Comment by alee8** [comment]
As much as was permitted.  However, I tried to include the files in
CityFlow after pulling the latest and could not import them.
I am unable to work on this until tomorrow the earliest.
Any chance you can try to import these 3 new files and in particular, the
utils functions and see if you see the same issue?

Alison
