### ISSUE TITLE
Support for decorators

### ISSUE THREAD

**Issue by alee8** [uber/react-vis#182]
Tried using the pure-render-decorator in a custom component built from react-vis. Got the following error.  Given progress of React 15, node and browser support, proposing that they be supported.
> Decorators are not officially supported yet in 6.x pending a proposal update.
    However, if you need to use them you can install the legacy decorators transform with:
     npm install babel-plugin-transform-decorators-legacy --save-dev
   and add the following line to your .babelrc file:
     {
        "plugins": ["transform-decorators-legacy"]
     }
  The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.

**Comment by chrisirhc** [comment]
You can fix that error in your project by adding the mentioned plugin into the Babel configuration. react-vis doesn't need any modifications for you to leverage decorators in your custom component.
