### ISSUE TITLE
Animation props requires null to be deactivated rather than false

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#186]
We should be able to pass animation: false (or any falsely value), as a prop to any of the animatable components, rather than being forced to pass null.

**Comment by chrisirhc** [comment]
Isn't this fixed via d9ebdf6c789bf412437387c008ec16b016d824b1 ?

**Comment by mcnuttandrew** [comment]
Looks like i was just behind by a few versions, closing as already fixed
