### ISSUE TITLE
Vertical bar series stack issue

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#187]
<img width="863" alt="screen shot 2016-11-23 at 10 57 25 am" src="https://cloud.githubusercontent.com/assets/6854312/20574891/a7946068-b16b-11e6-93da-fc80675457f4.png">

Vertical bar series appears to not have a notion of how to collapse a stacked series, leading to this, pretty, but confusing graphic

**Comment by chrisirhc** [comment]
Not sure what you mean by "collapse a stacked series". Could you perhaps paste an image of what the expected result is?

**Comment by mcnuttandrew** [comment]
<img width="340" alt="screen shot 2016-11-23 at 2 18 11 pm" src="https://cloud.githubusercontent.com/assets/6854312/20580548/bcd3cb0a-b187-11e6-95ea-8485d8f4580e.png">

**Comment by mcnuttandrew** [comment]
So looking at this some more, this has to do with a kinda weird quirk in the way that react-vis expects data to be formatted. Specifically it requires that each value in dominant direction of the series be present in order to stack. This assumption leads to some wackyness (see above).

**Comment by mcnuttandrew** [comment]
I ended up just adding explanation on how to work around this to the documentation for bar-series, so i guess this is now not technically an issue...
