### ISSUE TITLE
Brush Component

### ISSUE THREAD

**Issue by k010** [uber/react-vis#202]
Did you consider to add a [brush](https://github.com/d3/d3-brush) component to the Charts ?.
I think it's would be useful for filter the data through the selection or made some kind of zoom into.
Thanks

**Comment by akindr** [comment]
I had a similar question in #192 - ended up making a custom component to handle this. Could be worth re-visiting as a PR to make it part of the repo.

**Comment by mcnuttandrew** [comment]
Hey @akindr

I think that this would be a phenomenal example of custom components! Would you mind filing a PR in which you build that as an example?

**Comment by dotfold** [comment]
hey @akindr - I'm looking into this as well, have you got any pointers or some examples of how you achieved this?

Thanks!

**Comment by akindr** [comment]
Ah yeah sorry! I've got a great example, I'll open a PR for it shortly.

**Comment by anselmo** [comment]
Hi @akindr, wonder if you could post the brush example, even if it's still work-in-progress.

**Comment by akindr** [comment]
Ah sorry about that! Here's my branch: https://github.com/akindr/react-vis/tree/zoom-component 

Check it out and run the example to see the behavior. I'll make a PR shortly!

**Comment by anselmo** [comment]
@akindr good stuff, thanks for posting this out.

**Comment by zsherman** [comment]
would also love to see this PR'ed and added to the docs.

**Comment by mcnuttandrew** [comment]
Example if being PR'd in #405

**Comment by mcnuttandrew** [comment]
https://uber.github.io/react-vis/#/examples/charts/zoomable-chart example is live here! We need to production-ize the brush into the main library, but one step at a time

**Comment by YizhiCatherineZhang** [comment]
@mcnuttandrew Hi, when will the source code be available?

**Comment by mcnuttandrew** [comment]
Hey @akindr,

Do you think you could take a crack at productionalizing your highlight component? This would mean adding tests and moving it into the main library. It'd be a great boon for the library if you did!

**Comment by akindr** [comment]
I'd be happy to, might be a bit but it's on my radar

**Comment by acoll** [comment]
Hey @akindr ,

I can take a shot at moving that highlight component and sending a pull request if you haven't gotten to it yet.

**Comment by akindr** [comment]
I'm mid-progress on it now, I have some bandwidth to finish it this week or early next week!

**Comment by acoll** [comment]
Awesome. Sounds good!

**Comment by mcnuttandrew** [comment]
@akindr any word on the brushing component?

**Comment by mcnuttandrew** [comment]
@akindr any word on the brushing component?

**Comment by mcnuttandrew** [comment]
@akindr any word on the brushing component?

**Comment by mcnuttandrew** [comment]
@akindr monthly bump for updates on this work?

**Comment by akindr** [comment]
Yeesh, I am slacking on this. Haven't made progress on it recently, but I will gladly take a stab at opening a PR during the holiday week.

**Comment by mcnuttandrew** [comment]
@akindr bi-yearly bump?

**Comment by george-ionita** [comment]
Highlight.js doesn't seem to compile on React 16.3

`Syntax Error: Unexpected token (5:21)

  3 | 
  4 | export default class Highlight extends AbstractSeries {
> 5 |   static displayName = "HighlightOverlay";
    |                      ^
  6 |   static defaultProps = {
  7 |     allow: "x",
  8 |     color: "rgb(77, 182, 172)",

`
Any ideas on how to make it behave?

**Comment by gajus** [comment]
Assuming this component does exist, then the Storybook is missing an example.

https://uber.github.io/react-vis/website/dist/storybook/index.html?selectedKind=Series%2FAreaSeries%2FBase&selectedStory=Single%20Area%20chart&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
