### ISSUE TITLE
Automatic gh-pages update system

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#208]
We want to guarantee that our gh-pages are always up to date with the latest examples! We should write a simple build script so that contributing to the docs can be easy and quick.

**Comment by mcnuttandrew** [comment]
One suggestion is build a separate package.json for the example so that it can be built directly against it's own requirements, this will also thin out our devDeps & make them less menacing.

**Comment by amilajack** [comment]
So for instance, if example A depends on npm modules b and c, we will need to create a `package.json `, with dependencies `b` and `c`, specifically for example A

**Comment by amilajack** [comment]
Also where is the gh-pages repo?

**Comment by ibgreen** [comment]
@amilajack 

For reference, I have just started to create separate examples (with separate package.json) in [`react-map-gl` dev branch](https://github.com/uber/react-map-gl/tree/dev/examples/main).

> Also where is the gh-pages repo?
`gh-pages` is not a repo, it is a branch in each repo. Anything on those branches is served by github on github pages urls.

**Comment by amilajack** [comment]
@mcnuttandrew should each example in each directory have have its own `index.html`, `package.json`, `webpack.config.js`, etc? Or should we create them for each example directory (for example one `index.html`, `package.json` etc for all legends or one for each legend example)?

**Comment by mcnuttandrew** [comment]
Well if we are following deck.gl's lead, then we would have a folder structure like

// examples
// // example 1
// // // package.json
// // // index.html
// // // ..etc
// // example 2
// // // package.json
// // // index.html
// // // ..etc

which would allow people to clone those examples exactly in order to get started. (That said, the barrier to entry is substantially lower for react-vis than deck.gl) 

I think we should shoot for a structure that will allow us to build a central documentation page that has each of these examples embedded within it, so it seems like the above structure would work well? I think in an ideal world out compile system would merge these all together and shove them over to the gh-pages.

**Comment by amilajack** [comment]
@mcnuttandrew thanks for the clarification. I've started the migration of the examples in my local branch. I also have another question. Should the examples use the published npm version of the package or the compiled source of the git repo itself (the files in `dist`)? `react-map-gl`'s example rely on the npm package. I think we should take the npm package approach because its safer in terms of breaking changes and its easier to replicate. Is this recommended?

**Comment by amilajack** [comment]
[Here's](https://github.com/amilajack/react-vis/tree/refactor-doc-examples/src/example/legends) an initial implementation of the legends examples

<img width="1264" alt="screen shot 2017-01-11 at 9 46 57 pm" src="https://cloud.githubusercontent.com/assets/6374832/21878573/fd407896-d847-11e6-8c81-6b105fcb5585.png">

```bash
git clone https://github.com/amilajack/react-vis
cd react-vis/src/example/legends
git checkout refactor-doc-examples
yarn
npm start
```

**Comment by amilajack** [comment]
Finished migrating all the examples locally 🎉 😊 Should we keep the `src/example/main.js` file or remove it?

**Comment by mcnuttandrew** [comment]
> Finished migrating all the examples locally 🎉 😊 Should we keep the src/example/main.js file or remove it?

I think maybe keeping it, and using it as a index of examples is maybe not a bad idea? Looking forward to reading your PR!

> Also on a side note, react-map-gl's examples are not react 0.14.0 compatible but it has peerDependencies declare it as supporting 0.14.0.

You should file a bug on that repo?

**Comment by amilajack** [comment]
Sure thing. Just filed it. Also, [here's the commit](https://github.com/amilajack/react-vis/commit/15f31e61e6570bc560c3cc8a2ab64cc36ad3d088) that migrates all the examples (except legends, which was the previous commit) that can be build directly from the example's directory. It's still a work in progress.
