### ISSUE TITLE
Find more interesting examples

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#210]
The current examples uses pretty limited and very fake data, this make's it hard to to understand how a chart would work in context. It would be a great boon to our documentation to have better/more interesting examples

**Comment by mcnuttandrew** [comment]
One rich data set at hand is our contribution data. It would be kinda interesting to rebuild the gh-contributor page in react-vis

**Comment by akindr** [comment]
I've got some pretty interesting data that could work well for examples. I have these CSV datalogs from my car that capture a row of data per unit time, such as speed, RPM, boost pressure, air temperature, etc... You could plot things like speed vs time, speed vs RPM, etc... I've attached a file in case you want to check it out (I have it as CSV as well but github won't upload it).
[datalog.xlsx](https://github.com/uber/react-vis/files/699096/datalog.xlsx)

**Comment by mcnuttandrew** [comment]
![screen shot 2017-01-11 at 9 55 55 am](https://cloud.githubusercontent.com/assets/6854312/21860140/2c27301e-d7e4-11e6-889f-3c997b4a0006.png)
that some pretty cool data! I think we should maybe build an examples folder so that we can iteratively add cool things?

**Comment by akindr** [comment]
Agreed, I like that idea.

**Comment by john-ziegler** [comment]
We're using react-vis for [visualizing genetic profiles after engraftments.](https://mskcc-clinbx.github.io/react/front-end/flux/2017/01/23/plotting-engraftment-results-in-react.html) It could be a real-world example for the VerticalRectSeries.

**Comment by mcnuttandrew** [comment]
As I'm sure you've seen we've developed location for hosting examples (http://uber.github.io/react-vis/#/examples/charts/showcase). If you have any interest I highly encourage you to submit an example! The process is real easy, just clone one of the examples in the examples folder, and add an appropriate json object in constants/pages.js

**Comment by mcnuttandrew** [comment]
I'm marking this as closed as we have a pretty cool collection of examples now
