### ISSUE TITLE
Area Series opacity regards 0 as falsy 

### ISSUE THREAD

**Issue by roderickhsiao** [uber/react-vis#215]
https://github.com/uber/react-vis/blob/master/src/lib/plot/series/area-series.js#L68

```js    
const opacity = this._getAttributeValue('opacity') || DEFAULT_OPACITY;
```

We are having use case that we are conditionally passing opacity 0 to hide the chart, the above code will regard zero as falsy and always fallback to `DEFAULT_OPACITY`;

Probably specifically check for Nil value?

Thanks

**Comment by mcnuttandrew** [comment]
Good catch! Ill cut a new version tomorrow morning

**Comment by mcnuttandrew** [comment]
Alright there's a new version up 0.8.1 which fixes this. Let me know if I can do anything else!

**Comment by roderickhsiao** [comment]
Oh so fast! Just about to send a PR and you guys fix it :) thanks a lot
