### ISSUE TITLE
RFC: Extend eslint-config-airbnb

### ISSUE THREAD

**Issue by amilajack** [uber/react-vis#219]
`eslint-config-airbnb` is a very popular choice of eslint config in the js community. What are thoughts on migrating to it? The `.eslintrc` of this project seems to be a bit bloated at the moment.

**Comment by ibgreen** [comment]
> ? The .eslintrc of this project seems to be a bit bloated at the moment.

@amilajack  Agreed! We have uber configs that are very similar to airbnbs, that match all other code we work on internally and externally. We should be using those unless we have strong reasons not to. See [react-map-gl](https://github.com/uber/react-map-gl/blob/dev/.eslintrc)

**Comment by amilajack** [comment]
@ibgreen made a PR based on the `react-map-gl` `eslintrc` config. Would be great if you could review it:

https://github.com/uber/react-vis/pull/220

Most of the changes were made with eslint's auto fix feature, which is pretty conservative and should make breaking changes. How do you recommend I test the changes manually?

**Comment by chrisirhc** [comment]
@amilajack replied in #220. You can test the changes manually by running `npm run watch` and seeing checking visually through the examples.

**Comment by amilajack** [comment]
Closing, as the PR for this was made: https://github.com/uber/react-vis/pull/220
