### ISSUE TITLE
Undefined append on classname for Axis

### ISSUE THREAD

**Issue by roderickhsiao** [uber/react-vis#221]
very minor but if user doesn't pass in `className` for Axis
https://github.com/uber/react-vis/blob/master/src/lib/plot/axis/axis.js#L162

`const {className} = this.props` will become `undefined`

we can either add a defaultProps (empty className) or `const {className = ''} = this.props` I guess.

**Comment by mcnuttandrew** [comment]
Another good catch! Do you wanna shoot off a PR for this one?

**Comment by roderickhsiao** [comment]
Sure thing, this is an easy one :)
