### ISSUE TITLE
RFC: Visual Regression Testing

### ISSUE THREAD

**Issue by amilajack** [uber/react-vis#224]
A pretty powerful way of testing with confidence is visual regression testing. What are thoughts on this? [uber/image-diff](https://github.com/uber/image-diff) can be used to diff screenshots of images.

**Comment by mcnuttandrew** [comment]
I think you are right that visual regression testing can be a really powerful way to guarantee repeatable graphics. That said, I think we should work on making the rest of the code better tested before we invest in something heavy like screenshot diffing?

**Comment by mcnuttandrew** [comment]
Worth noting: image-diff seems like it is either deprecated or about to be deprecated.

**Comment by mcnuttandrew** [comment]
I've really enjoyed using phantom-css in the past, it works well and is pretty easy to reason about. I'm open to other suggestions if there are more modern alternatives?

**Comment by amilajack** [comment]
phantom-css seems to be pretty well maintained so i think its a good alternative

**Comment by jckr** [comment]
We're welcoming PR on this but it's not really blocking so will close for now.

**Comment by ibgreen** [comment]
Just FYI - The upcoming deck.gl 5.2 release includes a [visual regression testing framework](https://github.com/uber/deck.gl/tree/master/docs/api-reference/test-utils) for WebGL layers, using puppeteer and chrome dev tools. Pretty sure many parts could be reused if there was interest.

**Comment by ibgreen** [comment]
The basic BrowserDrivers parts are available in [probe.gl](https://uber-web.github.io/probe.gl/#/documentation/api-reference-testing/browserdriver). 

Current plan is to expose image diffing tools as part of a collection of GPGPU tools in luma.gl, but we could discuss other options.

The test scene renderer is harder to share as it would need to be adapted for react-vis, but deck.gl's version could be used as a base.

**Comment by ericsoco** [comment]
I know @btford was exploring a similar testing strategy for another
application a couple months back, we should sync our efforts.

**Comment by ibgreen** [comment]
Sounds good. Just in case, I added the image diffing tools as [experimental exports](https://github.com/uber-web/probe.gl/tree/master/src/test-utils/image-utils) in probe.gl. 

I think a skeleton of the code that asynchronously drives multiple react renders and wait for comparisons could also be made reusable. Doing that could save a lot of time for others, but preparing it would take a little more time than I have right now, so let's sync first.
