### ISSUE TITLE
Margin on rendered SVG

### ISSUE THREAD

**Issue by dcousens** [uber/react-vis#226]
In the below image, screen-capped from the examples page,  there is a noticeable bottom-right margin as part of the rendered SVG.
I've noticed this even on with my own usage of the library.

Am I missing a CSS trick to center/crop this?

![svg](https://cloud.githubusercontent.com/assets/413395/21851356/da72eab8-d862-11e6-972e-9bf2ae89ace0.png)
(Source: https://uber.github.io/react-vis/)

**Comment by mcnuttandrew** [comment]
No, your weren't missing anything! It was a problem on our end, thanks for catching that
