### ISSUE TITLE
Adjust series distance based on tickFormat?

### ISSUE THREAD

**Issue by roderickhsiao** [uber/react-vis#228]
Not sure if I implement correctly, I am building a time-series chart with custom `tickFormat` function.

However seems the tick distance on xAsis do adjusted but not the line/mark series, so the tick and mark is off.

[Example](https://branchmetrics.github.io/dashboard/#/components/lineChart
) on the **second** chart.

<img width="980" alt="screen shot 2017-01-11 at 1 11 56 pm" src="https://cloud.githubusercontent.com/assets/3906130/21866596/b2b27920-d7ff-11e6-9a7c-ecea1e0c41ab.png">

Similar to https://github.com/uber/react-vis/blob/master/src/example/plot/time-chart.js just 
I am passing `tickFormat: (v) => moment(v).format('MM/DD')` to `xAxis` component.

**Comment by mcnuttandrew** [comment]
The way that the ticks laid out is not connected to the number of points. By default the axis tries to layout an even ish distribution of labels. If you wanna make them match you'll need to supply the exact points along the line as the xaxis prop tickValues:

``
        <XAxis
          title="X"
          labelFormat={v => `Value is ${v}`}
          labelValues={[2]}
          tickValues={[1, 1.5, 2, 3]}/>
``

**Comment by roderickhsiao** [comment]
I see, thanks for your prompt reply!

**Comment by roderickhsiao** [comment]
@mcnuttandrew 

Just go deeper of the issue, the time format doesnt matter, the problem is that using `scale.tick(count)` will cause uneven spacing if the tick is by day (or other time unit).

I am using `Date.now();` as the first tick in the time data, so that the first tick distance is less then one day.

The approach of passing `tickValues` works but then we need to control responsive by ourself, will be kind of hairy as we need to read the width from the flexible wrapper, and re-render the whole component in order to adjust `tickValues` counts.

Thanks!
