### ISSUE TITLE
Rounding error on x-axis values when they are small decimals

### ISSUE THREAD

**Issue by timfpark** [uber/react-vis#230]
Using an XYPlot with formatted tick values (ala tickFormat={v => `${v} mi.`}) and a small range of values (for example, the below where the mileage runs between 0 and 3.1 miles yielding decimal increments of 0.2 miles on the x axis causes occasionally a bug where these tick values are not rounded correctly and instead contain a very large amount of precision that wrecks the visual display.

<img width="599" alt="screen shot 2017-01-12 at 4 48 59 pm" src="https://cloud.githubusercontent.com/assets/712001/21914287/187b75bc-d8e7-11e6-8875-3523db9fb043.png">

I've dug into the code but can't seem to figure out where the rounding needs to be corrected - i am happy to investigate if someone can give me a pointer on where to look.

Thanks for a great library overall!

**Comment by mcnuttandrew** [comment]
Hey @timfpark 

This is an interesting bug! Ill investigate. In the mean time you could inject the degree of precision you are looking for by modifying your custom formatter a little bit more. Specifically, if you import d3-format, and then build a formtter like

`var f = d3.format(".1f");`

which you could then use in conjunction with your tickFormat prop:

`tickFormat={v => `${f(v)} mi.`}

that would probably do what you are looking for

**Comment by Apercu** [comment]
I think anton was working on this particular issue

**Comment by mcnuttandrew** [comment]
It's been a long time since we've had any word on this, I'm going to close and if anyone is interested in reopening it (ie if it comes up again) we can see about it then
