### ISSUE TITLE
demo plot on your github page has a broken plot

### ISSUE THREAD

**Issue by Frazer** [uber/react-vis#236]
on http://uber.github.io/react-vis/  there is a plot that displays really badly:

![screen shot 2017-01-14 at 10 16 42](https://cloud.githubusercontent.com/assets/374464/21954082/f6e5f014-da47-11e6-80d3-cbba04ec5ffa.png)

it appears like that for me on safari and firefox.  

Also the x-axis is displaying decimals (including negative decimals) whenever there are less than 15 columns, which isn't sensible for a bar chart.

![screen shot 2017-01-14 at 11 00 07](https://cloud.githubusercontent.com/assets/374464/21954111/c357bf60-da48-11e6-92c7-4289e1edc84c.png)

**Comment by mcnuttandrew** [comment]
Alt: maybe I'm misunderstanding the basis of your comment, can you provide a gif?

**Comment by Apercu** [comment]
You can see on his first screenshot that the y-axis is entirely hidden, you can see the top of a value just at the bottom of the word plot. To me it's more an issue about data (and the random generation process) rather than the library itself.

**Comment by Frazer** [comment]
I guess the problem with the decimals on the x-axis is that you will have X
discrete columns, but 2X or 3X ticks on the x-axis.

**Comment by amilajack** [comment]
I was thinking of limiting the bar count to >= 2. Having a single bar somewhat defeats the purpose of having a bar chart, which really only makes sense when comparing two or more things.

**Comment by mcnuttandrew** [comment]
@amilajack that's reasonable, i'd also endorse using the rect-series rather than the bar-series, as this demo is using a continuous variable for the axis, and is thus a histogram (and not a bar chart)

**Comment by mcnuttandrew** [comment]
Hey @Frazer,

The demo page has been pretty radically updated! I think the issue should now be resolved. I'm marking this as resolved, but if you see the demo acting in a way that doesn't make sense again, feel free to re-open
