### ISSUE TITLE
RFC: Minify `main.css`

### ISSUE THREAD

**Issue by amilajack** [uber/react-vis#237]
At the moment, `main.css` isnt minified. What are thoughts on adding a minification build step to it? Also it would make more sense for `main.css` to be inside of `./dist` instead of root

**Comment by Apercu** [comment]
Related https://github.com/uber/react-vis/pull/232/commits/079cfab230ba160f42a4188b598420307fbfe436. As of now, it's not possible to move it to `dist` as explained in #232. Minification could be a thing though.
