### ISSUE TITLE
RFC: Allow access to sass files

### ISSUE THREAD

**Issue by amilajack** [uber/react-vis#238]
Currently, only the compiled `main.css`, which contains all the styles for all the examples, is exposed. Exposing the sass files of each visualization type (plot, legends, etc) can allow users to choose only the styles they need. A build step could be added to do this. Thoughts?

**Comment by Apercu** [comment]
The `main` css file does not contain the example styles, it only consist of base component ones. The sass files of each components are already exposed and can be imported individually, though this is undocumented.

    @import "react-vis/dist/styles/legends";
