### ISSUE TITLE
Is there some graph map with edges?

### ISSUE THREAD

**Issue by ardok** [uber/react-vis#25]
Let's say we start with one node, attach a click listener in which it will fetch some data, then we will expand that "graph map" with more edges connected with these other nodes that we get from our new data.

**Comment by bulyonov** [comment]
@ardok , we don't have any graph support in the library now. The next release will be definitely extending the existing functionality for charts. Different types of graphs are in our roadmap, but we don't have any estimate for that yet.

**Comment by williaster** [comment]
@bulyonov is there a published roadmap anywhere?

**Comment by mcnuttandrew** [comment]
@ardok you might be interested in this library https://github.com/uber/react-vis-force

**Comment by mcnuttandrew** [comment]
Also of interest, https://github.com/uber/react-digraph

**Comment by jckr** [comment]
no plan to build that in react-vis for now.
