### ISSUE TITLE
`npm start` fails

### ISSUE THREAD

**Issue by amilajack** [uber/react-vis#254]
```
ERROR in ./~/css-loader!./~/sass-loader!./index.scss
Module build failed:
@import "../main";
^
      File to import not found or unreadable: ../main.
Parent style sheet: stdin
```
This is failing because of an incorrect path. The correct path is `@import "../src/main.scss";`, not `@import "../main.scss";`I can submit a PR to fix this.

**Comment by amilajack** [comment]
**Should also note that the showcase styles are off for the custom radial radius chart

<img width="513" alt="screen shot 2017-01-24 at 1 03 08 pm" src="https://cloud.githubusercontent.com/assets/6374832/22266616/8d513bb8-e235-11e6-86de-ee560642cf08.png">

**Comment by Apercu** [comment]
You didn't build.

**Comment by amilajack** [comment]
We should also address the incorrectly positioned radial chart

**Comment by Apercu** [comment]
Don't think it's really related, we should open another issue

**Comment by amilajack** [comment]
To prevent issues like this in the future, should we add the build step to the npm start script?

**Comment by Apercu** [comment]
Hum I don't think so, the change of import you did in the stylelint pr should be good
