### ISSUE TITLE
Custom radius chart broken styles

### ISSUE THREAD

**Issue by amilajack** [uber/react-vis#256]
Showcase styles are off for the custom radial radius chart

<img width="513" alt="screen shot 2017-01-24 at 1 03 08 pm" src="https://cloud.githubusercontent.com/assets/6374832/22266616/8d513bb8-e235-11e6-86de-ee560642cf08.png">

**Comment by mcnuttandrew** [comment]
<img width="416" alt="screen shot 2017-01-26 at 9 41 51 pm" src="https://cloud.githubusercontent.com/assets/6854312/22361918/5868b6d0-e413-11e6-985a-79a1960c9ab6.png">

this is what i see when i run it locally?

**Comment by mcnuttandrew** [comment]
<img width="779" alt="screen shot 2017-01-26 at 10 01 39 pm" src="https://cloud.githubusercontent.com/assets/6854312/22361922/6209af14-e413-11e6-80d9-1a9f261f9067.png">

this is what i see when i run it locally

**Comment by amilajack** [comment]
It seems similar to what I see. Is this intentional or is this a bug?

**Comment by mcnuttandrew** [comment]
What do you see that you believe to be in error? I was assuming that you were referring to right side of the upper right label be clipped?

**Comment by amilajack** [comment]
Actually when looking back at the examples, the issue seems to be fixed. I thought it was a css positioning bug. It was probably because I was viewing it with canary

**Comment by hanjunx** [comment]
cool
