### ISSUE TITLE
Make voronoi a generic component

### ISSUE THREAD

**Issue by akre54** [uber/react-vis#264]
Hi y'all. I ran into a case today where I realized it'd be nice to have a generic voronoi component to overlay on top of a line chart with several overlapping lines. I see there already exists a one-off voronoi component in #243 that @Apercu added. Maybe it could be made available as a generic component?

I can take a crack at this if I get some time.

**Comment by mcnuttandrew** [comment]
That sounds like a great idea, I've been thinking we should develop a notion of of an overlays folder that in the future could support brushes and stuff. It would be great if you take a shot a genericizing the voronoi component.

**Comment by mcnuttandrew** [comment]
I am going to close this issue as the above PR addresses it.
