### ISSUE TITLE
tickTotal is ignored in source code

### ISSUE THREAD

**Issue by greatermeans** [uber/react-vis#268]
Looks like by default tickTotal is determined by size and all arguments being passed in are ignored.

**Comment by mcnuttandrew** [comment]
![screen shot 2017-02-16 at 11 40 56 am](https://cloud.githubusercontent.com/assets/6854312/23037882/ddb37b98-f43c-11e6-9642-d6c042c902de.png)
![screen shot 2017-02-16 at 11 41 08 am](https://cloud.githubusercontent.com/assets/6854312/23037884/ddbac5b0-f43c-11e6-999f-4dec78cace86.png)
![screen shot 2017-02-16 at 11 41 19 am](https://cloud.githubusercontent.com/assets/6854312/23037883/ddb71aaa-f43c-11e6-927d-d2127040b293.png)

Hey @greatermeans 

It looks like tickTotal is operating fine to me. Just like in d3 ticktotal is less a hard line specific number and more of a recommendation. If you need exact control over your ticks, I suggest passing in custom values for tickValues, and formatting however you need them via tickFormat.

**Comment by mcnuttandrew** [comment]
I'm gonna mark this as resolved, as this recomendation-rather-than-exatct-value is a feature not a bug. If i've missed something, feel free to re-open

**Comment by brandonmp** [comment]
> I suggest passing in custom values for tickValues

@mcnuttandrew  trying this now, but the high-bound seems to cut off at the max value.

is there another way to ensure the axis displays the entirety of a certain range irrespective of the size of the data points?


```
<XAxis
    title={'Portion of group (%)'}
    style={{
        ticks: { fill: 'white' },
        line: { display: 'none' }
    }}
    tickTotal={12}
    tickFormat={v =>
        v === 5 ? '≤ 5' : v}
    tickValues={[
        5,
        10,
        15,
        20,
        25,
        30,
        35,
        40,
        45,
        50,
        55,
        60
    ]}
/>
```

![image](https://user-images.githubusercontent.com/14139991/36854213-6f5206c0-1d3e-11e8-9a5a-096260006e27.png)

**Comment by Ventis** [comment]
I would like to know this as well. I have 8 values in my tickValues array on the XAxis but it only shows 7 (if I set tickTotal to 8) and much more if I don't set tickTotal at all.
