### ISSUE TITLE
Add docs (perhaps a "cookbook" recipe) about XYPlot order

### ISSUE THREAD

**Issue by WaldoJeffers** [uber/react-vis#272]
Hello,

Thanks for this great library!
Axis seem to be drawn in the background (ie. at a lower z-index than other elements), which means that when an axis' position is adjusted, the axis becomes invisible (especially in an area chart). Is this a bug ? Or is there an option to adjust an axis' z-index ?
![areachart](https://cloud.githubusercontent.com/assets/7644970/23063295/0b0b9dd2-f50a-11e6-8217-4ea2b75fed86.PNG)

I've adjusted the area's opacity on the screenshot above to provide a better understanding of the issue.

**Comment by mcnuttandrew** [comment]
Hey Waldo,

You can change the order that elements are placed onto the page by changing the order of the elements in your code, eg if you had a situation like

```
<XYPlot>
<XAxis />
<YAxis />
<RectSeries />
</XYPlot>
```

And you wanted to make sure your axes appeared on top of your bars, you could just rotate the order of the elements

```
<XYPlot>
<RectSeries />
<XAxis />
<YAxis />
</XYPlot>
```

Let me know if that works for you!

**Comment by WaldoJeffers** [comment]
Now, that's clever! Thank you for your quick reply, it works like a charm. Maybe it could be useful for others if this feature was mentioned somewhere in the docs ? (or maybe that was obvious)

**Comment by mcnuttandrew** [comment]
As I'm sure you've seen our docs are not a thing of great beauty, but we are intending to put some leg work in on them soon it soon, I'm going to re-open and tag this as a documentation task so that we have some tracking on it.

**Comment by mcnuttandrew** [comment]
Hey @WaldoJeffers I added a section to xy-plot docs about order, so I am marking this as resolved. If you still think the documentation is unclear, please feel free to re-open so we can work on improving it
