### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by Marnnn** [uber/react-vis#278]
Great library! Can this work with React Native? I'm pretty novice and had a quick attempt but getting a lot of red boxes. If not is there potential for creating a version that works with it?

**Comment by mcnuttandrew** [comment]
Hey @Marnnn ,

My understanding of react-native is that it requires packages to not use css. We've been tossing around a notion of introducing a root component called ReactVis that would allow users to declare whether they wanted styling to be handled inline (as react-native requires) or in stylesheets. That said there might be deeper issues preventing us from adding react-native support. I'd be open to hear thoughts from anyone who knows more about that topic than I do!

**Comment by rickcodetalk** [comment]
Hi, Is there any update on this topic? I'm looking into charting library that support react-native too. At the moment, the victory and victory-native seem work well on react and react-native, but I do like the simplicity of the react-vis. Thanks!

**Comment by mcnuttandrew** [comment]
There hasn't been any progress on this topic unfortunately, it still very much a nice to have, and not a critical path feature

**Comment by ericsoco** [comment]
How would this work with d3?

**Comment by ericsoco** [comment]
Sorry, hit send too soon -- have we abstracted d3 completely away from the
DOM? In that case, theoretically doable...just wondering how feasible in
practice.

**Comment by mcnuttandrew** [comment]
React-vis uses only react for it's DOM manipulation, so it is completely do-able! That said, there are just some tough questions to answer. 

- Should this be part of react-vis, or should there be a separate repo (react-vis-native)? If the former, how do we keep the package size down? if the latter we probably need to abstract a number of things within react-vis to make the change over more feasible.

- Should we develop each one of the marks as their own view components or use a svg package such as https://github.com/react-native-community/react-native-svg (which is what victory charts does)

**Comment by jckr** [comment]
we can consider doing a react-vis-native repo but that is not in the roadmap for now.

**Comment by eduardopelitti** [comment]
Hi, is this still off the roadmap? I'd be happy to contribute to this if it's activated.

**Comment by scinfu** [comment]
+1

**Comment by asherccohen** [comment]
Any plans for the future of native charts?

**Comment by abdemirza** [comment]
Any updates on React Native ?
