### ISSUE TITLE
Upgrade to d3 4.0

### ISSUE THREAD

**Issue by bulyonov** [uber/react-vis#29]
Upgrade to d3 4.0 will help us to make our codebase smaller and more extensible.

**Comment by samhogg** [comment]
This is of interest to me as we're using the d3 4 modules elsewhere so importing the d3@3 kitchen sink isn't so great for the size our web bundle.

From my grokking around the codebase the other day, the following methods are being used...

```
d3.time
d3.scale
d3.svg
d3.selection
d3.mouse
d3.event
d3.select
d3.event
d3.layout
d3.extent
d3.hsl
d3.set
d3.transition
```

Happy to pitch in on this if you want some help - shouldn't have the issue that there was in uber/react-map-gl#57 as there's no use of `d3.geo` which seems to be the big thing missing from the d3@4 modules at the moment.
