### ISSUE TITLE
Clustered and stacked bar charts

### ISSUE THREAD

**Issue by samhogg** [uber/react-vis#292]
It seems like clustering versus stacking is an either or operation at the moment, unless I'm missing something. Is there any way to do [something like this](http://excelhelphq.com/wp-content/uploads/2012/02/Example-of-Cluster-Stacked-Chart.png) with `react-vis`?

**Comment by samhogg** [comment]
Answering my own question - it seems that @chrisirhc [pointed this out](https://github.com/uber/react-vis/pull/37#r57063711) in #37.

Any chance a PR would be accepted to add this functionality in?

**Comment by mcnuttandrew** [comment]
a pr for this would definitely be welcome! i worry a that this would be a breaking change, so the api of the modification would have to be pretty careful. excited to see what you come up with
