### ISSUE TITLE
Treemap Click/Selection Event

### ISSUE THREAD

**Issue by nikolayg** [uber/react-vis#294]

**Comment by mcnuttandrew** [comment]
Hey @nikolayg 

You can certainly affix listeners to nodes in the treemap! Treemap accepts props called onLeafClick/onLeafMouseOver/onLeafMouseOut. Check out the docs on tree map https://github.com/uber/react-vis/blob/master/docs/markdown/treemap.md or one of the treemap examples (https://github.com/uber/react-vis/blob/master/showcase/treemap/dynamic-treemap.js) for more information on how to do this. 

Marking as resolved, but feel free to re-open if you have more questions.
