### ISSUE TITLE
Box Plot

### ISSUE THREAD

**Issue by nikolay-g** [uber/react-vis#296]
Can React-Vis be used for a [Boxplot](https://en.wikipedia.org/wiki/Box_plot)? I need to plot several boxplots on the same scale so they can be compared.

**Comment by mcnuttandrew** [comment]
It sure can! It's not baked in as part of the main library, but can be built super easily. Checkout this example (https://github.com/uber/react-vis/tree/master/examples/candlestick) for one technique on how to do it.

**Comment by nikolay-g** [comment]
Thanks!

**Comment by mcnuttandrew** [comment]
Marking as resolved, feel free to re-open if you have additional questions
