### ISSUE TITLE
Radar Chart?

### ISSUE THREAD

**Issue by nikolay-g** [uber/react-vis#299]
I couldn't see any example of a [Radar Chart](https://en.wikipedia.org/wiki/Radar_chart). Does react-vis support it?

**Comment by Apercu** [comment]
Not at the time, but a PR would be appreciated! 😃

**Comment by mcnuttandrew** [comment]
I've been thinking Radar charts would be part of a larger story around r-theta plots (#209), which would enable us to do a whole variety of additional polar coordinate based charts!

**Comment by mcnuttandrew** [comment]
At last radar charts are part of the library! Woot! They'll be up int he next release
