### ISSUE TITLE
Provide an example with Time as the Y-Axis. 

### ISSUE THREAD

**Issue by sheki** [uber/react-vis#30]
Right now I try to make a graph with X part of the dataset to be js Date objects. The graph renders horribly in that case. An example for xScale='time' would be very useful.

https://i.imgur.com/uvJS4tV.png

**Comment by samhogg** [comment]
@sheki try passing your dates as raw number values rather than JS date objects - seems to work with `xScale=time

**Comment by bulyonov** [comment]
@sheki , @samhogg , yes, this is correct. You should pass `xType="time"` there.

@sheki , Your issue is unrelated to the time scale. I have a strong feeling that you have some CSS missing (probably, not included in your css file).

**Comment by bulyonov** [comment]
@sheki, I've just made the requested change in README.md.
Here's the link to the commit — https://github.com/uber-common/react-vis/commit/86f62fb4bba3a36b7f209562e8c5f3a4e83bd55d

**Comment by bulyonov** [comment]
Closing this issue since it is resolved in examples and in README.md
