### ISSUE TITLE
Pass a style object to any react-vis component to apply styles directly

### ISSUE THREAD

**Issue by jckr** [uber/react-vis#307]
I'd like to be able to pass a style property anywhere to style my charts programatically, without having to work around the react-vis stylesheet.

**Comment by mcnuttandrew** [comment]
This sounds like a reasonable proposal. There are of course a wealth of different systems for adding styling to react-components via javascript. Does anyone have strong opinions about them?

**Comment by mcnuttandrew** [comment]
Now that @jckr's style PR is merged i think this can closed? Marking as resolved for now, feel free to re-open

**Comment by ericsoco** [comment]
@mcnuttandrew link to that PR or documentation of the feature? We'll need that for an upcoming feature...thanks!

**Comment by mcnuttandrew** [comment]
@ericsoco I'm not sure where the PR has gotten off to, but here's the commit https://github.com/uber/react-vis/commit/6752d8ad8e3267564e4056dc0ab9f93bef4530a7
