### ISSUE TITLE
Pass in a custom `strokeDasharray` property

### ISSUE THREAD

**Issue by jonsadka** [uber/react-vis#319]
Currently only a line style of `solid` and line style of `6, 2` are supported. We should expand to allow for a user specified `stroke-dasharray`.

**Comment by mcnuttandrew** [comment]
I think this is super reasonable, and would welcome a PR for it

**Comment by jonsadka** [comment]
@mcnuttandrew see PR for enhancement

**Comment by jonsadka** [comment]
Released in [v1.1.1](https://github.com/uber/react-vis/releases/tag/v1.1.1)
