### ISSUE TITLE
MarkSeries strokeWidth prop

### ISSUE THREAD

**Issue by LoicUV** [uber/react-vis#331]
I'd like to be able to change the `strokeWidth` of the dots in a `<MarkSeries />` just like you can for a `<LineSeries />`.  Could it be added ?

![capture d ecran 2017-03-31 a 11 11 48](https://cloud.githubusercontent.com/assets/592542/24544309/124cfd38-1603-11e7-809e-0bda10e37b4f.png)

Thanks !

**Comment by mcnuttandrew** [comment]
I just addressed this ticket in #333, and should have a version up of react-vis sometime in the next few hours. In the future if you don't want to wait for us to version packages and stuff, many properties (including stroke-width) can be manipulated via css!
