### ISSUE TITLE
Add sankey diagrams to the library

### ISSUE THREAD

**Issue by bulyonov** [uber/react-vis#34]
Currently we have a big need to show the flow of step by step changes. Sankey Diagram is a good way to visualize it.

I think, we should use `d3-sankey` for this purpose, but before that we should upgrade to d3@4.x (see #29  for detail).

**Comment by wzup** [comment]
> we have a big need to show the flow of step by step changes

It sounds like to display `dropoffs` with Sankey.
Could you please provide a link to a live example?
