### ISSUE TITLE
Enable reordering of cells in bar chart

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#359]
It would be good if we react-vis could dynamically re-order elements that it has stacked. This would enable "smart" bar charts that order their cells by value like so

![unnamed](https://cloud.githubusercontent.com/assets/6854312/24810293/c4402740-1b76-11e7-8b28-0266b7f1a16a.png)

**Comment by jckr** [comment]
you could do it through rect series, by computing the position of each mark through the data. i'm going to close for now
