### ISSUE TITLE
Automatic Documentation Generation

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#361]
We have lots of props in react-vis, and writing out each one of them leads to a lot of copy-pasta. In order to make sure our documentation is up to date we should make our documentation update it self. 

I propose that there should be some sort of system that looks at a component, reads it's props, looks for annotations and decorates them appropriately.

**Comment by mcnuttandrew** [comment]
Thinking of using https://github.com/reactjs/react-docgen

**Comment by mcnuttandrew** [comment]
I am not amazingly satisfied with my research on this topic, the above react-docgen would require us to change all of the components pretty radically to make it work. (In addition it's pretty clumsy from what I have seen, but that may just be bad luck or inexperience)

Even more: I hear @jckr is hard at work on a big docs PR

Given all this, I am going to close this ticket, but is something we could consider in the future if we ever feel the library needs to change a lot.

**Comment by ericsoco** [comment]
@jckr have you been talking with @btford / @ibgreen about this? Similar rumblings echoing through deck.gl right now...thinking about [flow-jsdoc](https://github.com/Kegsay/flow-jsdoc).
