### ISSUE TITLE
Migrate to use `prop-types` instead of `React.PropTypes`

### ISSUE THREAD

**Issue by btford** [uber/react-vis#369]
According to the react documentation:

> React.PropTypes is deprecated as of React v15.5. Please use the prop-types library instead.

We should consider adopting FlowType or using the new `prop-types` library.

I think the FlowType approach is a bit better, but it does mean that users not using FlowType do not get the runtime checks.

**Comment by samhogg** [comment]
@btford I just opened #368 - agreed though, Flow would be super nice

**Comment by btford** [comment]
Oh nice! Just noticed. We should try to land your change soon, and we can progressively move to Flow after that.

**Comment by mcnuttandrew** [comment]
Merged!
