### ISSUE TITLE
Move 'breaking changes' section in README to CHANGELOG

### ISSUE THREAD

**Issue by samhogg** [uber/react-vis#374]
Convention dictates that's probably the best place, and I think we should probably be using that real estate in the readme to entice users, not warn them that stuff breaks all the time.

On a similar line of thought, I'm of the opinion we should probably strip references to the pre 1.0 API in the docs (ie: line 5 of the [axes docs)[https://github.com/uber/react-vis/blob/master/docs/markdown/animation.md})

**Comment by mcnuttandrew** [comment]
I've actually actually already changed animation.md when I updated it recently. #373 deals with a mention of changes in the axes docs. I can't find any other cases?

**Comment by samhogg** [comment]
Looks like that was the only reference, thought there was another spot

**Comment by mcnuttandrew** [comment]
sick! marking as resolved but we should keep an eye out
