### ISSUE TITLE
Listeners get clobbered

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#381]
There is a reasonably frequent bug in which onValueMouseOut/onSeriesMouseOut listeners are not called due to the presence of other listeners. This often occurs in conjunction with the presence of animation. (To wit, check out the animated sunburst for more)

**Comment by samhogg** [comment]
This is what I was running into in my other PR - in my experience `onMouseLeave` is more reliable

**Comment by ajainarayanan** [comment]
@mcnuttandrew @samhogg  Are there any updates on this issue? Is there a resolution that was reached that you can share. Let me know if I can be of any help. I'm facing this issue on all the MarkSeries graphs that I'm rendering and as a workaround I right now bind the `esc` key and have an additional `x` on the `Hint` to close the hint. 

The `onValueMouseOver` gets triggered but `onValueMouseOut` is not getting triggered for me.

**Comment by ajainarayanan** [comment]
For reference I have created this webpackbin if someone wants to try to reproduce the issue: https://www.webpackbin.com/bins/-Kok65xQnKmQZ5sp6xvL. The onmouseover triggers all the time but not the onmouseout event handler. Not sure if anything can be done on the react-vis layer. Probably an issue with chrome may be (https://github.com/facebook/react/issues/4492)? 🤔

**Comment by vittvolt** [comment]
I'm also getting this problem on BarSeries, where onValueMouseOut / onSeriesMouseOut is not triggered.

**Comment by mcnuttandrew** [comment]
Anyone following this issue might be interested in the discussion on #518

**Comment by Vednus** [comment]
I got this working by turning animation off when onValueMouseOver is called and then turning it back on when onValueMouseOut is called

**Comment by jckr** [comment]
I'm going to close this one and keep discussion on #518
