### ISSUE TITLE
Add the ability to show labels on the chart (e.g. label series)

### ISSUE THREAD

**Issue by bulyonov** [uber/react-vis#39]

**Comment by mikaa123** [comment]
Hello!
Just to make sure: would this feature allow to show labels on `RadialChart`?
Are there currently any way to display labels on it?

Thanks

**Comment by bulyonov** [comment]
@mikaa123 , currently there's no way to place labels on radial chart. We will add them as soon as the label series will be supported.

I also realized that we don't support hints for the radial as well. I created a task for them here — #46.

**Comment by stolendog** [comment]
it would be great to have text labels on `RadialChart`, waiting for this too.

**Comment by ranjithnori** [comment]
+1

**Comment by mcnuttandrew** [comment]
The labelSeries is now available on the 2.0.0beta release, this ticket can be closed.
