### ISSUE TITLE
Zero width bars in IE11

### ISSUE THREAD

**Issue by ro-ka** [uber/react-vis#392]
Rendering a bar chart creates all the rectangles for the chart, but each has a width of `0` in IE11 so that the bar is unvisible. Legends and lines work perfectly.

Missing the bars in IE11:

![bildschirmfoto 2017-04-21 um 14 19 33](https://cloud.githubusercontent.com/assets/840022/25277143/c34ef578-269d-11e7-937e-699147a1007c.png)

It should look like this (screenshot from Firefox; position of the legend is a CSS issue, ignore that):

![screen shot 2017-04-21 at 14 20 53](https://cloud.githubusercontent.com/assets/840022/25277214/0b540afc-269e-11e7-9a47-854e2084fb4c.png)

**Comment by ro-ka** [comment]
Dug into the code. The problem is, that some props are empty and therefor the check `_isScaleAdjustmentPossible` in [scales-utils.js](https://github.com/uber/react-vis/blob/master/src/utils/scales-utils.js#L400-L411) returns false instead of true.

The props `_adjustBy` and `_adjustWhat` are empty arrays but should contain the columns to render as they do in other browsers.

Any idea why these are empty?

**Comment by ro-ka** [comment]
Found the problem: Using the TypeScript transpiled Set doesn’t work work with the core-js Array.from. Just needed the core-js Set polyfill.

**Comment by cadichris** [comment]
Thanks a ton @ro-ka, you saved me days of headaches 😍 .

> Just needed the core-js Set polyfill.  

For me it meant going from 

```js
import "core-js/fn/array/includes";
import "core-js/fn/array/from";
import "core-js/fn/array/find";
```

to 


```js
import "core-js/fn/set"; // <--  the core-js Set polyfill.
import "core-js/fn/array/includes";
import "core-js/fn/array/from";
import "core-js/fn/array/find";
```
