### ISSUE TITLE
deck.gl pinned at 4.0.0 on master and beta.4

### ISSUE THREAD

**Issue by abmai** [uber/react-vis#394]
Is there a reason why `^4.0.0` couldn't be used instead? The pinned version causes multiple versions error when app also specifies `deck.gl` as a dep.

**Comment by mcnuttandrew** [comment]
In the past deck.gl has exhibited some instability in between patch versions, so this was done out of paranoia more than any real logical thinking. That said, given how many hands are on deck.gl these days I'd wager it'd be safe to let the version be more loose here

**Comment by ibgreen** [comment]
> In the past deck.gl has exhibited some instability in between patch versions, ...  I'd wager it'd be safe to let the version be more loose here

Yes - we have taken a lot of precautions in deck.gl v4 to avoid the patch regressions we saw after the initial v3 release.

@mcnuttandrew @shaojingli

**Comment by mcnuttandrew** [comment]
Now that deck.gl has been pulled out, this issue can be closed.
