### ISSUE TITLE
Gridlines not rendering

### ISSUE THREAD

**Issue by rmammina** [uber/react-vis#395]
I don't know what I'm missing here, but for some reason the gridlines don't seem to render with a XY Plot component. Not sure if I need to place the components in a certain order, or specify certain properties for the gridlines.

Here's a preview of what the graph looks like
![image](https://cloud.githubusercontent.com/assets/978280/25364424/4112d3f0-2917-11e7-92ce-862ad86e8171.png)

and the ordering of my components.

```
class Graph extends Component {
  render() {
    return (
      <div className="graph">
        <XYPlot
          width={1100}
          height={300}>
          <HorizontalGridLines />
          <VerticalBarSeries 
            data={impressions}
          />

          <VerticalGridLines />
          <XAxis tickTotal={10} tickSize={3} />

          <YAxis /> 
        </XYPlot>
      </div>
    );
  }
}
```

**Comment by rmammina** [comment]
It looks like the delta in y1 to y2 is 0, which is causing the thickness of the line to go to 0. Not sure if there is a prop that will change this.

![image](https://cloud.githubusercontent.com/assets/978280/25406641/444277ec-29bc-11e7-8d35-763812f10c2f.png)

**Comment by rmammina** [comment]
Looks like this is your problem
```
          const pathProps = {
            [`${tickYAttr}1`]: pos,
            [`${tickYAttr}2`]: pos,
            [`${tickXAttr}1`]: 0,
            [`${tickXAttr}2`]: length
          };
```

The y2 attribute doesn't have any difference, so the gridline will never be visible.

**Comment by rmammina** [comment]
I was able to get them to show by specifying the line thickness on the css class.
```
  .rv-xy-plot__grid-lines__line {
    stroke: gray;
    stroke-width: 1;
  }
```

Would be nice if these were set by default.

**Comment by Lobosque** [comment]
I know this issue is closed but to avoid other people wasting time (I've been trough the same problem!):
Do not forget to add the stylesheet to your app. There are instructions in the Readme.

**Comment by wpcarro** [comment]
Thanks, @Lobosque. Where is this documented? I'm not seeing the instructions [here](https://uber.github.io/react-vis/documentation/getting-started/creating-a-new-react-vis-project), which is where I expected to find this kind of information.

**Comment by vandosant** [comment]
for anyone else coming here, like me, i found info on importing the styles here: https://github.com/uber/react-vis/blob/master/docs/getting-started/getting-started.md

i decided to import the styles into my component since it's only needed in one place:
```
import '../node_modules/react-vis/dist/style.css';
```

or just:
```
import 'react-vis/dist/style.css';
```

**Comment by squillace91** [comment]
It seems mine is loading the styles.css, also I can see in my dev tools the colors. However, this is how my demo graph is showing up.

[
<img width="347" alt="screen shot 2018-06-19 at 9 45 19 pm" src="https://user-images.githubusercontent.com/1086713/41635062-475fcf56-740c-11e8-99eb-930fd50a6f9b.png">
](url)

Did anyone have this problem before?
