### ISSUE TITLE
opacity behavior

### ISSUE THREAD

**Issue by jckr** [uber/react-vis#397]
Right now I can't have an opacity set at the level of a series, unless I also set opacityType to be "category" which is really counter-intuitive:

ie <MarkSeries opacity="0.2" data={data}/> -> won't take opacity into account
<MarkSeries opacity="0.2" opacityType="category" data={data}/> -> all marks are now 20% opaque

And if that wasn't cumbersome enough, if I do that, I won't be able to pass opacity values through the data. (I mean I could, but the opacity scale will still be categorical, so it's impossible to pass values directly). 

That's linked to https://github.com/uber/react-vis/pull/275 and changes on the scale-utils. PR coming up

**Comment by mcnuttandrew** [comment]
I think this was addressed in #398
