### ISSUE TITLE
Tick Labels are cut off

### ISSUE THREAD

**Issue by kbouaazzi-ds** [uber/react-vis#400]
Hello,
I can't seem to get the labels on these axes to show up properly. Here is my code: 

```import React from 'react'
import { XYPlot, PolygonSeries, MarkSeries, XAxis, YAxis, VerticalGridLines, HorizontalGridLines } from 'react-vis';

const data = [{ x: 10000, y: 20000}, { x: 12000, y: 10000},
  { x: 17000, y: 30000}, { x: 14000, y: 25000},
  { x: 15000, y: 20000}, { x: 11000, y: 28000}]

const lowBandData = [
  {x: 0, y: 20000},
  {x: 0, y: 30000},
  {x: 20000, y: 20000},
  {x: 20000, y: 10000}
]

export class ReactVisExample extends React.Component {
  render() {
    return (
      <XYPlot
        width={500}
        height={500}>
        <XAxis/>
        <YAxis/>
        <HorizontalGridLines/>
        <VerticalGridLines/>
        <PolygonSeries
          data={lowBandData}
          color="gray"/>
        <MarkSeries
          data={data}
          color="green">
        </MarkSeries>
      </XYPlot>
    );
  }
}
```
![screen shot 2017-04-26 at 1 50 50 pm](https://cloud.githubusercontent.com/assets/27975257/25451952/7f96f87c-2a89-11e7-9872-52d3833fde2f.png)

As you can see, the labels on the y axis and the last label on the x axis are cutoff. Is there a work-around/some hidden param I can pass to make these show up properly?

**Comment by mcnuttandrew** [comment]
Hey @kbouaazzi-ds,

There's a couple of different ways that you could approach this problem! You could first try out adding a margin: 

```javascript
<XYPlot
  margin={{left: 100}}
  width={300}
  height={300}>
  <XAxis/>
  <YAxis/>
  <HorizontalGridLines/>
  <VerticalGridLines/>
  <PolygonSeries
    data={lowBandData}
    color="#776E57"/>
  <MarkSeries
    data={data}
    color="#4DC19C" />
</XYPlot>
```

Which would adjust the way that XYPlot is laying out the components:

![screen shot 2017-04-26 at 12 47 40 pm](https://cloud.githubusercontent.com/assets/6854312/25453642/955b15c2-2a7e-11e7-8a95-1eec1796a8de.png)

Or you could modify the actual values being shown (if you like the default margin), and use a numerical formatter, such as [d3-format](https://github.com/d3/d3-format) or [numeral](http://numeraljs.com/) and pipe that into the Axis formatter:

```javascript
<XYPlot
  width={300}
  height={300}>
  <XAxis />
  <YAxis tickFormat={tick => format('.2s')(tick)}/>
  <HorizontalGridLines/>
  <VerticalGridLines/>
  <PolygonSeries
    data={lowBandData}
    color="#776E57"/>
  <MarkSeries
    data={data}
    color="#4DC19C" />
</XYPlot>
```

Here i am using d3-format. This yields

![screen shot 2017-04-26 at 12 55 07 pm](https://cloud.githubusercontent.com/assets/6854312/25453919/97bf81da-2a7f-11e7-9de0-738f3e3d7457.png)

**Comment by kbouaazzi-ds** [comment]
Oh thanks. I didn't realize I could pass margin in at the graph level. Thanks!

**Comment by shrishail091** [comment]
You can also manage the number of the tick to be displayed using tickTotal attribute.

Example: tickTotal = 5 will limit the number of ticks to 5.
