### ISSUE TITLE
Any support for gradients in PolygonSeries?

### ISSUE THREAD

**Issue by kbouaazzi-ds** [uber/react-vis#402]
Hello,

Is there any support for linearGradients on PolygonSeries? I believe there is a way to do this by extending the PolygonSeries class but I just want to make sure that there is no gradient support already baked in.

**Comment by mcnuttandrew** [comment]
There is not currently any baked in support for svg gradients in the polygon series. If you come up with something good, feel free to file a PR

**Comment by kusold** [comment]
@kbouaazzi-ds I just tackled this for an AreaSeries:

```
export class GradientFill extends Component {
  render() {
    return (
      <defs>
        <linearGradient id="Gradient2" x1="0" x2="0" y1="0" y2="1">
          <stop offset="0%" stopColor="#009DEC" stopOpacity={0.4}/>
          <stop offset="100%" stopColor="#E4EDF2" stopOpacity={0.3} />
        </linearGradient>
      </defs>
    );
  }
}
GradientFill.requiresSVG = true;

export class Chart extends Component {
  render() {
    const {
      data,
    } = this.props;
    return (
      <XYPlot
        height={60}
        width={234}
        margin={{left: 0, right: 0, top: 0, bottom: 0}}
        xType="time"
      >
        <GradientFill/>
        <AreaSeries
          data={data}
          fill={"url(#Gradient2)"}
        />
      </XYPlot>
    );
  }
}
```

It might be useful to expose a `defs` class in React-Vis since I had to read the source to find out about `requiresSVG`.

**Comment by Smarq** [comment]
@kusold Thanks! We ended up looking at creating our gradients using feGaussianBlur. We wanted a gradient to follow the slope of a trendline but that proved to be too difficult.

**Comment by mcnuttandrew** [comment]
Hey @kbouaazzi-ds 

I added a gradientDefs component in the above PR, so this should be available whenever the next beta version is cut (@apercu would you mind cutting another beta version). Marking as resolved, but feel free to re-open if you feel otherwise

**Comment by Apercu** [comment]
I've went and deployed `1.5.0` instead of doing a new beta version, since we removed the deck.gl integration, I found it more appropriate

**Comment by Smarq** [comment]
@mcnuttandrew Thanks so much! BTW this is my (kbouaazzi-ds) non-work profile so dont get weirded out.
