### ISSUE TITLE
Bar Charts Not Rendering (again, possibly D3?)

### ISSUE THREAD

**Issue by NewETown** [uber/react-vis#406]
I'm attempting to render a horizontal bar chart with text labels on the Y axis instead of numeric labels. Numeric labels are working fine but strings appear to cause D3 errors with this message:

`Error: <rect> attribute x: Expected length, "NaN".`

Might be related to https://github.com/uber/react-vis/issues/184 ?

Here's the data I'm using. For the sake of completeness I've tried both horizontal and vertical bar charts and swapped the values for X and Y for both, none of that seems to change the error.

     <XYPlot
          width={450}
          height={300}>
          <VerticalBarSeries
            data={[
              { x: 10, y: 'bob', label: 'bob' },
              { x: 20, y: 'frank', label: 'frank'},
              { x: 10, y: 'eddie', label: 'eddie'},
              { x: 30, y: 'marge', label: 'marge'},
            ]}
            onValueMouseOver={(d) => {console.log(d);}} />
            <XAxis />
            <YAxis />
        </XYPlot>

And here are the packages being installed by NPM. I noticed that they're different from the Yarn file in the responsive vis sample (https://github.com/uber/react-vis/blob/master/examples/responsive-vis/responsive-vis-utils.js):

    └─┬ react-vis@1.3.0 
    ├── d3-array@1.2.0 
    ├── d3-collection@1.0.3 
    ├── d3-color@1.0.3 
    ├── d3-hierarchy@1.1.4 
    ├── d3-interpolate@1.1.4 
    ├─┬ d3-sankey-align@0.1.0 
    │ ├── d3-array@0.7.1 
    │ ├── d3-collection@0.1.2 
    │ └─┬ d3-interpolate@0.2.1 
    │   └── d3-color@0.3.4 
    ├─┬ d3-scale@1.0.5 
    │ ├── d3-format@1.2.0 
    │ ├── d3-time@1.0.6 
    │ └── d3-time-format@2.0.5 
    ├─┬ d3-shape@1.0.6 
    │ └── d3-path@1.0.5 
    ├── d3-voronoi@1.1.2 
    └─┬ react-motion@0.4.8 
      ├─┬ create-react-class@15.5.2 
      │ └── object-assign@4.1.1 
      └── raf@3.3.0 

I've tried the latest beta release as well as versions all the way back to 1.3, same message. This makes me think it's D3 but I'm not sure how to resolve the problem without switching package managers and forcing the proper versions of D3.

**Comment by mcnuttandrew** [comment]
Hey @NewETown 

If I understand you right, you are try to make HorizontalBarSeries. In order to get such a thing to render given your current data, you need to to switch the VerticalBarSeries to a horizontal one, and mark the y scale type as ordinal, like so:

```javascript
          <XYPlot
                yType={'ordinal'}
                width={450}
                height={300}>
                <HorizontalBarSeries
                  data={[
                    {x: 10, y: 'bob'},
                    {x: 20, y: 'frank'},
                    {x: 10, y: 'eddie'},
                    {x: 30, y: 'marge'}
                  ]}
                  onValueMouseOver={(d) => {console.log(d);}} />
                  <XAxis />
                  <YAxis />
              </XYPlot>
```

This generates an image like
![screen shot 2017-05-03 at 10 19 22 am](https://cloud.githubusercontent.com/assets/6854312/25672803/054b7ca8-2fea-11e7-801a-2bf88c776d68.png)

**Comment by NewETown** [comment]
@mcnuttandrew Aha! I hadn't marked the Y axis as ordinal, I completely missed this in the sample code:

    yType="ordinal"
    xType="linear"

Thanks for the catch
