### ISSUE TITLE
API to use chart components directly?

### ISSUE THREAD

**Issue by nsonnad** [uber/react-vis#41]
Hello, great work on this library.

I'm wondering if it is possible, or if you would like to add, some kind of API for using components such as `LineSeries` etc directly, rather than making them part of some explicit plot wrapper. The use case for this is if a user (such as myself) would like to draw them onto an existing SVG or combine them with custom SVG components that are not part of this library. For example I work on a chart-making tool and we'd like to add custom elements such as labels to the chart, but currently react-vis takes responsibility for the entire SVG.

Perhaps this API is there already, and can e.g. be used by passing all of these props to each series type, only that they are not documented as part of `propTypes`?

```
_getClonedChildComponents() {
  const {animation} = this.props;
  const {scaleMixins, data} = this.state;
  const dimensions = getInnerDimensions(this.props);
  const children = React.Children.toArray(this.props.children);
  const seriesProps = getSeriesPropsFromChildren(children);
  return children.map((child, index) => {
    const dataProps = data[index] ? {data: data[index]} : null;
    return React.cloneElement(child, {
      ...dimensions,
      animation,
      ...seriesProps[index],
      ...scaleMixins,
      ...child.props,
      ...dataProps
    });
  });
}
```

Otherwise, I'd be happy to look at submitting a PR to make this possible

**Comment by chrisirhc** [comment]
Indeed there's no easy way to do this now. Yes, you'd need to use those methods to set up the correct scales for the series children on your SVG.

One reason we're taking control of the SVG is to be able to handle mouse events within the SVG element. We might need to revisit this later to allow others to easily use Series components in their own SVG components, perhaps through exposing a higher order component that does these cloning/scale calculations and provide the relevant scales to the wrapped component.

propTypes are documented via AbstractSeries right now: https://github.com/uber-common/react-vis/blob/master/src/lib/plot/series/abstract-series.js#L35

**Comment by nsonnad** [comment]
Thanks for the helpful answer. Will try to investigate the higher order component or another approach, but it sounds like it may be a bit wide-scoping for a simple PR. Feel free to close this or tag as `feature request` or something in the mean time.

**Comment by chrisirhc** [comment]
Please do share your findings! I'll leave this open for discussion and so that others are aware of the issue. Thanks for opening the issue.

I was thinking the higher order component approach would be great to also extract out some of the logic that's deep inside XYPlot.

**Comment by mcnuttandrew** [comment]
I think another approach would be to enable an svg only mode on XYPlot. That way we can still scale our series and run all of our handlers, but serve up an embeddable svg. 

This would also enable us to be super slick and deeply nest our components! For instance, imagine I wanted to layout a small multiple of pie charts, and I wanted it to be pure SVG. (So that i could crowbar it out and drop it into sketch say). Example API

```javascript
<XYPlot ....>
<RadialChart xPosition={10} yPosition={10} data={myData}/>
<RadialChart xPosition={10} yPosition={20} data={myData2}/>
...
</XYplot>
```

**Comment by jckr** [comment]
We have no plan to do that for now but feel free to submit a PR.
