### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by MykolaGolubyev** [uber/react-vis#410]
Hello,
Do you think we could upgrade to a new version of React?

I would like to volunteer if possible.

**Comment by mcnuttandrew** [comment]
Hey @MykolaGolubyev,
This warning is due to deck.gl calling PropTypes directly from the React package, as soon as #401 lands this issue will go away! Sorry for inconvenience/noise

**Comment by MykolaGolubyev** [comment]
Ah, thanks for letting me know. I was searching for the existing issue and didn't spot the connection.
