### ISSUE TITLE
Contour Series

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#419]
It would be really cool if we could add a contour series! This would allow use to do really expressive heatmaps and contours:

![faithful](https://cloud.githubusercontent.com/assets/6854312/26010076/601471c2-3700-11e7-84e5-17175e2dfbf4.png)

One way that this could be done is by bostock's wonderful d3-contour lib (https://github.com/d3/d3-contour)

**Comment by mcnuttandrew** [comment]
@Apercu will publish a new version (contour + radar = minor version)?

**Comment by Apercu** [comment]
Sure! ;D
