### ISSUE TITLE
bar chart with time series data not lineair  

### ISSUE THREAD

**Issue by eborst** [uber/react-vis#426]
Hi,

I want to have a bar chart with time series of data. 
This data is not lineair, so in the chart I want to see gaps over the Xaxis and the labels customized.
something like this:
![image](https://cloud.githubusercontent.com/assets/11938157/26374981/85184fc4-4007-11e7-977a-47c57bd06aac.png)

Is that possible with react-vis? is there an example?
Thanks in advance.

**Comment by mcnuttandrew** [comment]
Hey @eborst 

It is certainly possible to do this with react-vis! You want to be using the rectSeries, which allows you to specify the left and right values of your rectangles. I'll cook up an example, one sec

**Comment by mcnuttandrew** [comment]
Alright here we go. In the PR referenced above (#428) I added an example of how to make a histogram using a time axis and irregularly spaced data. It yields a chart that looks like

![screen shot 2017-05-23 at 2 06 56 pm](https://cloud.githubusercontent.com/assets/6854312/26376411/3d6d9a1c-3fc1-11e7-82dd-9c357d897fa5.png)

I tried to model it the data off of @eborst 's data. Here's the meat of it

```javascript
const timestamp = new Date('May 23 2017').getTime();
const ONE_DAY = 86400000;
const DATA = [
  {x0: ONE_DAY * 2, x: ONE_DAY * 3, y: 1},
  {x0: ONE_DAY * 7, x: ONE_DAY * 8, y: 1},
  {x0: ONE_DAY * 8, x: ONE_DAY * 9, y: 1},
  {x0: ONE_DAY * 9, x: ONE_DAY * 10, y: 2},
  {x0: ONE_DAY * 10, x: ONE_DAY * 11, y: 2.2},
  {x0: ONE_DAY * 19, x: ONE_DAY * 20, y: 1},
  {x0: ONE_DAY * 20, x: ONE_DAY * 21, y: 2.5},
  {x0: ONE_DAY * 21, x: ONE_DAY * 24, y: 1}
].map(el => ({x0: el.x0 + timestamp, x: el.x + timestamp, y: el.y}));

export default class Example extends React.Component {
  render() {
    return (
      <XYPlot
        xDomain={[timestamp, timestamp + 30 * ONE_DAY]}
        yDomain={[0.1, 2.1]}
        xType="time"
        width={300}
        height={300} >
        <VerticalGridLines />
        <HorizontalGridLines />
        <XAxis />
        <YAxis />
        <VerticalRectSeries data={DATA} style={{stroke: '#fff'}}/>
      </XYPlot>
    );
  }
}
```

**Comment by eborst** [comment]
Hi @mcnuttandrew,
Thanks for you quick reaction. This looks promising!
I have played a bit with your example, but sill do have some issues.
The data I use is like:
`[{"sensorid":1,"value":0.6,"date":"2017-05-11T20:00:00Z"},{"sensorid":1,"value":0.6,"date":"2017-05-11T21:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-12T09:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-12T14:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-12T21:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-12T22:00:00Z"},{"sensorid":1,"value":1.5,"date":"2017-05-13T03:00:00Z"},{"sensorid":1,"value":5.4,"date":"2017-05-13T17:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-14T10:00:00Z"},{"sensorid":1,"value":1.2,"date":"2017-05-14T15:00:00Z"},{"sensorid":1,"value":0.9,"date":"2017-05-14T16:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-16T22:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-18T06:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-18T07:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-18T08:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-18T09:00:00Z"},{"sensorid":1,"value":0.3,"date":"2017-05-19T04:00:00Z"}]
`

When I use your example I get a lot of overlap.
Earlier I was looking into generating ticks for this. 
Your approach is a bit different by using a histogram for this. 

Could you give me some hints to get this displayed in a bar chart?
Many thanks,

**Comment by mcnuttandrew** [comment]
Hey @eborst 

The big insight with using RectSeries rather than BarSeries is that you need to specify left and right values for the bars. The way that is done, is by specify x and x0 (for VerticalRectSeries) or y and y0 (for HorizontalRectSeries). This allows you to exactly specify the part of axis covered by the rectangle. So if your data is in hours, then simply specify that! Also, I find it to be a little easier to work with date in javascript if they are converted to unix epoch rather than plain date strings. (Which is what i do in the referenced example).

As for axis ticks, If you want to exactly specify your ticks, you can! Simply give xAxis or yAxis a prop tickValues!

**Comment by eborst** [comment]
That clarifies a lot.... ;) 
I will give this  a try.

**Comment by mcnuttandrew** [comment]
I'm gonna close this issue, but if you feel that it is not resolved, feel free to re-open or we can continue this discussion under close

**Comment by eborst** [comment]
Ok so far it is going well.
I can get the data on screen using VerticalRectSeries.
2 things I can't get working correctly:

Hint: I tried mouseMove on the VerticalRectSeries
like: `<VerticalRectSeries data={DATA}
          onValueMouseOver={this._rememberValue}
          onValueMouseOut={this._forgetValue}
    />
        {value ?
          <Hint value={value}>
          </Hint> :
          null
        }`
Hint is shown, but on weird places on the screen. sometimes close to the object, but sometimes far away.
How can I control that? there's also not that much documentation about this.

**Comment by eborst** [comment]
also another thing I found is that onValueMouseOut is not working for VerticalRectSeries.

**Comment by mcnuttandrew** [comment]
can you move this over to a code pen so i see what you are doing directly? example https://codepen.io/Apercu/pen/mmLOpY?editors=0010

**Comment by eborst** [comment]
I've tried to move this to code pen, but I can't get this working there.
The code is simple:
`import React, { Component } from 'react'
import { Hint, XYPlot, VerticalGridLines, HorizontalGridLines, XAxis, YAxis, VerticalRectSeries } from 'react-vis';

const RDATA =[{"sensorid":1,"value":0.6,"date":"2017-05-11T20:00:00Z"}
       ,{"sensorid":1,"value":0.6,"date":"2017-05-11T21:00:00Z"}
       ,{"sensorid":1,"value":0.3,"date":"2017-05-12T09:00:00Z"}
       ,{"sensorid":1,"value":0.3,"date":"2017-05-12T14:00:00Z"}
       ,{"sensorid":1,"value":0.3,"date":"2017-05-12T21:00:00Z"}
       ,{"sensorid":1,"value":0.3,"date":"2017-05-12T22:00:00Z"}
       ,{"sensorid":1,"value":1.5,"date":"2017-05-13T03:00:00Z"}
       ,{"sensorid":1,"value":5.4,"date":"2017-05-13T17:00:00Z"}];


function HintContent({value}) {
  const {x, y} = value;
  return <div>
    <div style={{
             borderBottom: '1px solid #717171',
             fontWeight: 'bold',
             marginBottom: 5,
             paddingBottom: 5,
             textTransform: 'uppercase'
    }}>{y}</div>
  </div>;
}

class SimpleBarChart extends Component {
  constructor(props) {
    super(props);
    this.state = {
      value: null
    };
    this._rememberValue = this._rememberValue.bind(this);
    this._forgetValue = this._forgetValue.bind(this);
  }

  _rememberValue(value) {
    this.setState({value});
    console.log('remembervalue: '+ value);
  }

  _forgetValue() {
    this.setState({value: null});
    console.log('forgetvalue: ' + this.state.value);
  }

  render() {
    const {value} = this.state;
    var DATA = RDATA.map(el => ({x0: new Date(el.date).getTime()  ,x: new Date(el.date).getTime() +1000000 , y: el.value}));

    return (
      <div>
        <XYPlot
          xDomain={[1494532800000 , 1494694800000]}
          yDomain={[0.0 ,10.0]}
          xType="time"
          width={800}
          height={300}
        >
          <VerticalGridLines />
          <HorizontalGridLines />
          <XAxis />
          <YAxis />
          <VerticalRectSeries data={DATA}
            onValueMouseOver={this._rememberValue}
            onValueMouseOut={this._forgetValue}
          />
          {value ?
            <Hint value={value} align={{horizontal: "auto", vertical: "auto"}}>
              <HintContent value={value} />
            </Hint>
            :
            null
          }
        </XYPlot>
      </div>
    )
  }
}
export default SimpleBarChart;
`
