### ISSUE TITLE
Using small amounts of data in the plot examples does not exemplify well

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#429]
Many of our examples use a trivial amount of data (3-5 points), this is not helpful for people who are evaluating whether or not the library meets many of their needs. I suggest we move through each of the example and expand them to look a little more realistic, or at least a little more appealing.

**Comment by jckr** [comment]
We should build a new example section with more substantive examples.

**Comment by mcnuttandrew** [comment]
As a third example section or ...?

**Comment by jckr** [comment]
Yeah. More elaborate examples with explanations

**Comment by ericsoco** [comment]
deck.gl has basic examples to run locally and more advanced (and
impressive) demos that run online (and can also be picked apart by
interested devs). we might follow the same pattern here...

**Comment by mcnuttandrew** [comment]
I think that was the idea behind the examples folder we already have? So I guess maybe we should stop using that as alpha testing area and use it for its original intended purpose

**Comment by jckr** [comment]
yes we need more examples. and when we'll have more examples we'll still need more examples. so i'm going to close it for now but welcome more examples.
