### ISSUE TITLE
Add makeHeightFlexible

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#455]
In #262 @Firenze11 suggested

"Is there a plan to also expose "makeHeightFlexible" too? I'm try to use a HorizontalBarSeries chart to function as a vertical indexing sidebar, and found it would be useful to auto-determine its height."

**Comment by jckr** [comment]
<img width="1133" alt="screenshot 2017-06-29 19 45 45" src="https://user-images.githubusercontent.com/9727630/27718866-95a5128c-5d03-11e7-846c-2bb50becf003.png">
will write the PR tomorrow
