### ISSUE TITLE
can't generate the docs anymore?

### ISSUE THREAD

**Issue by jckr** [uber/react-vis#459]
did something change?
I do yarn start-docs
I get
ERROR in ../examples/complex-chart/complex-chart-example.js
Module not found: Error: Can't resolve 'react-vis' in '/Users/jerome/react-vis/examples/complex-chart'
 @ ../examples/complex-chart/complex-chart-example.js 27:0-152
 @ ./docs-app/components/home.js
 @ ./docs-app/routes.js
 @ ./app.js
 @ multi (webpack)-dev-server/client?http://localhost:3001 webpack/hot/dev-server ./app.js

(many times for many examples)

**Comment by mcnuttandrew** [comment]
Try building the examples, e.g. Cd examples, yarn?

**Comment by jckr** [comment]
that worked! you're missed Andrew!

**Comment by mcnuttandrew** [comment]
We should maybe write a script so this doesn't happen again? Something like build-examples? And maybe have that be called from the docs script?

Alternatively we could also maybe simplify the examples folder so there isn't so much boiler plate?
