### ISSUE TITLE
Example + docs site looks bad on mobile

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#463]
I can't say what percentage of the traffic to the site is on mobile, but I can say it looks real bad.

**Comment by Apercu** [comment]
We got a slight improvement of this, I think there is still a few charts that should be wrapped to prevent overflowing. I think @jckr wanted to do something about this

**Comment by jckr** [comment]
ok the examples don't look great and we can improve on that. the website looks fine under safari on iphone but not great with chrome with iphone (can't navigate). seems more like an Ocular issue.

**Comment by mcnuttandrew** [comment]
Addressed as an ocular issue at https://github.com/uber-web/ocular/issues/55
