### ISSUE TITLE
CanvasSeries API Change

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#467]
The current api for making series flip into canvas mode is kind of cumbersome. While It is really pleasant to simply say RectSeriesCanvas, it is not exactly developer friendly to have each of these broken out into it's own series. It means we have to test and document double the number of components. Given this, I propose a breaking API change:

- add a new prop to all series: renderMethod
- delete all canvas series and move the canvas rendering into the component itself

This would significantly deflate the number of series components, and it would leave room for us to add new rendering systems at some point in the future (ReGL? Deck.gL? ReactNative?). Love to hear thoughts

**Comment by jckr** [comment]
i gave it some thought before you brought it up; i don't think we'd have to delete components. we could have something like: 

```
class RectSeries extends AbstractSeries {
...
render() {
  if (this.props.renderMethod === 'canvas') {
  return (<rectSeriesCanvas />);
  }
  ...
}
```
 
that renderMethod, or however we call it, could also be used to trigger renderCanvasComponents. 
```
 const componentsToRender = components.filter(c => c && (c.props.renderMethod === 'canvas' || !c.type.requiresSVG && c.type.isCanvas));

As for testing, I don't see much impact. We'd have to write tests for either cases.
Likewise for documentation: either we keep the exact same API, or we'd have to write docs for both.

**Comment by mcnuttandrew** [comment]
I guess I'm a little apprehensive about using the render method directly, as this will cause any custom renders to have to look to it's grandchildren (rather than just children), which seems like it could create chaos.

**Comment by jckr** [comment]
i'm more in favor of 2 separate components now (+ new ones for webGL, react-native etc.)
will close for now but may reference in future
