### ISSUE TITLE
[Radar] starting position of variable line

### ISSUE THREAD

**Issue by zachguo** [uber/react-vis#469]
Variable line starts from `right` by default, is there a way to configure it to start from `top`?

**Comment by mcnuttandrew** [comment]
Just to clarify: the default behavior has the first line pointed at 3 oclock, and you want to be able to manipulate that?

**Comment by zachguo** [comment]
Yes, it looks a bit weird for charts having odd number of variables, i.e. 3. 
Starting from 12 o'clock would look more balanced.
<img width="183" alt="screen shot 2017-06-26 at 3 08 22 pm" src="https://user-images.githubusercontent.com/3478203/27562420-53b76426-5a81-11e7-9648-112225156eda.png">

**Comment by mcnuttandrew** [comment]
My kneejerk is introduce a new prop call startingAngle, which by default would be at 3 oclock (following the convention from polar coordinates) and accept a starting position in degrees. That seem reasonable?

**Comment by zachguo** [comment]
Yes, sounds perfect.

**Comment by zachguo** [comment]
TBH, simply changing default angle would work too. I guess most people expect it to start from 12 o'clock, to make chart look symmetrical, but I can be wrong.

**Comment by mcnuttandrew** [comment]
this is addressed in #471 , and should be available in v1.6.3
