### ISSUE TITLE
[Radar] smaller value on axis starts from edge rather than center

### ISSUE THREAD

**Issue by zachguo** [uber/react-vis#477]
<img width="453" alt="screen shot 2017-06-27 at 6 58 38 pm" src="https://user-images.githubusercontent.com/3478203/27617379-c8852cea-5b6a-11e7-9923-2a77d6095ff2.png">

For some axes, smaller values start from outer ends instead of ends near center.
I tried reverse the order of `domain` array, but axes stay the same.

`react-vis v1.6.4`

**Comment by zachguo** [comment]
In my case, only the order of tick labels are wrong, underlying domain and ticks are correct.

**Comment by zachguo** [comment]
@mcnuttandrew Why is `domain` sorted by default? https://github.com/uber/react-vis/blob/2c898cf7e5169a14895c880dd9047c22b6c71e82/src/radar-chart/index.js#L50

**Comment by mcnuttandrew** [comment]
@zachguo that's a good catch! i'll file a PR about it shortly. 

Btw, in the future if you find yourself digging in super deep like this, feel free to file a PR we accept/delight in contributions

**Comment by zachguo** [comment]
@mcnuttandrew I'm still getting myself familiar with the codebase, will definitely do when I'm ready.
For this issue, I'm still not sure what the cause is.

**Comment by mcnuttandrew** [comment]
I mean you correctly identified it, i need to clarify the formatting system a little (so that there isn't a bunch of junk in the center 

![screen shot 2017-06-29 at 5 00 07 pm](https://user-images.githubusercontent.com/6854312/27715499-6f85e39a-5cec-11e7-9f44-fadfefb7f4cf.png)

**Comment by mcnuttandrew** [comment]
the fix is in! once a new patch is cut this issue should be addressed (@apercu or @ericsoco)
