### ISSUE TITLE
VerticalRectSeries - single time slice expands xDomain

### ISSUE THREAD

**Issue by tusharchhibber** [uber/react-vis#478]
Reopening the issue from past #443 

It appears that a fix was merged #447 
but it was reverted as seen in history of the file
https://github.com/uber/react-vis/commits/master/src/utils/scales-utils.js

**Comment by mcnuttandrew** [comment]
@CharlieMartell It looks like you reverted #447? Is there a reason why you did that?

**Comment by CharlieMartell** [comment]
Hmm, git got confused and created a merge in the file when only bumping package.json so I reverted to the previous SHA will fix soon.
