### ISSUE TITLE
Unable to display Sunburst with OnHover Hints

### ISSUE THREAD

**Issue by mohithingorani** [uber/react-vis#483]
Hey react-vis team!

Is there an example available of a sunburst with onHover Hint?
Although the onValueMouseOver & onValueMouseOut can be triggered, i suspect that the x,y coordinates being passed on are incorrect.
[Animation has been set to false]

Thanks!

**Comment by mcnuttandrew** [comment]
Hey @mohithingorani, You uncovered a great bug! See the PR for more details. Thanks for catching that.

**Comment by mohithingorani** [comment]
You are welcome! @mcnuttandrew 
Thank you for the quick response. 
Another small problem with Sunbursts that i have noted is that the paths generated in sunburst have a className = "undefined " unlike a radial chart's "rv-radial-chart__series--pie__slice". 
It would make it simple to style sunburst elements if we had a class attached to the path elements.

Thanks!
<img width="779" alt="screenshot 2017-06-30 14 45 24" src="https://user-images.githubusercontent.com/5414494/27755260-7ae3b804-5da3-11e7-838e-395c4341d28a.png">

**Comment by mcnuttandrew** [comment]
I left this open while #505 was in flight, and forgot to close it. all should be well!
