### ISSUE TITLE
Issue with VerticalBarSeries with single data

### ISSUE THREAD

**Issue by ajainarayanan** [uber/react-vis#484]
Not sure if this was a known or issue or if I am doing something wrong but I am trying to render a `<Verticalbarseries />` chart for single data and I'm seeing some unusual results.

I'm not sure if #201 is related but nevertheless the same chart with more than 1 data point works fine. Seems like there is a one off case where either I'm doing something wrong or width of the `rect` element is not scaled correctly.

Here is a demo of what I'm seeing: https://www.webpackbin.com/bins/-KoVgdGKnDhCaxsgVyR_

Please feel free to close this if its not an issue and more of a question. Happy to ask the same in other QA forums.

**Comment by samhogg** [comment]
This is related to #443 too, there's a fix in #447 but was reverted, being tracked in #478.

**Comment by ajainarayanan** [comment]
@samhogg Thanks! Is there a timeline when this will be in a release? (1.6.5?) Right now I'm working around this by adding a dummy data point. Would be helpful if its in a release that I could use.

**Comment by samhogg** [comment]
@ajainarayanan I'll refer you to @mcnuttandrew on that - I don't have commit rights, just use `react-vis` a lot and tend to watch issues

**Comment by mcnuttandrew** [comment]
@ajainarayanan @samhogg i'm pushing @CharlieMartell to fix his re-revert and patch, so hopefully today?

**Comment by CharlieMartell** [comment]
Hey I will push address this when I'm back in a bit. Will be today.

**Comment by ajainarayanan** [comment]
@mcnuttandrew @CharlieMartell Thanks for the quick response! Will look out for it

**Comment by ajainarayanan** [comment]
@mcnuttandrew @CharlieMartell This https://github.com/uber/react-vis/pull/487 PR for some reason doesn't fix this issue. I have updated the same webpack-bin link and I am using `1.6.7` and I'm still seeing the issue. Is there anything I'm missing?

**Comment by CharlieMartell** [comment]
For tracking references the hyperlink to unusual behaviour is [here.](https://www.webpackbin.com/bins/-KoVgdGKnDhCaxsgVyR_)

**Comment by CharlieMartell** [comment]
@sandiiarov Was this the issue you were originally addressing in: [this commit](https://github.com/uber/react-vis/commit/c440565495a0caee0d64955f5448002fc3f5816f) ?
