### ISSUE TITLE
Multi-line ticks

### ISSUE THREAD

**Issue by pcmaffey** [uber/react-vis#488]
So I'm trying to display custom ticks, with multiple lines, eg. 'Day /r Month'.

The only way to do that in svg text element is wrapping each line in a tspan tag. However when I use tickFormat function to return even a single tspan element, the AxisTicks component errors, turning my tspan into [object tspan].

 ```
    const tspan = document.createElementNS("http://www.w3.org/2000/svg", 'tspan');
    tspan.setAttribute('x', 0);
    tspan.setAttribute('dy', '1em');

    const textNode = document.createTextNode(text);
    tspan.appendChild(textNode);
```

returns `<tspan x="0" dy="1em">text</tspan>`

And errors 

> Objects are not valid as a React child (found: [object SVGTSpanElement]). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `AxisTicks`.

Is there any workaround (other than multiple axes) to render 
`<tspan x="0" dy="1em">line 1</tspan>
<tspan x="0" dy="1em">line 2</tspan>`

**Comment by mcnuttandrew** [comment]
Hey @pcmaffey, this functionality isn't currently supported, but totally should be! I'll file a PR about it shortly

**Comment by mcnuttandrew** [comment]
Hey @pcmaffey 
I was totally wrong! That functionality is currently supported. Checkout the example here in the pr i just put #490. I think your problem is you need to give back a single react element, not an array. Ie 
```javascript
<tspan>
<tspan x="0" dy="1em">line 1</tspan> <tspan x="0" dy="1em">line 2</tspan>
</tspan>
```

I'm going to mark this as resolved, but you feel otherwise feel free to re-open

**Comment by pcmaffey** [comment]
Thanks for the quick reply!

Good to know about wrapping tspan elements. That solves 1 question. Unfortunately, the error I'm getting above is happening even with a single tspan element. Somehow my tickFormat function, which returns `<tspan>text</tspan>` is getting converted into an object `[object SVGTSpanElement]` when rendered, and so react is erroring trying to render that...

**Comment by mcnuttandrew** [comment]
Huh, single ones look like they are working for me as well. Can you post your code somewhere? My kneejerk guess is that it looks like you are returning an array rather than a pure object, but i can't be sure without seeing code?

**Comment by pcmaffey** [comment]
See my edit above. Problem was how I was defining my svg elements.
