### ISSUE TITLE
npm release v1.6.5 loses all updates since #466

### ISSUE THREAD

**Issue by zachguo** [uber/react-vis#495]
npm release v1.6.5 loses all updates since https://github.com/uber/react-vis/pull/466

At least in Radar chart, #466, #471, #472, #474, #486 are all lost.

My npm version is v5.0.4.

**Comment by mcnuttandrew** [comment]
hmm looks like there was a botched build, @Apercu would you mind re-cutting?

**Comment by Apercu** [comment]
Sure

**Comment by Apercu** [comment]
Deployed `1.6.6`, feel free to close if the issue is resolved.

**Comment by zachguo** [comment]
#482 wasn't but now is missing

**Comment by zachguo** [comment]
#483 is included but it seems there's a bug with #482. I'm investigating.
