### ISSUE TITLE
RadarChart: ticks are not correctly presented when startingAngle is Math.PI / 2

### ISSUE THREAD

**Issue by zachguo** [uber/react-vis#497]
`ticks` are not correctly **presented** when `startingAngle` is `Math.PI / 2` (underlying tick values are correct)

i.e. wrong `ticks` when `startingAngle: Math.PI / 2`
<img width="227" alt="screen shot 2017-07-05 at 2 11 11 pm" src="https://user-images.githubusercontent.com/3478203/27885157-d615d9a0-618b-11e7-9310-e4288eeb92fb.png">

correct when `startingAngle: Math.PI / 2 + 0.01` or `startingAngle: Math.PI / 2 - 0.01`
<img width="228" alt="screen shot 2017-07-05 at 2 10 10 pm" src="https://user-images.githubusercontent.com/3478203/27885178-ec5c5572-618b-11e7-821f-dd07361f448c.png">

I may dig deeper later today.

**Comment by zherutis** [comment]
I noticed that the ticks are also wrongly generated when there are 4 axes. The one pointing up has inverted order of tick labels, while the one pointing down lacks ticks. The example can be seen in the following codepen:
https://codepen.io/zherutis/pen/OgYrEK

**Comment by mcnuttandrew** [comment]
@zherutis the problem turned out to be related to the way decorative ticks were behaving when the line is vertical. The fix is not dependent on the number of axes, so all of the above issues should be fixed once #515 lands

**Comment by mcnuttandrew** [comment]
#515 is in 1.7.0 ! I'm marking this as resolved
