### ISSUE TITLE
broken link in documentation

### ISSUE THREAD

**Issue by alaindresse** [uber/react-vis#498]
The link to mark series in
    http://uber.github.io/react-vis/#/documentation/xy-plot/series
is broken.

It should be
    http://uber.github.io/react-vis/#/documentation/xy-plot-series/mark-series
instead of
    http://uber.github.io/react-vis/mark-series.md.

**Comment by mcnuttandrew** [comment]
Should be resolved, marking as closed

**Comment by alaindresse** [comment]
Super impressed: Super quick !
