### ISSUE TITLE
Axis label is off

### ISSUE THREAD

**Issue by Firenze11** [uber/react-vis#501]
I run the same code both locally and on a production machine, and the AxisLabels are displayed differently. 
On production machine, AxisLabels are off:
![image](https://user-images.githubusercontent.com/4994677/27934705-c4718494-625b-11e7-9f98-68441155ae43.png)

but on local machine, they display fine:
![image](https://user-images.githubusercontent.com/4994677/27934670-9e207b74-625b-11e7-8236-d2c67ce614c1.png)

This is happening to all XYPlots in my code. Can you provide any lead on what could be wrong with the package on my production machine? Thanks.

**Comment by mcnuttandrew** [comment]
My kneejerk reaction would be that there is probably a problem with textAnchor, but I am not amazingly sure. Do you think you could reproduce this in a codepen?

**Comment by Firenze11** [comment]
Thanks, this makes a lot of sense. Maybe there's something messed up in my css on the production machine.
local:
![image](https://user-images.githubusercontent.com/4994677/27935323-3aa18062-625f-11e7-84ad-11423b136f0e.png)
production:
![image](https://user-images.githubusercontent.com/4994677/27935350-6bf52cae-625f-11e7-81ea-df4348167c64.png)
Should be fixed by css overriding.
