### ISSUE TITLE
Can't resolve 'make-vis-flexible'

### ISSUE THREAD

**Issue by DsAco** [uber/react-vis#503]
i think this is a bug.
when i upgrade react-vis,
the console show this => 
Module not found: Error: Can't resolve 'make-vis-flexible' in '.........\node_modules\.1.6.6@react-vis\es'
if i remove the react-vis code,the project can run ,
if i just add import {} from 'react-vis'; the project will turn off and console that error

**Comment by jckr** [comment]
- closing
