### ISSUE TITLE
Treemap/Sunburst: encode opacity to indicate depth

### ISSUE THREAD

**Issue by jchenjc** [uber/react-vis#519]
Hi,

Is there any plan to support "encoding opacity to indicate depth" (one of the hints on the Treemap documentation) for both the Treemap and Sunburst? If not, is there any existing library to convert a color (in hex, supported by react-vis) into another color with a "depth" parameter? 

Thanks!

**Comment by mcnuttandrew** [comment]
Hey @jchenjc,

Generally this is something you need to as part of your data prep. For example, here is the dataset from the sunburst-with-tooltip example, with opacity added onto the nodes. 

```javascript
const DATA = {
  children: [
    {children: [
      {size: 1, children: [], color: COLOR[1], opacity: 0.5},
      {size: 1, children: [], color: COLOR[2], opacity: 0.5}
    ], color: COLOR[3], opacity: 1},
    {size: 1, children: [], color: COLOR[4], opacity: 0.5},
    {size: 1, children: [], color: COLOR[5], opacity: 0.5},
    {size: 1, children: [], color: COLOR[6], opacity: 0.5},
    {children: [
      {size: 1, children: [], color: COLOR[7], opacity: 0.5},
      {size: 1, children: [], color: COLOR[8], opacity: 0.5}
    ], color: COLOR[9], opacity: 1}
  ]
};
```
The original looks like this
![screen shot 2017-07-28 at 11 41 26 am](https://user-images.githubusercontent.com/6854312/28731720-d92d57c0-7389-11e7-8ae4-3f2797357893.png)

And the opacity encoded with depth version looks like this:
![screen shot 2017-07-28 at 11 41 07 am](https://user-images.githubusercontent.com/6854312/28731719-d91626a4-7389-11e7-9f73-aca0c7667a90.png)

(i also added the hideRootNode prop to remove the center) Encoding opacity to tree depth is something the library could do for you, but it most likely be clearer and easier if users just did it themselves. I think this answers your question, but maybe i've missed something?

**Comment by jchenjc** [comment]
Thank you for the explanation @mcnuttandrew! Yes, that answered my question.

**Comment by mcnuttandrew** [comment]
I totally hear you! I just worry that such a feature would have a lot of edge cases and be kinda cumbersome to use. I'm going to mark this as resolved, but feel free to re-open if you feel otherwise
