### ISSUE TITLE
Doc Typos

### ISSUE THREAD

**Issue by headfox23** [uber/react-vis#520]
I found some typos in the docs:
https://github.com/uber/react-vis/blob/master/docs/markdown/line-mark-series.md#onvalueclick
The title says `onvalueclick` but the example shows `onClick`
The same applys to:
- onValueMouseOut -> onMouseOut
- onValueMouseOver -> onMouseOver

Thanks :)

PS: For lazy copy-paste-victims like me its misleading like hell because it simply doesnt work :D

**Comment by mcnuttandrew** [comment]
resolved!
