### ISSUE TITLE
Productionalize Candlestick

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#521]
The candlestick series type in the examples, is a good example of allowing users to extend the library to their own ends, but would be more useful as a first class series! Generally such a series solves the problem of expressing variance relative to a given mark. A robust approach to dealing with this problem would be to add two series

- A whisker series, that would be able to describe variance around either a mark or a bar. This would cover whisker plots & candle sticks.
- A wrapper candlestick series, similar to how LineMark simply wraps up two other series, CandleStick could wrap a bar and a whisker series.

For completion each of these series would require 

- examples
- test
- tests on those examples
- documentation

**Comment by arkadyan** [comment]
@mcnuttandrew I got pulled away from this after finishing the first half, but starting to look at it again. Looking at the existing BarSeries, am I correct in thinking that it always starts the rectangle at 0 (in the y or x dimension as the case may be)? It seems like I could make a pretty straightforward LineMark-style wrapper series out of the MarkSeries and WhiskerSeries right away. But if we wanted to pair the WhiskerSeries with a variation of the BarSeries like that shown in the candlestick example where there is both a high and a low value, I would first need to create a new "BarHighLowSeries" type (that's a horrible name and I'd never suggest it for real), and then combine that with the WhiskerSeries to make a CandlestickSeries. 

Does it seem like I'm on track with this conception of the state of affairs, or is there something I'm missing? Also, a MarkAndWhiskersSeries (MarkSeries + WhiskerSeries) and a CandlestickSeries (BarHighLowSeries + WhiskerSeries) are obviously not mutually exclusive.

**Comment by mcnuttandrew** [comment]
@arkadyan, as usual, you got some insightful thoughts there.

> Looking at the existing BarSeries, am I correct in thinking that it always starts the rectangle at 0 (in the y or x dimension as the case may be)

Bar series center their boxes about their value. Eg, if you have values A, B, C the boxes will have x values like [A - boxWidth/2, A + boxWidth/2] etc. In the example I did I was treating the candle stick as a wrapper on rectSeries, but i think you could just as easily do it with barSeries's, the big trick being that you would need to decorate the data by adding y0s to each of the data rows to make them "float".

> It seems like I could make a pretty straightforward LineMark-style wrapper series out of the MarkSeries and WhiskerSeries right away

I'd argue that having a MarkAndWhiskersSeries is unnecessary. It's perfectly easy to just stack the two of series on top of each other (in fact if this was the beginning of the project, i'd probably suggest LineMarkSeries is unnecessary for the same reason). Instead I'd suggest making a showcase example that shows this mark + variance behaviour, either as part of the whisker series or as part of the soon to be candlestick article. If you wanted to just expand the whisker article, this demo could show both mark + whisker as well as representing variance in a single direction.

**Comment by mcnuttandrew** [comment]
Also, as you add series, make sure you update the documentation/general-principles/scales-and-data.md
