### ISSUE TITLE
Export flexible plot components

### ISSUE THREAD

**Issue by Apercu** [uber/react-vis#525]
In addition to the `makeFlexible` method, we should maybe export the three different types of flexible graphs so it's easier to use.

**Comment by jckr** [comment]
hi just returning to a world of internet after 3 weeks. 
... isn't it not the case already?

**Comment by Apercu** [comment]
I was talking about exporting the result of `makeWidthFlexible(XYPlot)` and `makeHeightFlexible(XYPlot)`, since it's used already a few times in our showcases and might be a bit more straightforward to use for our users. Do you think that's too much?

**Comment by jckr** [comment]
I see. instead of (or in addition to) exporting makeWidthFlexible, exporting FlexibleWidthXYPlot.
sure we can do this.

**Comment by Apercu** [comment]
Cool, will `throw(pr)` for this
