### ISSUE TITLE
Question: Labels for ArcSeries and Sunburst

### ISSUE THREAD

**Issue by jchenjc** [uber/react-vis#529]
Hi, 

I looked through the docs and couldn't find a way to add label support for a Sunburst chart. But label-support is available for Radial chart. Is there a plan to add automatic labelling (given label key-value pairs in the data-tree) for ArcSeries (and Sunburst and Treemap) in the future? 

Since the library doesn't support that now, do you have any suggestions on how we could do that ourselves for now? 

Thanks!

**Comment by mcnuttandrew** [comment]
Hey @jchenjc 

I poked around a little bit and found that adding labels via child components (as would be the recommended approach) wasn't super feasible. So, to make things easy on you and me and everybody I went ahead and added them. (#531)

Question: you mention treemap in your request, but treemap already has labeling? can you say more about what you mean?

**Comment by mcnuttandrew** [comment]
In the mean time, marking as resolved, the new functionality is in v1.7.1

**Comment by jchenjc** [comment]
Hi @mcnuttandrew, thanks for the fast response! Sorry, I didn't realize Treemap already labelling. It has the same tree-data structure as the Sunburst, that's why I thought it may not have it as well. #531 looks promising, look forward to checking it out. Thanks again!

**Comment by jchenjc** [comment]
@mcnuttandrew Is it too much to ask to make the labels like this http://bl.ocks.org/metmajer/5480307? :D

**Comment by mcnuttandrew** [comment]
It certainly is, i think rotation could be enabled pretty darn easily, I'm going to re-open this issue because i am not going to be to do it *this second*. My knee jerk would to be expose this as a mode on Sunburst via prop such as rotateLabels.

**Comment by mcnuttandrew** [comment]
#558 is landed, the changes requested should be in place in 1.7.4
