### ISSUE TITLE
Adding 'animation' to Sunburst causes error on initial mouseOver

### ISSUE THREAD

**Issue by jchenjc** [uber/react-vis#535]
Hi, 

After I added 'animation' to the Sunburst chart, I got the following error on the first mouseOver event (and whatever I set for the mouseOver event didn't get fired). But any consecutive mouseOver event worked fine after that. 

<img width="1540" alt="screen shot 2017-08-07 at 3 00 11 pm" src="https://user-images.githubusercontent.com/384315/29047598-322cffde-7b81-11e7-80f2-3e20105cdace.png">

This issue didn't occur after I removed the 'animation' flag.

P.S.:
I also got the same error when poking around with the 'hideRootNode' flag. When I chose to display the rootNode, the same error occurred every time I mouseOver the rootNode.
I ended up just disabling mouseOver for rootNode.

Thanks!

**Comment by mcnuttandrew** [comment]
Hey @jchenjc,

Now that #554 is landed, I suspect that this issue should be resolved. Let me know if we can close this issue
