### ISSUE TITLE
Step (or Stair) LineSeries by specifying the interpolation

### ISSUE THREAD

**Issue by topvis** [uber/react-vis#537]
is it possible to specify the interpolation method (e.g., "stepAfter") for  `LineSeries` component to draw a step or stair line?

![image](https://user-images.githubusercontent.com/5996531/29104552-62e1aad0-7c94-11e7-9a1b-5e874d6f9c9f.png)

**Comment by mcnuttandrew** [comment]
It totally is possible! LineSeries accepts a prop called curve (see [docs](http://uber.github.io/react-vis/#/documentation/series-reference/line-series)), this allows you to do with lineSeries anything you can do with a d3 line (as specified in https://github.com/d3/d3-shape#curves)! 

![screen shot 2017-08-08 at 8 58 58 pm](https://user-images.githubusercontent.com/6854312/29104706-6e25c2cc-7c7c-11e7-974d-e8cac05ebd01.png)
 

Modifying the line-chart.js example to your use case, like so:

```javascript
(
      <XYPlot
        width={300}
        height={300}>
        <HorizontalGridLines />
        <VerticalGridLines />
        <XAxis title="X Axis" />
        <YAxis title="Y Axis" />
        <LineSeries
          className="first-series"
          data={DATA1}/>
        <LineSeries
          className="third-series"
          curve={'curveStep'}
          style={{
            strokeDasharray: '2 2'
          }}
          data={DATA2}
          strokeDasharray="7, 3"
          />
        <LineSeries
          className="fourth-series"
          curve={curveCatmullRom.alpha(0.5)}
          data={DATA3}/>
      </XYPlot>
    )
```

**Comment by mcnuttandrew** [comment]
I'm gonna mark this as resolved, feel free to re-open if this functionality isn't sufficiently covered via the curve prop.

**Comment by topvis** [comment]
@mcnuttandrew  it works perfectly. Thanks.
