### ISSUE TITLE
Treemap support for 'literal' colorType

### ISSUE THREAD

**Issue by jchenjc** [uber/react-vis#541]
Hi, 

I was able to customize the Sunburst chart by passing in a tree with style built into the data:
`
{
    title: 'John',
    size: 1,
    style: {
      fill: '#FF991F', 
      fillOpacity: 0.533
    }
}
`.

However, Treemap didn't respect the same tree data, the chart showed up with a default color (whatever I specified in the 'style' section has no effect). I don't see the 'colorType' property in the Treemap source. Is it supposed to be supported? If not, does that mean I need create a separate function to build a different tree for Treemap?

Thanks!

**Comment by mcnuttandrew** [comment]
Hey @jchenjc,

ColorType is definately supported in Treemap! Each of the nodes checks to see if it has a color value, which is then interpreted via colorType. To wit, copy and pasted from the documentation: 

```javascripr
const myData = {
 "title": "analytics",
 "color": "#12939A",
 "children": [
  {
   "title": "cluster",
   "children": [
    {"title": "AgglomerativeCluster", "color": "#12939A", "size": 3938},
    {"title": "CommunityStructure", "color": "#12939A", "size": 3812},
    {"title": "HierarchicalCluster", "color": "#12939A", "size": 6714},
    {"title": "MergeEdge", "color": "#12939A", "size": 743}
   ]
  },
  {
   "title": "graph",
   "children": [
    {"title": "BetweennessCentrality", "color": "#12939A", "size": 3534},
    {"title": "LinkDistance", "color": "#12939A", "size": 5731},
    {"title": "MaxFlowMinCut", "color": "#12939A", "size": 7840},
    {"title": "ShortestPaths", "color": "#12939A", "size": 5914},
    {"title": "SpanningTree", "color": "#12939A", "size": 3416}
   ]
  },
  {
   "title": "optimization",
   "children": [
    {"title": "AspectRatioBanker", "color": "#12939A", "size": 7074}
   ]
  }
 ]
}
```

That said, you do highlight a valuable insight, we do not support a prop style on each of the nodes, and don't mention colorType directly in the docs. These things can certainly be fixed

**Comment by mcnuttandrew** [comment]
Oh also, fill & fillOpacity are not directly relavant here bc the treemap uses DOM elements and not svg

**Comment by jchenjc** [comment]
Thanks for the quick response again @mcnuttandrew!

I see, did not realize the Treemap is not svg. Now I guess I have to refactor my 'toTree' function to populate 'color' and 'opacity' directly (instead of using 'style') if I want to share the tree-data between sunburst and treemap. 

For sunburst, I can control the width and color of the stroke by passing in different values for `data.style = { fill, fillOpacity, stroke, strokeWidth }` when the user mouseOver a particular arc. What can I use for Treemap if I want to achieve the same effect (hovering over a square or circle)? Can I use any css property, like passing in borderWidth and borderColor etc.?

Thanks!

**Comment by mcnuttandrew** [comment]
@supasonk if you are using SVG mode you can set it via style={{stroke: 'white'}} or if you are using DOM mode you can do style={{border: 'thin sold white'}} check out https://github.com/uber/react-vis/blob/master/showcase/treemap/simple-treemap.js for more details

**Comment by amitpatil321** [comment]
@jchenjc : I know its a long time, But can you please share your code, I am trying to make it work but no matter what I am not able to color tree-map children's.
