### ISSUE TITLE
Pie chart gives console error when changing number of segments is animated

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#55]
The pie chart yields a bunch of console errors like this

`d3.js:8756 Error: Invalid value for <path> attribute d="M109.35191368826634,412.2430898706445A426.5,426.5 0 0.000006912,1 -225.26700899816143,362.14965805466653L-144.9842766002235,233.08532321974673Z"`

when animation is on and the number of segments is increasing or decreasing. This doesn't appear to affect the functionality of the chart, but is a little worrisome.

**Comment by chrisirhc** [comment]
Marking this for a later release since it doesn't affect functionality.

**Comment by bulyonov** [comment]
Apparently d3 is a source of problems here: it is not able to animate arcs from the initial state without the `d` property.

**Comment by bulyonov** [comment]
Further investigation showed that d3 generates a `d` property for a path, which contains not `x,y` pairs, but a single value only (`0`, which means that both `x` and `y` are zero). Surprisingly this `d` cannot be animated using d3.

**Comment by bulyonov** [comment]
Fixed in #126
