### ISSUE TITLE
Combining props functions on charts

### ISSUE THREAD

**Issue by dbrrt** [uber/react-vis#557]
Is there a way to use at same time, onValueClick and onValueMouseOver on Sunburst charts.
I would like to animate the opacity by hovering the part and then by clicking activating something, but unfortunately, it seems impossible to have both props simultaneously in the props and having both working (click is not working if there's an onValueMouseOver).

Was it planned or more like a 'bug'?

**Comment by mcnuttandrew** [comment]
Hey @dbrrt,

This exact issue is being covered in #554! I'm adding some tests to the PR to verify this use case.

**Comment by dbrrt** [comment]
Hi @mcnuttandrew,
After removing animation prop, both over and click were working together !

**Comment by mcnuttandrew** [comment]
This issue should be resolved now that #554 is landed. Marking as resolved.

**Comment by dbrrt** [comment]
Thanks for the great work on it !
