### ISSUE TITLE
React-vis requiresSVG  doesn't work properly with Preact

### ISSUE THREAD

**Issue by mrawdon** [uber/react-vis#565]
When using Preact stateless components are rendered outside of the SVG element

![image](https://user-images.githubusercontent.com/1678756/29731804-e4c2b7fc-89b3-11e7-9ce9-108084a71bbb.png)

![image](https://user-images.githubusercontent.com/1678756/29731844-190fb23a-89b4-11e7-8c16-3b6bb249a0c3.png)

Preact makes a copy of any stateless component.  When doing that it only copies the documented React class properties https://facebook.github.io/react/docs/react-component.html#class-properties
This occurrs in Preact at https://github.com/developit/preact-compat/blob/master/src/index.js#L264

A simple solution for this is moving requiresSVG  and isSVG into defaultProps.  I've implemented this and will create a Pull Request.  Not sure if this will result in confusion though, as these aren't properties that should ever be changed from the default.

**Comment by chrisirhc** [comment]
Could we use the `statics` API instead? See https://github.com/developit/preact-compat/issues/47 .

Relevant lines:
https://github.com/developit/preact-compat/blob/e25d0607d8a00a3e2f9229f33de4dc0f63c8e931/src/index.js#L417-L419

**Comment by mrawdon** [comment]
I wasn't going to use defaultProps to do the check in xy-plot I use the props object(just needed a way to set the default)  https://github.com/Mitrend/react-vis/blob/master/src/plot/xy-plot.js#L99

So it can still be controlled by the user

developit/preact-compat#47 seems pretty specific to the children property so not really sure that its relevant here.

**Comment by chrisirhc** [comment]
> So it can still be controlled by the user

That's the thing, it shouldn't be controlled by the user per usage of the component. It should be controlled by the developer of the component.

**Comment by mrawdon** [comment]
Sorry I misunderstood your point earlier. I agree a user shouldn't be modifying these  but it doesn't seem like the functional components api gives any other options. 

We opened #569 to work out the documentation.

@mcnuttandrew any thought here?

**Comment by mcnuttandrew** [comment]
Generally I agree with @chrisirhc that the user shouldn't be able to modify this prop. I'm not sure what the right solution is! 

As i noted above, I feel like stashing the props of interest under a underscore generally reads to users that they shouldn't mess with them? Eg _isCanvas is probably not something a user will attempt to use. We could also throw warnings if the default props are different than the recieved props, however this usage feels less than clean.

**Comment by mrawdon** [comment]
Another option I was thinking of would be registering a component with it's display name to a static function on xy-plot when it's defined as to how it should render. 
Did that make any sense?  

I think this would be cleaner from an end user's perspective, but it feels unnecessary, and coupled to the implementation of xy-plot

**Comment by mcnuttandrew** [comment]
So your suggesting making the display name meaningful, like 'MyCustomComponentSVG' or 'MyCustomComponetCanvas'? That seems like there's a little too much magic there from a developers perspective? That said it is better than exposing the API in props... so maybe?

**Comment by mrawdon** [comment]
I was thinking 
in  xy-plot.js(or maybe somewhere more generic) having a function like
``` 
class XYPlot extends React.Component {
...
static registerComponentRenderType(componentClass, renderType){
 // do something to validate renderType
  XYPlot. _renderType[componentClass.displayName]=renderType;
 }
} 
...
}
XYPlot._renderType={};
```
The when I define MyCustomComponetCanvas call
```
import{ XYPlot} from 'react-vis' 
class MyCustomComponetCanvas extends React.Component{
...
}
MyCustomComponetCanvas.displayName='MyCustomComponetCanvas '
XYPlot.registerComponentRenderType(MyCustomComponetCanvas ,'Canvas');
```
