### ISSUE TITLE
Flexible plots are missing from 1.7.3

### ISSUE THREAD

**Issue by targos** [uber/react-vis#568]
Hi! I just upgraded from version 1.7.2 to 1.7.3. After the 1.7.2 release, I started using the newly exported `Flexible{Width|Height}XYPlot`. It looks like those components are not exported anymore by `react-vis`.

**Comment by Apercu** [comment]
Hey, sorry for that :/ Can you try bumping to `1.7.4`?

**Comment by targos** [comment]
They're back in `1.7.4`. Thank you!
