### ISSUE TITLE
style a single mark

### ISSUE THREAD

**Issue by ahfarmer** [uber/react-vis#574]
I'd like to highlight the mark nearest the user's mouse cursor with a border or a shadow. You see this in lots of analytics packages like for instance google analytics (see the third dot in the screenshot).

I scoured the docs & GitHub issues trying to figure out how to do this - is it possible?

![screen shot 2017-08-30 at 3 11 42 pm](https://user-images.githubusercontent.com/597825/29897565-5e0f01c0-8d96-11e7-8a91-dc53ae4e4344.png)

**Comment by mcnuttandrew** [comment]
Hey @ahfarmer

There are many ways to achieve this! One approach would be to have a second hover series with pointer-event turned off, like so

```javascript
<XYPlot>
<MarkSeries data={data} />
<MarkSeries data={hoveredPoint} style={{pointerEvents: 'none}} />
</XYPlot>
```

Another way, though more cumbersome, would be to embed this behavior in to a custom markseries. A final way would be to do this through CSS, with a rule such as 

```scss
.my-mark-series:hover {
 stroke: red;
}
```

**Comment by ahfarmer** [comment]
Whoa. Thanks for the fast response time! For my use-case, the first solution you mentioned will work very nicely.
