### ISSUE TITLE
Time type tick values showing up as floats

### ISSUE THREAD

**Issue by 0x80** [uber/react-vis#586]
I am working on this graph below. The tickValues is an array is filled with Date objects. Also the startDate and endDate are date instances. Yet the values on the x-axis are showing as floating point values. The tick values don't make any sense to me. Any idea how this can happen?

```jsx
 <FlexibleWidthXYPlot
          xType="time"
          xDomain={[startDate, endDate]}
          onMouseLeave={() => this.setState({ crosshairIndex: null })}
          height={150}
          margin={{
            left: 20,
            right: 20,
            top: 10,
            bottom: 30,
          }}
        >
          <XAxis tickValues={tickValues} />
          <LineSeries data={mappedExpectedValues} color="rgb(230, 230, 230)" />
          <AreaSeries data={mappedReportedValues} stroke="none" fill="rgba(80, 80, 110, 0.06)" />
          <LineSeries
            data={mappedReportedValues}
            color="rgb(80, 80, 110)"
            strokeWidth={3}
            onNearestX={(value, { index }) => {
              this.setState({
                crosshairIndex: index,
              });
            }}
          />
</FlexibleWidthXYPlot>
```

It looks like this:

<img width="352" alt="screenshot 2017-09-04 23 00 34" src="https://user-images.githubusercontent.com/1193520/30038445-f00526ae-91c4-11e7-9ca5-daef30882eaa.png">

I've now stared at my input data for a long time, and I'm pretty sure it is ok...

**Comment by mcnuttandrew** [comment]
Might be related to #509 ? Is your data in epoch or date strings?

**Comment by 0x80** [comment]
With epoch you mean UTC milliseconds? 

My data on both the series components and the x-axis (`[startDate, endDate]`) are Date objects instantiated from an ISO date string.

**Comment by jckr** [comment]
can't repro the issue in 1.9.1. as long as  xType="time" is specified the xAxis is going to display dates by default whether the data provided uses numbers or date objects.
