### ISSUE TITLE
`gh-pages` documentation broken

### ISSUE THREAD

**Issue by egeste** [uber/react-vis#592]
1. Requests to the root `http://uber.github.io/react-vis/` redirect to `http://uber.github.io/react-vis/website/dist/#/`, a 404 page
1. Requests to the demos page, and any subsequent page, fails to render content, instead rendering what appears to be a direct source of the intended rendering module. `http://uber.github.io/react-vis/#/examples/charts/candlestick` ->
```
module.exports = "\n\n\n## Extensibility\n\nreact-vis is easily extensible! If we don't have what you want it's easy to make! For instance, the above chart\nwas made by simply extending abstract series and adding a little sugar.\n\nSource code\n"
```

**Comment by Apercu** [comment]
Yes my bad, I am trying to deploy new docs and hitting some issues on the deployed version. Reverted, and will work on a separate fork. Thanks for reporting.
