### ISSUE TITLE
CustomSVGSeries style props ignored

### ISSUE THREAD

**Issue by jpoeppel** [uber/react-vis#594]
Hi everyone,

first of all, thanks for this great module. I have a problem with the relatively new CustomSVGSeries component, as styles passed as props (e.g. like  style={{stroke: 'red', fill: 'orange'}}, or similar the size) seem to be ignored. Glancing over the source (https://github.com/uber/react-vis/blob/master/src/plot/series/custom-svg-series.js) it looks like, the default styles are always used, unless different styles are specified on the data/row-level. Is this the intended behaviour (i.e. should styles for custom svg series only be specified on a datum by datum basis instead of globally for the entire series) or should I pass my style differently?

Thanks a lot.

**Comment by mcnuttandrew** [comment]
Solution is in latestest version!
