### ISSUE TITLE
Broken link on the line-mark-series documentation page

### ISSUE THREAD

**Issue by williamge** [uber/react-vis#599]
On https://uber.github.io/react-vis/documentation/series-reference/line-mark-series

find the url for "Scales and Data" under "Data Format" > "x"

it takes you to https://uber.github.io/react-vis/website/dist/scales-and-data.md which doesn't seem to be a valid page, I think the intended url is https://uber.github.io/react-vis/documentation/general-principles/scales-and-data

**Comment by Apercu** [comment]
Fixed! Thanks
