### ISSUE TITLE
Write better tests for interaction examples

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#611]
It seems like some of our tests are woefully lacking! It would be good if batch tests like interaction-examples tested the behaviour they described, as opposed to simple checks that they load. 

Further, it would be good if all of these examples which are meant to be shown in the docs pages appeared in the development environment/showcase so that they can be looked after.

**Comment by jckr** [comment]
I'm going to close this for now because we should rewrite the way interaction works anyway but I'm taking your point
