### ISSUE TITLE
Trouble with vertical bar series spacing

### ISSUE THREAD

**Issue by hansena** [uber/react-vis#612]
Hi folks, not sure if this is the correct forum for a question, but I'm having some difficulty with the vertical bar series chart when using string values on the x-axis.  I've set the xType to ordinal but the bars seem to be rendering on top of one another?  

![image](https://user-images.githubusercontent.com/15346521/30541434-67c89a66-9c49-11e7-8955-bba00fa49ec8.png)

I've recreated this issue on a fork of your code pen: https://codepen.io/vv1z/pen/oGbNKv?editors=1111
Any help would be greatly appreciated...

**Comment by mcnuttandrew** [comment]
Hey @hansena, Try moving the xType off of the individual series and onto the XYPlot ('<XYPlot xType="ordinal"...>...</XYPlot>').

**Comment by mcnuttandrew** [comment]
For an example of this technique in use check out https://github.com/uber/react-vis/blob/master/showcase/plot/bar-chart.js

**Comment by hansena** [comment]
That was it, thanks so much @mcnuttandrew !
