### ISSUE TITLE
Restrict stackBy when multiple series are present

### ISSUE THREAD

**Issue by LoicUV** [uber/react-vis#613]
I have a plot with 2 stacked vertical bar series and a line series. I'd like to be able to use the `stackBy` prop on the `y` axis only for the two bar series and not the line series, but since it's a prop of the plot it gets applied to the line series too. Is there a way to achieve this ?
See [this codepen](https://codepen.io/anon/pen/gGPOza)

**Comment by mcnuttandrew** [comment]
Hey @LoicUV,

I don't think there is a way to do this right now, however I think there easily could be! I imagine a prop added to each series called stack, that is a Boolean which is false by default. The behavior of the stacking algorithm would be such that, 

- if stack was present on any series it would only stack the series with the prop selected
- if stack is not present on any series it will try to stack all the series

I'm not available to do this work for a while, so I would encourage a PR!

**Comment by craigbeck** [comment]
+1 for this issue. I have something similar where I'm using a `LineSeries` to draw a cursor along the Y axis when mousing over the graph, but with `stacked` rendering of graph this line is also stacked.

line: 
![screen shot 2018-03-08 at 11 21 03 am](https://user-images.githubusercontent.com/1620605/37171463-d5a3d5c8-22c2-11e8-885f-a06ee62940fb.png)

stacked line showing hint cursor also being stacked:
![screen shot 2018-03-08 at 11 20 31 am](https://user-images.githubusercontent.com/1620605/37171482-e482df58-22c2-11e8-8049-af524eca6247.png)

**Comment by LoicUV** [comment]
@craigbeck It has been implemented, however it looks like [my changes on the documentation](https://github.com/uber/react-vis/pull/688/commits/71b972c8d78b635dfadce4438ea8972b591a301a) is missing in master. Can you look into this @mcnuttandrew ?

**Comment by craigbeck** [comment]
excellent thanks @LoicUV! updated to latest and it works great
