### ISSUE TITLE
XYPlot appears to require a consistant number of children

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#62]
For both area and line charts it appears that there is a render issue such that react-vis requries a consitant number of elements. For instance, say we were render three line series:

``
<XYPlot>
<series 1>
<series 2>
<series 3>
</XYPlot>
``
and then add grid lines

``
<XYPlot>
<grid>
<grid>
<series 1>
<series 2>
<series 3>
</XYPlot>
``

More likely than not series 3 would not appear

**Comment by bulyonov** [comment]
Fixed in #75
