### ISSUE TITLE
Responsive RadialChart  "react-vis": "^1.7.7"

### ISSUE THREAD

**Issue by PaulieScanlon** [uber/react-vis#620]
Hey, i can't seem to get a RadialChart to be responsive using the same technique as i've used for an XYPlot. Can you help please?

`const FlexibleRadialChart = makeWidthFlexible(RadialChart)`

              <Col xs={12} sm={12} md={12} lg={6}>
                <FlexibleRadialChart
                  height={400}
                  innerRadius={130}
                  radius={140}
                  showLabels
                  data={_categories}
                >
                </FlexibleRadialChart>
              </Col>

Am i missing something?

**Comment by simpleltcTerry** [comment]
What is the status of this issues? I think if XYPlot suppose nested, then this will be resolve

**Comment by devgibsonsp** [comment]
I see that this is an issue from a year ago. Was there any resolution to this? I am having the exact issue with the same chart.

**Comment by russellc92** [comment]
same issue, same chart here, any resolution?
