### ISSUE TITLE
Issue with Axis Ticks

### ISSUE THREAD

**Issue by iamcaleberic** [uber/react-vis#626]
Getting the following error on the LineSeries. I passing data that's updated constantly. The format never changes.

`Uncaught TypeError: Cannot read property 'ticks' of null`

**Comment by iamcaleberic** [comment]
The line series does not handle null values too well between updates. Ill go ahead and close this.

**Comment by mateuszzdyb** [comment]
i'd like to reopen it. it would be nice to have such feature build-in that if we have series with null values it does not crash the chart, but produce no line whatsoverer

**Comment by fifthanalytics** [comment]
> i'd like to reopen it. it would be nice to have such feature build-in that if we have series with null values it does not crash the chart, but produce no line whatsoverer

Hi! I'd like to offer up a solution that worked for me. In my VerticalBarSeries component, I had to move the <XAxis/> and <YAxis/> elements above the VerticalBarSeries. That worked for me, hope it helps. 

```
<XYPlot 
      margin={{left: 25, right: 25}}
      xType="ordinal"
      width={chartWidth}
      height={chartHeight}
      yDomain={[0, chartDomainBaths[1]+1]}
      >
      <ChartLabel  
          text="Average"
<XAxis/>
<YAxis/>
<VerticalBarSeries .....
```
