### ISSUE TITLE
Zoomable chart / xDomain chart overflow

### ISSUE THREAD

**Issue by acoll** [uber/react-vis#627]
When you use the xDomain to "zoom" in a chart, the path overflows the chart region.

Notice in the zoomable example:
https://uber.github.io/react-vis/examples/charts/zoomable-chart

![image](https://user-images.githubusercontent.com/1021013/30926468-434ed858-a383-11e7-848d-be3fefa21e52.png)

See on the left how the lines "overflow" into the y axis.

**Comment by targos** [comment]
I use the `Borders` component to fix this. Example:

```js
<XYPlot
    width={800}
    height={600}
    xDomain={xDomain}
>
    {series.map((serie) => <LineSeries
        key={serie.id}
        data={serie.data}
        color={serie.color}
    />)}
    <Borders style={{all: {fill: '#fff'}}} />
    <XAxis />
    <YAxis />
</XYPlot>
```

**Comment by acoll** [comment]
Cool. Yea that solves the problem for me.

Should we close this?

**Comment by toddmedema** [comment]
Following up here - ran into the same issue. Would be great to intuitively fix this rather than expect everyone to apply a hack :)

**Comment by notargetbg** [comment]
Using borders component didn't work for me. This issue is still ongoing...

**Comment by sharynneazhar** [comment]
The border hack worked for me but it matters where you place it in your code. Regardless, I do agree that there should be a better solution than this hack. 🙈 Perhaps a prop someone can pass in to enable or disable overflow?

**Comment by mcnuttandrew** [comment]
I would accept a PR adding a prop to the highlight component that constrains it to be within the margins. Something like stayInsideMargins={true/false}
