### ISSUE TITLE
Sankey Link Tooltips

### ISSUE THREAD

**Issue by awjreynolds** [uber/react-vis#631]
The sankey chart is useful however it would be good to be able to hover over a link and see a tooltip with some sort of display of the data. Being able to pass in a link tooltip function would be extremely useful.

**Comment by mcnuttandrew** [comment]
Hey @awjreynolds, It should be relatively easy to add a call backs for link. I would encourage you to open a PR to that effect! In order to maintain consistency across the library you'd probably want to add three onLinkClick/onLinkMouseOver/onLinkMouseOut.

**Comment by stu-harvey** [comment]
@mcnuttandrew I went ahead and added those event handlers because I need them for a similar purpose. Would appreciate a review on the PR

**Comment by awjreynolds** [comment]
@mcnuttandrew I was trying to get Hints working with the Sankey but I'm unsure if I'm approaching this right. However I do not understand how the hint is not working giving that the underlying component is XYPlot.
`
const { hoveredValue } = this.state;

<Sankey
        nodes={this.state.data.nodes}
        links={this.state.data.links}
        width={1500}
        height={this.state.data.nodes.length * 35}
        onValueClick={this.showDataPoint}
        onValueMouseOver={this.showDataPoint}
        onValueMouseOut={this.showDataPoint}
        hasVoronoi={true}
      >
        {hoveredValue ? 
          <Hint value={hoveredValue}>
            <div style={{background: 'black'}}>
              <h3>Value of hint</h3>
              <p>{hoveredValue.value}</p>
            </div>
          </Hint> : null}
      </Sankey>`

**Comment by mcnuttandrew** [comment]
@awjreynolds  I'm not sure, but i'm betting some of your issue is being cause by

        onValueMouseOver={this.showDataPoint}
        onValueMouseOut={this.showDataPoint}

If you wanna spin up a code pen i'd be happy to take a look

**Comment by chlumper** [comment]
@awjreynolds I extended the Sankey diagram to allow rendering of children within the XYPlot in my PR #648. The PR also adds a showcase example for the usage of a Hint in combination with the Sankey diagram (It shows the Hint on hover of a link).

See: https://github.com/chlumper/react-vis/blob/10e4a4f0cb06e81990b0c06136964f790daf1c76/showcase/sankey/link-hint.js

I hope the PR will find its way into the next release and it helps solving your problem.

**Comment by mcnuttandrew** [comment]
Now that #648 is merged in, i think this issue is now addressed. @awjreynolds has this addressed your issues?

**Comment by mcnuttandrew** [comment]
I'm going to close this, but @awjreynolds if your issues are unaddressed feel free to reopen
