### ISSUE TITLE
Typescript Definition File for the library.

### ISSUE THREAD

**Issue by awjreynolds** [uber/react-vis#636]
I have searched for and not found a typescript definition file (d.ts) for this library. 

Is there one in the pipeline? I've created a horrible stub for now, but if I get the chance I will tidy it up and produce a PR.

**Comment by zfranklyn** [comment]
I'd love to contribute to this if someone's working on this. Would love a Typescript def file for this library!

**Comment by codepressd** [comment]
Any word on this? I'd be super stoked!!

**Comment by Fles** [comment]
still nothing?

**Comment by vdelacou** [comment]
I write a first version, but still need a lot of work (eg: delete all any an write the correct type) 

https://gist.github.com/vdelacou/c7025196695148da33b3ee1a0efacdf1

**Comment by xogeny** [comment]
@btford or @mcnuttandrew Would you accept a pull request for this? (i.e., keeping a `.d.ts` file in the `react-vis` repo)?

**Comment by mcnuttandrew** [comment]
I would welcome a PR to this effect. I am not familiar with typescript, so it would be good if you could include some resources on how to review the PR along the PR 😬😬😬😬.

**Comment by xogeny** [comment]
I would propose we take @vdelacou's version as a starting point and iterate on it.  We could add some tests as we go based on examples, etc. to ensure the typings matched up.

@Fles, @codepressd , @zfranklyn @awjreynolds are you interested in participating?

Seems like the simplest thing would be to fork the repo and work on the typings in the fork and then submit a PR to merge it all when we are reasonably happy with it.  Comments?

**Comment by xogeny** [comment]
Well, it seems others have lost interest (?).  I have a project where I plan to use `react-vis` with TypeScript.  My current plan is to use @vdelacou's typings and then refine them as I need to.  If I think the result is reasonable, I will submit a PR back here to fold in whatever I have back into this project.  This assumes (perhaps incorrectly) that I will have the proper time to do this.  I'll try, but not promises.

**Comment by Domino987** [comment]
I use the typescript definition mentioned by @vdelacou and improved it a but t it still needs all lot of anys replaced. I create a merge request to add the first version to the repository #850 so that hopefully it will be improved.

**Comment by evgsil** [comment]
My version (still in progress):
https://gist.github.com/evgsil/783967090f6741139c97c45ef3b6a30c

**Comment by dtimm** [comment]
heads up @evgsil made a repo under the MIT license with the typings from that gist.
https://github.com/evgsil/react-vis-typings

**Comment by evgsil** [comment]
I've submitted pull request https://github.com/uber/react-vis/pull/1003 that should add generate-types.js to this package.

**Comment by agwells** [comment]
It's probably worth mentioning here that #1003 was closed in favor of submitting some type definitions to Definitely-Typed: https://github.com/uber/react-vis/pull/1003#issuecomment-500028248

As mentioned on that thread, @fstylermiller has started a repo to work on a Definitely Typed pull request: https://github.com/fstylermiller/DefinitelyTyped

**Comment by mcnuttandrew** [comment]
there is now a typescript definition file on definitely typed! install it now via @types/react-vis big credit to @evgsil for the types
