### ISSUE TITLE
Space left at the top of Partition Treemaps

### ISSUE THREAD

**Issue by mrawdon** [uber/react-vis#639]
There is always space left at the top of the treemap of a partition treemap for the root node.

![image](https://user-images.githubusercontent.com/1678756/31464708-300d8b68-aea0-11e7-8c02-987eb6fd9086.png)

This is caused by skipping the root node in the following code.
https://github.com/uber/react-vis/blob/master/src/treemap/treemap-dom.js#L34
and
https://github.com/uber/react-vis/blob/master/src/treemap/treemap-svg.js#L95

The easiest solution here would just be to display the root node like for circle packing.
To keep this from altering existing functionality exposing a prop would work.

Another option is to hide the root when its just a container for children.  That is discussed in this stackoverflow question, https://stackoverflow.com/questions/28700591/is-it-possible-to-have-multiple-parent-root-nodes-in-a-d3-icicle-plot

I can put a PR together for either option, just wanted to discuss first

**Comment by mrawdon** [comment]
@mcnuttandrew any thoughts on this one?  Thanks

**Comment by mcnuttandrew** [comment]
I guess i'd be push for displaying the root node by default, and adding a prop to turn it off (ala the opposite of how it is on sunburst). I think such a change would have a minimal impact on the rest of the code base.

**Comment by mrawdon** [comment]
Makes sense, I'll put a PR together for this soon
