### ISSUE TITLE
Multiple YAxis' on a Chart

### ISSUE THREAD

**Issue by Srirangan** [uber/react-vis#642]
I'm trying to implement a composite chart of a line series and bar series.

Their data share's the x-axis but the y-axis differs.

Is there's a way to plot both series in a single chart with multiple y-axis?

**Comment by antoinecollas** [comment]
I think this issue can help you: #388

**Comment by antoinecollas** [comment]
#388

**Comment by mcnuttandrew** [comment]
@Srirangan did #388 end up being sufficient help to answer your question?

**Comment by Srirangan** [comment]
Yep

**Comment by ayepRahman** [comment]
@srirangan may I know which solution you when up using for multi-axis?
