### ISSUE TITLE
Memory usage increases over time

### ISSUE THREAD

**Issue by CharukaK** [uber/react-vis#644]
Hi,

I'm thinking of using react-vis to create a real-time dashboard with the initial tests I have done I noticed that the memory usage increases with time with about 8 charts running parallel each with different data sets constantly updating every one second, the data set length always kept constant. Is this an issue with the constant updating of charts or is there a way to achieve real-time charts?

Thanks

**Comment by mcnuttandrew** [comment]
Hey @CharukaK,

I haven't seen that behaviour and have made some pretty data dynamic charts. Would you mind seeing if you can reproduce this in a code pen environment?  In the mean time, it is worth noting that SVG can be kinda hard on the browser if you have a lot of it. Check out the canvas series for potential fixes?

**Comment by mcnuttandrew** [comment]
I haven't really heard other issues about this, so I'm going to close this, but feel free to re-open if you want
