### ISSUE TITLE
Sorting bar chart

### ISSUE THREAD

**Issue by Matthijn** [uber/react-vis#645]
I'm not quite sure (or is it possible) to sort information on a bar chart. I have my data in the {x: y:} format in an array and can draw a nice bar chart. But changing the order in my data array does not change anything in the bar chart itself. 

I am looking to build something like this: https://bl.ocks.org/mbostock/3885705 but there it is animated, and that is not really necessary for me.

**Comment by crotundu** [comment]
> This quantity is treated as a category (at least in VerticalBarSeries) and so considers the exact left-right positioning to be not that important (which is something to watch out for if you are providing exact numbers, in such a case it is better to the rect-series).

Got it from [BarSeries documentation](https://github.com/uber/react-vis/blob/master/docs/bar-series.md)

**Comment by mcnuttandrew** [comment]
@Matthijn did that documentation solve your problem or is there something additional your referring to?

**Comment by Matthijn** [comment]
I solved it by keeping track of a "sortIndex" property on my data and using that as the x property.
