### ISSUE TITLE
Legend Items are always "clickable"

### ISSUE THREAD

**Issue by sjbrown** [uber/react-vis#647]
https://github.com/uber/react-vis/blob/ec1ed9f9b9dc140c1ee1d53292e51f31f99161a1/src/legends/discrete-color-legend-item.js#L38

I think you've got a bug here.  `onClick` is a function, so it's always "truthy".  Thus this `clickable` class always gets added.

I suggest fixing this over here:
https://github.com/uber/react-vis/blob/ec1ed9f9b9dc140c1ee1d53292e51f31f99161a1/src/legends/discrete-color-legend.js#L50

By only conditionally passing in a function, otherwise path in something "falsy"

**Comment by mcnuttandrew** [comment]
Good catch! discrete-color-legend's default value for onItemClick is what's causing the trouble. I would accept a PR that removes default from discrete-color-legend and does a presence check on discrete-color-legend-item. 

Probably would also require writing a test so that we don't backslide.

**Comment by brandonmp** [comment]
oh it's a bug! I just thought it was a weird default behavior.
I've been using this to de-clickable them w styled-components:

```
 .rv-discrete-color-legend-item {
        cursor: default;
        &:hover {
            background: unset;
        }
    }
```
