### ISSUE TITLE
Stylesheet inclusion check fails on Firefox in dev environment

### ISSUE THREAD

**Issue by stropitek** [uber/react-vis#650]
I get a security error in Firefox when using react-vis.
![screen shot 2017-11-02 at 2 36 58 pm](https://user-images.githubusercontent.com/4118690/32328778-5551232a-bfdb-11e7-847e-49b6bff87778.png)

The error occurs when I develop using webpack-dev-server. Firefox throws a security error because react-vis (loaded from localhost:8080) is trying to access a stylesheet that was loaded from a different origin (I'm including semantic-ui css from a cdn). The line that throws is [that one](https://github.com/uber/react-vis/blob/3be2bec66d14ce3079c9fc0d181d3542234ee352/src/utils/react-utils.js#L88). The error does not exist in the production bundle because that check is removed.

I'm not sure what the fix should be. Try-catching that line would not solve the underlying issue but would at least prevent the page to crash in those circumstances.

**Comment by mcnuttandrew** [comment]
Huh, that's annoying. I'm not quite sure what a good workaround would be, maybe a minimal solution would involve adding a prop to XYPlot like "skipStylesheetCheck" that would skip the stylesheet check? If you wanted to file a PR to that effect I'd gladly accept it.

**Comment by tux4** [comment]
Hi,
I am facing this exact same issue. It is preventing me from working on `react-vis` in firefox. A quick way of reproducing this would be to try this:

```
document.styleSheets[0].cssRules
```

Which throws:

```
SecurityError: The operation is insecure.
```

@stropitek Have you managed to fix this? If not, I can make a PR, as @mcnuttandrew suggested.

**Comment by stropitek** [comment]
@tux4 I haven't started to work on this. Feel free to do the PR

**Comment by mcnuttandrew** [comment]
I'm going to close this as #658 has landed and appears to address this issue. Feel free to re-open if you feel otherwise.
