### ISSUE TITLE
Confused by Rect Series documenation

### ISSUE THREAD

**Issue by FinalChaos** [uber/react-vis#656]
I see the phrase "RectSeries isn't meant to be used directly," in the documentation. But I need to do width customization for bar series as per: https://github.com/uber/react-vis/issues/67.

I also see other comments: "RectSeries can be used to build histograms, icicle charts, or anything really where both height and width matter."

So is it a "bad practice" to use RectSeries directly?

**Comment by brandonmp** [comment]
Maybe it means you ought to use `HorizontalRectSeries` or `VerticalRectSeries` instead?


here's a few examples of a histo from docs:

https://github.com/uber/react-vis/blob/3be2bec66d14ce3079c9fc0d181d3542234ee352/showcase/plot/histogram.js

https://github.com/uber/react-vis/blob/3be2bec66d14ce3079c9fc0d181d3542234ee352/showcase/plot/stacked-histogram.js


Note that I think the docs are wrong, in that x0/y0 mark the beginning of a rect, and x/y mark the end (the docs IIRC mix those up)

**Comment by jckr** [comment]
thanks for pointing that out. 
Yeah what the docs mean is that we assume people will use HorizontalRectSeries / VerticalRectSeries which are a tiny wrapper around RectSeries, rather than RectSeries directly. However, there's nothing wrong with using RectSeries directly.

**Comment by FinalChaos** [comment]
Thanks that makes sense. Appreciate the answers.
