### ISSUE TITLE
Does react-vis support scale breaks?

### ISSUE THREAD

**Issue by JarLowrey** [uber/react-vis#668]
[More info](https://ux.stackexchange.com/questions/36408/how-to-visualize-data-with-extreme-value-differences)

**Comment by mcnuttandrew** [comment]
React-vis *does not* support scale breaks. This affect can be achieve through some hack and slashing by combing two different XYPlots, one with the top domain and one with the bottom. 

However, I'd strongly caution you against this type of graph: it tends to be pretty dishonest and misleads the viewer about the nature of the information being presented, as it will appear to them that points above and below the break are on the same (unbroken) axis. Check out the wikipedia article about it https://en.wikipedia.org/wiki/Misleading_graph#Truncated_graph !

**Comment by JarLowrey** [comment]
Thanks!
