### ISSUE TITLE
react-vis is no longer compatible with 0.14.x

### ISSUE THREAD

**Issue by chrisirhc** [uber/react-vis#673]
In peerDependencies we're indicating compatibility with 0.14.x but we're not, due to our use of `PureComponent`:

![image](https://user-images.githubusercontent.com/132584/33505437-25e14d8c-d6a0-11e7-9337-78bf7de8c319.png)

See https://github.com/uber/react-vis/commit/b0f386f027a9ceaa2874e8bbc8c52acf3b5e4c1b#r25990797 .

Users might see an error like:
`Uncaught TypeError: Super expression must either be null or a function, not undefined`

https://github.com/uber/react-vis/blob/8ac25342d31ed339ad717b7045cc908a0c1ba1a5/package.json#L83-L85

**Comment by akre54** [comment]
Should we drop 0.14 then? Seems reasonable to me.

**Comment by ericsoco** [comment]
Definitely.
But I think the main question is how to handle versioning.
That's a breaking change, but it's already broken in the current version.
So maybe this is just a minor bump? Or maybe even a patch?

**Comment by akre54** [comment]
The most semver-ish way is to create a patch version with a rollback for the breaking change, then move the old change and new peerDependencies to a major version bump.

Personally I think semver is broken for many reasons like this, and we'd probably do fine with just a minor bump.

**Comment by jckr** [comment]
we're now a few minor versions deep since this issue, we should just update the peerDependency to 15.3.0 for next release

**Comment by jckr** [comment]
fixed with 1.9.2
