### ISSUE TITLE
Simple Chart copied from examples appears different

### ISSUE THREAD

**Issue by deehuey** [uber/react-vis#674]
Hey! I've implemented react-vis in our application, and the outcome, while copied exactly as some of the examples, appears entirely different.

Any clue / leads as to why? The XAxis, YAxis aren't rendering, and then line mark series are filling between the lines with black.

![image](https://user-images.githubusercontent.com/29404735/33528999-ef21a3b6-d837-11e7-9baf-ea5339dbd6f0.png)

```javascript

const data = [
  {x: 0, y: 8},
  {x: 1, y: 5},
  {x: 2, y: 4},
  {x: 3, y: 9},
  {x: 4, y: 1},
  {x: 5, y: 7},
  {x: 6, y: 6},
  {x: 7, y: 3},
  {x: 8, y: 2},
  {x: 9, y: 0}
];
            <FlexibleWidthXYPlot height={400}>
              <XAxis />
              <YAxis />
              <VerticalGridLines />
              <HorizontalGridLines />
              <LineMarkSeries color="#35ab4c" strokeWidth={5} data={data} />
            </FlexibleWidthXYPlot>
```

**Comment by deehuey** [comment]
Codepen works fine for me, but in my app it seems to be quite broken!

**Comment by balthazar** [comment]
Look at your console, a warning should be present telling you that you forgot to include the stylesheet 🙂

**Comment by deehuey** [comment]
Interesting, I don't see a notification / error in the console for this. Thanks, I'll take a look.

**Comment by balthazar** [comment]
Then something might be wrong with #667, unless you're using an older version?

**Comment by deehuey** [comment]
The fix worked, just didn't see the error in the console. Thanks =) I'll make sure I'm on latest too, but I did just `npm install` yesterday so I'm assuming I should be.

**Comment by balthazar** [comment]
Which browser and exact version of `react-vis` are you using?
