### ISSUE TITLE
Documentation : Difficult to find source code for examples

### ISSUE THREAD

**Issue by krabbypattified** [uber/react-vis#676]
The documentation for react-vis provides many great examples:

![screen shot 2017-12-03 at 5 06 33 pm](https://user-images.githubusercontent.com/13423815/33530355-585d3a84-d84c-11e7-9123-ff9e3d080733.png)

![screen shot 2017-12-03 at 5 14 06 pm](https://user-images.githubusercontent.com/13423815/33530434-6524cb28-d84d-11e7-8c5d-492b7597330b.png)

However, it is difficult to locate the source code for these examples (so I can recreate something like it).

Can react-vis provide a simple explanation (ie [here](https://uber.github.io/react-vis/documentation/welcome-to-react-vis)) or mechanism for viewing the source code of a arbitrary example, (ie a "view code" button) or even a CodePen?

**Comment by krabbypattified** [comment]
My apologies if I missed anything obvious.

**Comment by mcnuttandrew** [comment]
Hey @krabbypattified 

I filed some changes yesterday that I think should address this issue! It is now the case that every live example has a documentation link attached to it. This obviously isn't perfect, but it makes it way easier to get to the code for the example. Excited to hear any comments you might have on the manner.

**Comment by krabbypattified** [comment]
Thanks, I'm loving the new feature! But I do see what you mean, it's obviously not perfect 🤷
![capture](https://user-images.githubusercontent.com/13423815/34022937-4675da2a-e110-11e7-838e-dc8fb0cdbb5f.PNG)

**Comment by mcnuttandrew** [comment]
Yea, I borked up some stuff when I was doing it, itll be fixed soon. Marking this as resolved as #693 is covering the broken showcases directly.
