### ISSUE TITLE
Inconsistent xDomain rendering

### ISSUE THREAD

**Issue by Falieson** [uber/react-vis#679]
I have 2 graphs, one above the other, as demonstrated here: https://www.webpackbin.com/bins/-L-YaM--lR20uaHPtRuG

Even though both graphs have the same xDomain, the xDomain renders differently. 
- Data1:  {xRange: "{"max":1512417540000,"min":1512403200000}"} {yRange: "{"max":95,"min":50}"}
- Data2:  {xRange: "{"max":1512417540000,"min":1512403200000}"} {yRange: "{"max":175,"min":115}"}

The first graph perfectly fits the data between 8am-12pm, while the second graph shoes time before 8am and after 12am on the xAxis.

I want both of the graphs to render with the data fit to the graph, thanks for your help

**Comment by jckr** [comment]
Link doesn't work anymore, so I'm going to assume this is related to VerticalBarAeries, which is the series which would position 2 set of marks with the same x values differently on the x axis. 
By default bar charts appear clustered
![screenshot 2018-03-19 09 34 16](https://user-images.githubusercontent.com/9727630/37608802-b886428e-2b58-11e8-8317-81ee617f025c.png)
so if there are several bar series each will share a "slot" on the x axis and appear from left to right.
To disable that behavior you can set cluster to false in the props. 

Will close now but if that doesn't address the issue please copy paste code?
thanks!
