### ISSUE TITLE
Custom SCSS import: Warning about missing stylesheets

### ISSUE THREAD

**Issue by texttechne** [uber/react-vis#683]
While it's a cool feature to warn new users about missing stylesheets, it bites me a 2nd time (see #682). I import only the needed stylesheets in my main.scss file. Although everything works fine and is setup correctly I get the warning about missing stylesheets, because of these "magic lines":
```
.react-vis-magic-css-import-rule {
  display: inherit;
}
```
This code is buried in react-vis' main scss file, which I don't want to import.
So, I'm left to live with this incorrect warning (bad habit: devs soon start to ignore all kinds of warnings) or reproduce these lines in my code. However, this is internal code which shouldn't leak  into user land: You wouldn't be free to change this code then without breaking client code....

**Comment by jckr** [comment]
will try to tackle this in response to #725
