### ISSUE TITLE
can't get the cursor position in parameter events of callback function onValueMouseOver

### ISSUE THREAD

**Issue by TangiDing** [uber/react-vis#687]
As the title says, i want to get the position of cursor in onValueMousOver, when i access the clientX of events, i get null,  the need is when the mouse over the series,  it shouild occur a tip with the series message on the series, my english is poor, i hope this helpful

**Comment by jckr** [comment]
thank you for the issue, will investigate

**Comment by jckr** [comment]
Hi, take a look at this pen: 
https://codepen.io/jckr/pen/dmpWzK

that's one way to do it:
<MarkSeries ... onValueMouseOver={(d, {event}) => {const clientX = event.clientX; ...}} />
