### ISSUE TITLE
Add radiusDomain to ArcSeries docs

### ISSUE THREAD

**Issue by mmende** [uber/react-vis#691]
Please add the radiusDomain prop to the documentation for ArcSeries. It took me ages to find out why my graph would always render from the center and not from radius0 as expected. Nonetheless thanks for these beautiful components.

**Comment by mcnuttandrew** [comment]
Hey @mmende,
I think the best documentation tends to come from when you find the solution to a tough problem. If you wanted to write up a modification to the docs that would have helped you not get in the pickle you ended up in, I would certainly accept it.

**Comment by mcnuttandrew** [comment]
I added some documentation that I hope will help! Let me know if the above PR is sufficent. Closing for now
