### ISSUE TITLE
Examples in documentation don't show up anymore

### ISSUE THREAD

**Issue by aaronang** [uber/react-vis#693]
When you go to https://uber.github.io/react-vis/examples/showcases/plots, it will just show a blank page as shown below.

![image](https://user-images.githubusercontent.com/7579804/34008724-2881338e-e0bb-11e7-9788-12d09d5900fc.png)

The error message in Chrome DevTools' console is:

```
Failed to load resource: the server responded with a status of 404 ()
```

**Comment by mcnuttandrew** [comment]
Should be resolved now, sorry about that
