### ISSUE TITLE
Unknown plugin "module-resolver" 

### ISSUE THREAD

**Issue by Olian04** [uber/react-vis#700]
I'm getting this error:

```
.../node_modules/react-vis/dist/index.js: Unknown plugin "module-resolver" specified in 
".../node_modules/react-vis/package.json" at 0
```

__Versions:__ 
npm: 5.5.1
react-vis: 1.8.0
react: 16.2.0
parcel-bundler: 1.2.0

**Comment by balthazar** [comment]
Hi!

Do you have a more complete stacktrace you could share on pastebin maybe? By looking at the bundled [index.js](https://unpkg.com/react-vis@1.8.0/dist/index.js) I don't see any reference to this. Not sure if parcel-related?

**Comment by Olian04** [comment]
@balthazar 
![image](https://user-images.githubusercontent.com/5493406/34176526-795baade-e500-11e7-9b8d-899158e767a2.png)

**Comment by Olian04** [comment]
@balthazar That exact error was thrown when i copied over the example from [here](https://github.com/uber/react-vis/blob/master/docs/sankey.md).

**Comment by balthazar** [comment]
Are you using aliases or links?

**Comment by Olian04** [comment]
@balthazar not to my knowledge.

**Comment by balthazar** [comment]
And `babel-plugin-module-resolver` is not installed in your dependency tree?

**Comment by balthazar** [comment]
Can you try installing it as a temporary workaround? We might want to switch it to a core dep instead of a dev one, weirdly we didn't got the issue before.

**Comment by Olian04** [comment]
@balthazar I installed it as a dep, and then i get this: 
![image](https://user-images.githubusercontent.com/5493406/34177402-c0a8b78a-e503-11e7-8276-46a37fc92169.png)

**Comment by Olian04** [comment]
@balthazar  And adding that dep gives me the same error but for `stage-0`. I'm guessing it will keep going...

**Comment by balthazar** [comment]
Looks like because it's seeing these in the babel config of the package it automatically requires them, even if the dist is already built and shouldn't require them. Can you instead remove this prop from the package and see how that goes?

**Comment by Olian04** [comment]
@balthazar Ohhh... if that's the case then this might actually be a parcel error. I had a discussion over there about just that earlier today. https://github.com/parcel-bundler/parcel/issues/351

**Comment by jckr** [comment]
we will close this for now

**Comment by mathewleland** [comment]
@Olian04 Were you able to resolve this issue?  I am running into the same issue with webpack, and am not having any luck...

**Comment by Olian04** [comment]
@mathewleland I wasn't. I decided not to use react-vis

**Comment by dockwarder** [comment]
I got the same error
Fixed it with manually installing `babel-plugin-module-resolver` as dev dependency

**Comment by balthazar** [comment]
https://github.com/uber/react-vis/blob/master/package.json#L65 the dependency is already in the `package.json`. Have you tried installing the dependencies using `yarn` instead of `npm`?

**Comment by jamesawer3** [comment]
@balthazar Still getting the same issue
