### ISSUE TITLE
Is there a way to create a Spaced Clustered Vertical Stacked Bar with 'Hierarchical' X axis labeling 

### ISSUE THREAD

**Issue by FinalChaos** [uber/react-vis#707]
I want to create something like this.

![image](https://user-images.githubusercontent.com/27317754/35003008-52641230-faa0-11e7-871d-990db153ebf7.png)

  Similar to Vertical stacked bar graph with clusters
  Cluster value would be "Divison A", "Divison B", "Division C"
  Y values are stacked as represented by the different colored bar segments
  X - ordinal values are the dates (correspond to weeks)
  
  Key difference are:
  1) Want spacing between each cluster bar for a given x ordinal value
  2) Want a hierarchical labeling along the x - axis with each cluster value visible "Division A" etc but also 
      want the X ordinal values labels to the "encompass" the cluster values "December 22 2017" etc.

**Comment by aaronmagi** [comment]
+1 for wondering how this would be done.

**Comment by jckr** [comment]
we don't have a high-level way to do that. 

however, with tickValues and tickFormat, and possibly several XAxis components, you could do that.

let's suppose your bars have an x value from 0 to 8. so [{x: 0, y: ...}, {x: 1, y: ...}, etc.]

you could have:
<XAxis tickValues={[0, 1, 2, 3, 4, 5, 6, 7, 8]}
  tickFormat={d => ['Division A', 'Division B', 'Division C'][d % 3]}
/>
<XAxis tickValues = {[1, 4, 7]}
  tickFormat={d => ['December 22 2017', 'December 29 2017', 'January 5 2018'][(d - 1) / 3 % 3]
/>

Here I'm using % as a hacky way to create a function that would transform the tick values into the desired label. 
If you have the data set accessible as an array and the division name or the date are present it could be something like

tickFormat={d => data[d].division} 

hope it helps
