### ISSUE TITLE
Does react-vis support live streaming via calling external API

### ISSUE THREAD

**Issue by VineethArvindFluke** [uber/react-vis#710]
Does react-vis support live streaming via calling external API.
Like using API result and then plotting graph.

**Comment by wzup** [comment]
16 days and no answer? Looks like this lib is as bad as Uber itself

**Comment by akindr** [comment]
react-vis doesn't have built-in data fetching solutions. It is fairly easy to add a surrounding component to handle that, which could update the data being fed into the chart. The visualizations do a good job of keeping the existing line in place and not re-rendering the entire line with each data update.
