### ISSUE TITLE
TickValues not seem to render properly

### ISSUE THREAD

**Issue by andylaci** [uber/react-vis#712]
This is what I get 
![image](https://user-images.githubusercontent.com/7139923/35628044-04588a92-069b-11e8-8688-a7b4beb9e7ad.png)

my code looks like this:

          <YAxis
            style={{
              line: { stroke: 'none' },
              text: {fontSize: '15px'}
            }}
            tickSize={4}
            tickValues={['0-17','18-25','25-30','30-45']}
            tickFormat={value => value}
          />

error from console is:

![image](https://user-images.githubusercontent.com/7139923/35628104-2de80b9e-069b-11e8-9cb8-2ee93969ba84.png)

am I missing something, or it is bug?

**Comment by timplode** [comment]
I had the same problem. It appears that Axis tickValues does not support anything than tick positions (0,1,2,...). I was able to work around it by making a mapper function. Its definitely not pretty but it gets around this limitation.

```
constructor(props) {
        super(props);
      
        this.state = {
            x_tick_values: ['0-17','18-25','25-30','30-45']
        };
    }

    tickMapper(v) {
        return(
            <tspan>{this.state.x_tick_values[v]}</tspan>
        );
    }


    render() {
        return(
            <YAxis
                tickFormat={v => this.tickMapper(v)}
            />
        );
    }
```

**Comment by jckr** [comment]
tickValues represents where your tick should be placed. 
tickFormat is what controls what is being displayed. 

so you may want to do something like: 
tickValues={[0, 1, 2, 3]}
tickFormat={d =>  ['0-17','18-25','25-30','30-45'][d]}
