### ISSUE TITLE
jest snapshots "Cannot read property 'offsetHeight' of undefined"

### ISSUE THREAD

**Issue by sakulstra** [uber/react-vis#713]
When trying to use this library inside jest snapshots I face a problem regarding https://github.com/uber/react-vis/blob/b882563d8d93d459d08973fdd156148ffe129475/src/make-vis-flexible.js#L126
```
[1]     TypeError: Cannot read property 'offsetHeight' of undefined
```
which i think is somehow related to react-test-renderer not working well with findDomNode
I think it would be enough to check it before destructuring via `if(!containerElement) return;` - not sure if this is a proper fix, though.

**Comment by jckr** [comment]
we're going to deprecate makeVisFlexible so that should make the problem go away
