### ISSUE TITLE
Animation prop for Sankey?? Does it exists anyway?

### ISSUE THREAD

**Issue by wzup** [uber/react-vis#715]
Your API doesn't have `animation` prop for Sankey.

However you use `animation` prop in your examples (https://github.com/uber/react-vis/blob/master/showcase/sankey/energy-sankey.js#L36)

![sankey_animation](https://user-images.githubusercontent.com/3880497/35768549-249d685a-0906-11e8-9981-41ac3882799e.png)

Question is simple, does the prop exist or not? Does it do something or was it just a typo in your code examples?

**Comment by mcnuttandrew** [comment]
Hey @wzup,

You highlight another oversight in the docs. Animation is a completely valid prop to pass the sankey diagram, however we must have missed documenting it. You can checkout the animation docs for more information https://uber.github.io/react-vis/documentation/general-principles/animation
