### ISSUE TITLE
Module not found: Error: Can't resolve 'plot/hint' for Sankey

### ISSUE THREAD

**Issue by wzup** [uber/react-vis#716]
What error is that?
```
Module not found: Error: Can't resolve 'plot/hint'
```
Why do you have it in your examples but throws?
```
import Sankey from 'sankey';
import Hint from 'plot/hint';
```

**Comment by mcnuttandrew** [comment]
Hey @wzup,

Those examples are making use of the directory structure from inside of the package. If you want to access sankey/hint you can import them from react-vis, vis:

```
import {
Sankey,
Hint
} from 'react-vis'
```

But you make a good point, the example should be converted so that they can all be be plug and play
