### ISSUE TITLE
[question] can react-vis do geolocation based visualization?

### ISSUE THREAD

**Issue by syang** [uber/react-vis#719]
I am going to do something like this see [a similar geo-based visualization effect I want to achieve](http://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/13/d3_azure_search_interactive_visualization.png)

![data viz on a map](http://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/13/d3_azure_search_interactive_visualization.png "Logo Title Text 1")

I have I don't see the use case on the [react-vis demo page](https://uber.github.io/react-vis/) though, not sure if react-vis could provide some out-of-box solution for React integration for such use case or if I should be using d3 directly.

**Comment by BertCh** [comment]
not react-vis but there is another react-based, modular and composable data visualization library open sourced by Uber that is focused on geospatial data.

this example comes to mind based upon your pic:
https://uber.github.io/deck.gl/#/examples/core-layers/arc-layer

**Comment by jonsadka** [comment]
@syang there is also https://uber.github.io/react-map-gl/

**Comment by jckr** [comment]
you could do that with react-vis if you really wanted to, but it would be very cumbersome. states could be done through the svg series, circles through the mark series and lines, with the line series. It is definitely not what react-vis is good at, contrary to deck.gl / react-map-gl libraries highlighted by Robert and Jon.
