### ISSUE TITLE
DOMException SecurityError (code 18) checkIfStyleSheetIsImported

### ISSUE THREAD

**Issue by vasymus** [uber/react-vis#725]
react-vis/es/utils/react-utils@checkIfStyleSheetIsImported

checking of importing of react-vis styles
via
var CSSRulesList = styleSheet.rules || styleSheet.cssRules

it's better to check via
document.styleSheets[i].hasOwnProperty('rules')
and
document.styleSheets[i].hasOwnProperty('cssRules')

otherwise,
the DOMException https://developer.mozilla.org/en-US/docs/Web/API/DOMException SecurityError (code 18) would be in CHROME (windows 10, Version 64.0.3282.167 (Official Build) (64-bit))
if there will be any of <link/> or <style/> tags appended to <head> by other plugins do not have this properties
(like, in my case, was https://github.com/tomchentw/react-google-maps, that append to <head> google-fonts <link/>)

for now if fixed it via changing prototype of component where it was used

`
XYPlot.prototype.componentDidMount = function () {
    try {
        checkIfStyleSheetIsImported()
    } catch (err) {
        console.warn(err)
        console.warn('most likely the problem is because of accessing document.styleSheets[i].rules or document.styleSheets[i].cssRules')
        console.warn('the right way is, e.g., document.styleSheets[i].hasOwnProperty("rules")')
    }
}
`

but it would be better if you change the react-vis/es/utils/react-utils@checkIfStyleSheetIsImported

**Comment by mcnuttandrew** [comment]
Hey @vasymus 
Thanks for digging into this. I know some other folks have seen similar bugs and this sounds like you have a hold on a solution. I would gladly accept a PR that executed this change.

**Comment by vasymus** [comment]
Hi!

Year, sure!

but very busy right now :-(

I think i'll make the PR at this holidays


>Воскресенье, 18 февраля 2018, 23:06 +02:00 от Andrew McNutt <notifications@github.com>:
>
>Hey  @vasymus
>Thanks for digging into this. I know some other folks have seen similar bugs and this sounds like you have a hold on a solution. I would gladly accept a PR that executed this change.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Vasil Zchdankin6

**Comment by jckr** [comment]
I'll write that PR. thanks

**Comment by JFernandoGomez** [comment]
What's the status on this PR ?

**Comment by jckr** [comment]
@JFernandoGomez I'm going to publish a new version today.
