### ISSUE TITLE
Ability to supply class prefix?

### ISSUE THREAD

**Issue by rauchg** [uber/react-vis#73]
It'd be cool to be able to isolate the CSS classes with a prefix of our choosing.
Is this something you'd be interested in incorporating if we submit a PR?

**Comment by chrisirhc** [comment]
Yes, this makes sense.
Is there a plan of implementation you had in mind? Perhaps adding a prop for customizing the prefix?

**Comment by rauchg** [comment]
Yep. Said prop would be passed down if necessary (if sub-components that use classes are involved)

**Comment by samhogg** [comment]
@rauchg @chrisirhc was there any progress here?

I'd be interested in the same functionality, happy to contribute a PR.

**Comment by mcnuttandrew** [comment]
Out of curiosity: most of the components in react-vis now support a className prop, what's the utility of being able to supply a prefix vs just providing a className?

**Comment by Apercu** [comment]
Would having a top class on all our components that create a css namespace so to speak resolve the problem too instead of hacking a prefix in all our classNames?

**Comment by samhogg** [comment]
Probably, yes! I suspect that could be solved in conjunction with #242?

**Comment by Apercu** [comment]
Indeed 😃

**Comment by samhogg** [comment]
@Apercu @mcnuttandrew - would you accept a PR to add a `className` prop to the top level `XYPlot` and `RadialChart`? Those are the main gaps for me at the moment.

**Comment by mcnuttandrew** [comment]
100% would accept

**Comment by samhogg** [comment]
@mcnuttandrew this can probably be closed.

**Comment by mcnuttandrew** [comment]
I agree!
