### ISSUE TITLE
NPM install not working | react-vis@1.9.0 

### ISSUE THREAD

**Issue by Sachinmanoj** [uber/react-vis#733]
I tried 
> _npm install --save react-vis_  

The version 1.9.0 is not creating the dist folder, it just downloads 
- Changelog
- License
- package.json
- Readme

But the ver 1.8.2 is working perfectly it create the dist folder in npm install

**Comment by MohammadHasham** [comment]
same here. The package was working fine a couple of days ago.Did you find any solution @Sachinmanoj

**Comment by MohammadHasham** [comment]
I have found a workaround that you can downgrade to ver 1.81 by

`npm install react-vis@1.8.3 --save`

**Comment by imsickofmaps** [comment]
same, breaking builds

**Comment by Shavindra** [comment]
same here....

**Comment by jonsadka** [comment]
Looking

**Comment by jonsadka** [comment]
Just cut a new build (v1.9.1) to fix the issue which should be live. Thanks for reporting this and sorry about that.

**Comment by imsickofmaps** [comment]
@jonsadka confirmed fixed for me. Thanks!

**Comment by SinghDigamber** [comment]
I tried npm i react-vis --force and it worked for me.
