### ISSUE TITLE
Uncaught DOMException: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules

### ISSUE THREAD

**Issue by volkanunsal** [uber/react-vis#742]
I've been getting this error from the XYPlot component lately. I believe it's happening because [as of Chrome 64 new CORS rules are enforced for stylesheets.](https://stackoverflow.com/questions/48753691/cannot-access-cssrules-from-local-css-file-in-chrome-64/49160760#49160760)

The fix may involve modifying getCSSRules in react-utils file.

**Comment by mcnuttandrew** [comment]
I believe this is addressed in #740 which will be included in a version that will most likely be cut sometime tommorow

**Comment by jckr** [comment]
This is fixed in 1.9.2

**Comment by Sanvycoder** [comment]
@volkanunsal  could you give me in-details of that fix  what needs to be done in utils.js?
