### ISSUE TITLE
make a timeline viewer like performance timeline in chrome

### ISSUE THREAD

**Issue by jonnydodad** [uber/react-vis#747]
Hi, Im having trouble making a performance timeline viewer for displaying react components rendering times, not sure what a good approach would be using react-vis. Ive tried adapting a horizontal bar graph but no success. would love to be pointed in the right direction or just hear some ideas on how to approach making this kind of graph, thanks :)

**Comment by jckr** [comment]
how I would approach this is using rect series (say, HorizontalRectSeries). If you know exactly the time of the rendering that's your x prop, the duration is your width, the depth is your y and the height is an arbitrary constant.

**Comment by jonnydodad** [comment]
thanks a bunch!

**Comment by jbach** [comment]
I’m trying to recreate something like this (taken from [d3-timeline](https://www.npmjs.com/package/d3-timelines)):
![](https://raw.githubusercontent.com/denisemauldin/d3-timeline/HEAD/examples/timeline4.png)

I gathered that HorizontalRectSeries could work for that, but I can't seem to render at the right position without explicitly defining y/y0, which wouldn’t work for `yType='ordinal'`, right?

How can I use HorizontalRectSeries with ordinal scales? I threw up a [codepen here](https://codepen.io/anon/pen/VVEpxR?editors=0010).

**Comment by priombiswas89** [comment]
I would love to see whether you have got some success because I am also looking for something like this to implement using react-vis
