### ISSUE TITLE
series data formatting

### ISSUE THREAD

**Issue by wadehenning** [uber/react-vis#750]
Could you please help me figure out what I am doing wrong with my data formatting?  I am trying to plot a closed curve.  I have an array of objects that include the coordinates.
![image](https://user-images.githubusercontent.com/10761087/37558188-8fcbede4-29e6-11e8-93b7-15442438beb9.png)
Each Object looks like this:
![image](https://user-images.githubusercontent.com/10761087/37558195-b66e9014-29e6-11e8-8e18-55c784d2c72a.png)
My final goal is to plot many of these curves on the plot. 
Thank you.

**Comment by jckr** [comment]
Hi, this looks good so far, can you share the rest of your code?

**Comment by wadehenning** [comment]
Sure- thanks. The data comes in here and calls the plot component. I don't know if I am allowed an id in the data, so I remove it after it comes in before sending to the plot component.
![image](https://user-images.githubusercontent.com/10761087/37608713-a6310a56-2b71-11e8-9960-7ff39f03d0cc.png)


Here's the plot component. Could be that some of these component parameters are not suitable for my polygons:
![image](https://user-images.githubusercontent.com/10761087/37608763-c5b1564c-2b71-11e8-8829-7965a6a6a606.png)

**Comment by wadehenning** [comment]
Sure- thanks. The data comes in here and I group it, then I choose only the first shape to see if I can get some results.  I remove the 'id' because I don't know if that is ok to send to your plot. 
![image](https://user-images.githubusercontent.com/10761087/37609161-bf809f52-2b72-11e8-9d4d-523d25ba6a2f.png)
Here is the shape plot.  I haven't looked much at the parameters yet- I copied this from somewhere and am working to modify it to work with my shapes.
![image](https://user-images.githubusercontent.com/10761087/37609201-de1e24ca-2b72-11e8-8d49-7ad8fa82faad.png)

**Comment by jckr** [comment]
I don't see anything weird so far, it's possible that the data that you pass to your function doesn't generate a visible polygon. 
Does your output generate anything?  
Here's an example with polygon series: https://codepen.io/jckr/pen/yKgyVE?editors=1010
You can add any property (i.e. id, etc.) to the array of objects that goes in a series.

**Comment by wadehenning** [comment]
Thanks for checking- I'll look more closely.

**Comment by wadehenning** [comment]
Maybe I need some state management, like a constructor,  in the component.  I don't understand that very well yet.

**Comment by mcnuttandrew** [comment]
@wadehenning did this end up getting you where you needed to go? I'm marking it as resolved, but feel free to re-open if you wish
