### ISSUE TITLE
Implement onTouchMove handling

### ISSUE THREAD

**Issue by kanzelm3** [uber/react-vis#751]
This library is great! One feature we really want to implement is `touchmove` handling on mobile devices. We would really love it if when a user moved their finger across the chart, it would execute `onNearestX` again so that the behavior is more in line with desktop. It looks like it may be as simple as adding the `onTouchMove` handler here:  https://github.com/uber/react-vis/blob/master/src/plot/xy-plot.js#L447

I would be happy to implement it and submit a PR, can you see any potential issues with the idea though?

**Comment by jckr** [comment]
We'll be happy to look at a PR. Thanks!

**Comment by kanzelm3** [comment]
@jckr let me know what you think!
