### ISSUE TITLE
Add margin to axes

### ISSUE THREAD

**Issue by woniesong92** [uber/react-vis#755]
Is there a way to add margin to axes?
The ticks are too close to the graph and it would be great to introduce some margin there!

![image](https://user-images.githubusercontent.com/2935309/37846905-56234fd8-2e8c-11e8-859d-5db5e736bbf6.png)

**Comment by jckr** [comment]
Yes. You can pass a "left" property to your YAxis and give it a negative value. You may want to increase the margin prop at the XYPlot level.

Here's an example: https://codepen.io/jckr/pen/dmzOmy

**Comment by woniesong92** [comment]
@jckr Thank you!
