### ISSUE TITLE
add label to Horizontal Bar series

### ISSUE THREAD

**Issue by jonnydodad** [uber/react-vis#759]
Hi I am trying to add a label to each bar of a horizontal bar series. Ive added a Label Series component but the label isn't contained in the bar, hangs off to the side. Is there any way to hide a label if it doesn't fit inside of a bar?

**Comment by jckr** [comment]
apologies for late reply. There's no quick solution at the moment. 
The latest PR, https://github.com/uber/react-vis/pull/768, does address this problem. Will cut a 1.9.3 release in the next couple of days.

**Comment by jonnydodad** [comment]
awesome thank you!

**Comment by tumetus** [comment]
Any update on when the new release will be available? 🙂
