### ISSUE TITLE
How to increase specificity of the className classes for the visualizations

### ISSUE THREAD

**Issue by JatinYadav1307** [uber/react-vis#769]
`.mark-series Circle {
    fill: #333;
    color: #333;
    stroke: #333;
}`

`<MarkSeries
          data={this.DATA[0]}
          className={'mark-series'}
        />`

The resultant is still the default Teal color for the marks, how to change the color with CSS.

**Comment by mcnuttandrew** [comment]
Hey @JatinYadav1307 

You can increase the specificity of the selector by adding stuff from react-vis like
```
.rv-xy-plot__series.rv-xy-plot__series--mark.mark-series-example > circle
```
Also, pro-tip you can always get the browser to tell you a more specific selector via "copy selector", like so 

![screen shot 2018-03-28 at 9 11 23 pm](https://user-images.githubusercontent.com/6854312/38066393-61c0b62e-32cd-11e8-8250-0119e17ce70a.png)



However it might behove you to just change the color directly via either the color prop
```
<MarkSeries data={this.DATA[0]} className="mark-series" color="#333" />
```
or through the style prop
```
<MarkSeries data={this.DATA[0]} className="mark-series" style={{fill: 'red', stroke: '#ccc'}} />
```


Hope that helps!

**Comment by JatinYadav1307** [comment]
This works for me, but shouldn't there be a better way to increase the specificity for the elements without having to add this much of CSS selectors and what about separate Charts with different classes how to deal with those. What I am aware of is that this `.rv-xy-plot__series.rv-xy-plot__series--mark.mark-series-example` is added to every line mark series, how to differentiate between others without adding this much of CSS selectors?
