### ISSUE TITLE
How to add onClick event on the CustomSVGSeries item?

### ISSUE THREAD

**Issue by yashshah** [uber/react-vis#771]
I'm using `CustomSVGSeries` to render my own svg and unable to add `onClick` on any of the SVG elements. How do you suggest to use onClick event on CustomSVGSeries?

Thanks!

**Comment by jckr** [comment]
You're right, there's no click event listening going on on customSVGSeries. we can add in the future

**Comment by mcnuttandrew** [comment]
Pull requests to address this are welcome!
