### ISSUE TITLE
How to create a minimal bar graph

### ISSUE THREAD

**Issue by nareshbhatia** [uber/react-vis#776]
I am trying to create a minimal stacked bar graph which occupies the full width and height of the container. See the bar below. You can ignore the labels, I will render them myself.

![screen shot 2018-04-05 at 5 26 07 pm](https://user-images.githubusercontent.com/1220198/38392740-915b3416-38f6-11e8-8464-4bce6064c78e.png)

I tried using `FlexibleXYPlot` for this, but it looks like the plot is leaving a lot of left and bottom margin - see below:

![screen shot 2018-04-05 at 5 31 24 pm](https://user-images.githubusercontent.com/1220198/38392969-4a2c1992-38f7-11e8-9953-543e91fed126.png)

What am I doing wrong? Here's my code:

```
import React, { Component } from 'react';
import 'react-vis/dist/style.css';
import { FlexibleXYPlot, HorizontalBarSeries } from 'react-vis';

const styles = {
    panel: {
        width: 200,
        height: 80,
        backgroundColor: '#4d3e2e'
    }
};

class App extends Component {
    render() {
        const series1 = [{ y: 1, x: 20 }];
        const series2 = [{ y: 1, x: 10 }];
        const series3 = [{ y: 1, x: 70 }];

        return (
            <div style={styles.panel}>
                <FlexibleXYPlot stackBy="x">
                    <HorizontalBarSeries data={series1} color="#f2d200" />
                    <HorizontalBarSeries data={series2} color="#404040" />
                    <HorizontalBarSeries data={series3} color="#000000" />
                </FlexibleXYPlot>
            </div>
        );
    }
}

export default App;
```

**Comment by jckr** [comment]
Hi, you're not doing anything wrong but XYPlot has a default margin settings optimized for charts with labels, etc. 
to have your bar flush on the side of XYPlot pass this prop: margin={{top: 0, bottom: 0, left: 0, right: 0}}

**Comment by nareshbhatia** [comment]
Works like a charm, @jckr. Thanks for the help. Time to learn more!
