### ISSUE TITLE
unable to style labels on Sunburst

### ISSUE THREAD

**Issue by HarringtonM2** [uber/react-vis#779]
Is there a way to style the labels on the sunburst? I cannot seem to find that. I want to be able to pass a value to each of the data sets with a color for the label so that each piece of the sunburst can have a different color text.

**Comment by jckr** [comment]
There are several ways. These labels are really a LabelSeries so you could always change the styling for .rv-xy-plot__series--label-text in your stylesheet. You can also include a labelStyle property in your data points.

**Comment by HarringtonM2** [comment]
labelsStyle doesn't seem to work on the sunburst. Do you have an example of this working?/

**Comment by HarringtonM2** [comment]
Thanks. The documentation had an extra 's' (labelsStyle)

**Comment by kylietmo** [comment]
I can only style the labels to a certain extent. In particular - color will not apply and the labels are consistently black no matter which method I try. I also tried creating a single LabelSeries object as well separate from the data labels and styling it as shown in documentation examples and again it ignored any color styling. 

 For example, if I have this:

<img width="670" alt="screen shot 2018-11-01 at 11 04 06 am" src="https://user-images.githubusercontent.com/11698457/47870161-1b889880-ddc6-11e8-828e-c710662804c7.png">

I get this (notice the labels are still black but the other styles applied):
<img width="149" alt="screen shot 2018-11-01 at 11 04 17 am" src="https://user-images.githubusercontent.com/11698457/47870162-1b889880-ddc6-11e8-83f4-5ad2a47f4013.png">

**Comment by gpa-bblackman** [comment]
<RadialChart
                radius={50}
                data={dataArr}
                showLabels
                colorType={'literal'}
                labelsStyle={{
                        textAnchor: 'middle',
                        fontSize: 12,
                        fontWeight: 500,
                        fill: '#e9e9e9'
                }}
                width={110}
                height={120}
                >
            </RadialChart>
