### ISSUE TITLE
Add PlotBands as series

### ISSUE THREAD

**Issue by KamalAman** [uber/react-vis#780]
What would be the best way to add PlotBands as a series to a chart. The colored bars in the example below are X plot bands

<img width="458" alt="screen shot 2018-04-12 at 10 40 40 pm" src="https://user-images.githubusercontent.com/2692357/38714106-adf2f120-3ea2-11e8-98fa-5b2ab9e3a695.png">

PlotBands have a and x1 and x2 value and consume all y over the range, unless otherwise specified. (or vise versa) 

I think it would be very similar to a mark-series.

**Comment by mcnuttandrew** [comment]
I think the best way to do this would either be through 
- the use Polygon Series (https://uber.github.io/react-vis/documentation/series-reference/polygon-series), where you specify data like [{x: startTime, y: 0}, {x: endTime, y: 0}, {x: endTime, y: maxVal}, {x: startTime, y: maxVal}]. 
- using a rect series (https://uber.github.io/react-vis/documentation/series-reference/rect-series), which would have data like [{x0: startTime, x: endTime, y: maxVal}].

**Comment by mcnuttandrew** [comment]
I'm going to mark this as resolved, but feel free to reopen if you still want help
