### ISSUE TITLE
Example issues

### ISSUE THREAD

**Issue by YeomanCai** [uber/react-vis#79]
I'd like to do some exercises of react-vis, but some issues happened. 

1.The LineSeries doesn't look like same as 'http://uber.github.io/react-vis/' provided. Just like as the attachment image.
![image](https://cloud.githubusercontent.com/assets/3434576/15200834/44540284-181d-11e6-8349-7dbb61986ed4.png)

2.The VerticalBarSeries doesn't display normally, It only has coordinate like as the attachment image.
![image](https://cloud.githubusercontent.com/assets/3434576/15200897/caf07f7a-181d-11e6-86a3-488e7a8ef602.png)

Other series and radial work fine. All the example codes come from the 'src/example' file directory. 

Some suggestions: Could you provide the example codes for each chart in 'http://uber.github.io/react-vis/' or build online editors in jsfiddle?

**Comment by bulyonov** [comment]
@YeomanCai , thank you for your report.

I have a strong assumption that you don't have the CSS file included. We highly suggest to do that, otherwise you'll get a lot of issues (including those which I see right now). Could you double check that you have `./node_modules/react-vis/main.css` in head or imported into your SASS file?

Please provide the source code if you'll get this issue again.

**Comment by YeomanCai** [comment]
@bulyonov , thank you for your help.
I checked what you said, I really missed the style file import. Now LineSeries has worked well. But the VerticalBarSeries still can not display the data inside.
![image](https://cloud.githubusercontent.com/assets/3434576/15278333/dcea7aa8-1b49-11e6-99f5-99c2bc35eb2c.png)

**Comment by bulyonov** [comment]
@YeomanCai , we need the source code as well as the screenshot. Could you attach your sourced **and** your data examples here?

**Comment by YeomanCai** [comment]
@bulyonov , It comes from https://github.com/uber/react-vis/blob/master/src/example/plot/bar-chart.js.

`<XYPlot
        width={300}
        height={300}>
        <VerticalGridLines />
        <HorizontalGridLines />
        <XAxis />
        <YAxis />
        <VerticalBarSeries
          data={[
            {x: 1, y: 10},
            {x: 2, y: 5},
            {x: 3, y: 15}
          ]}/>
        <VerticalBarSeries
          data={[
            {x: 1, y: 12},
            {x: 2, y: 2},
            {x: 3, y: 11}
          ]}/>
      </XYPlot>`

**Comment by YeomanCai** [comment]
@bulyonov , excuse me, I have another question, has React-vis implemented the donut chart?

**Comment by YeomanCai** [comment]
I think that will get more stars if rename React-vis to something like ReactD3xxx or add some description about react chart.

**Comment by YeomanCai** [comment]
@bulyonov I send my example code as much as possible to you as following, please help to solve this problem, thank you!
![qq 20160517232755](https://cloud.githubusercontent.com/assets/3434576/15328459/84ae7cba-1c87-11e6-84e5-d1bc93cf076d.jpg)

**Comment by YeomanCai** [comment]
The issue caused from my other codes influencing, so now I close the issue.
