### ISSUE TITLE
Is there a way to get labels instead of numbers in the axes for the heatmap?

### ISSUE THREAD

**Issue by codewithsk** [uber/react-vis#790]
For example:
In the attached image, is it possible to get "dog", "cat", "elephant" etc. instead of 1,2,3..?

<img width="336" alt="screen shot 2018-04-26 at 11 38 52 am" src="https://user-images.githubusercontent.com/6351528/39316143-6fb20168-4946-11e8-8480-08362ed93b42.png">

**Comment by mcnuttandrew** [comment]
I don't think it is possible the build a heatmap using ordinal data, but you can certainly relabel the axes. 

```jsx
<xAxis tickFormat={(val, idx) => SOME_PIECEWISE_FUNCTION_DESCRIBING_YOUR_DESIRED_LABELS(val)}>
```

Where the inner function could be some sort of specially tuned d3 scale, like a bandscale or piecewise. There are lots of ways to do it!

**Comment by mcnuttandrew** [comment]
I was totally wrong! You totally can use categorical variables for building heatmaps, you just need to define the xDomain and yDomain. See above committ

**Comment by codewithsk** [comment]
Thank you :+1:
