### ISSUE TITLE
What type of object does Hint expect for its `value` property.

### ISSUE THREAD

**Issue by angus-c** [uber/react-vis#792]
The documentation says an Object, which is a data point. I assumed this meant an x,y co-ordinate but 

`<Hint value={{x: 1, y: 2}} />`

throws Object(...)(...) is not a function.

thanks!

**Comment by angus-c** [comment]
Got it. It is {x, y} but I wasn't nesting it inside the a react vis component.

**Comment by mathewleland** [comment]
I just wanted to add to this because i got hung up on the Object(...)(...) is not a function error too -- make sure your <Hint /> is _right before_ your </XYPlot> closing tag (or whatever plot type you're using).
