### ISSUE TITLE
FlexibleXYPlot doesnt fill full width of container

### ISSUE THREAD

**Issue by zlydenko** [uber/react-vis#795]
Trying to make graph to be full width of screen, thought FlexibleXYPlot can resolve all my problems, but still graph is have a borders on left side and bottom side.
 <img src="http://g.recordit.co/rBw8d0QXxu.gif"/>

**Comment by zlydenko** [comment]
Its ok, just use react-easy-charts instead

**Comment by zlydenko** [comment]
Its ok, just use react-easy-charts instead

**Comment by alanhr** [comment]
Hi @zlydenko, u only need put that prop in flexible `margin={{ top: 0, left: 0, right: 0, bottom: 0 }}`
