### ISSUE TITLE
Get current x axis value on hover or click event

### ISSUE THREAD

**Issue by daumann** [uber/react-vis#798]
As far as I understand the docs, it is currently only possible to get defined values (innerX/ innerY) on events like nearestXHandler. 

However, it would be nice to get the current x value fluently - if defined as a data value or not via a mouse hover or click event.

Please let me know if I should clarify my question (I feel I worded it a bit strangely).

**Comment by mcnuttandrew** [comment]
This can be handleded through the use of the Highlight component i think. I'm gonna close this, but feel free to reopen if it doesn't meet your use case
