### ISSUE TITLE
TreeMap error for x attribute

### ISSUE THREAD

**Issue by kimballj** [uber/react-vis#803]
I'm trying to use the TreeMap component using the following code and I'm getting an error:
"Warning: Received NaN for the `x` attribute. If this is expected, cast the value to a string."

```jsx
<Treemap 
     width={this.props.width}
     height={this.props.height}
     data={data}
     renderMode={'SVG'}
     hideRootNode={true}
     colorType={'literal'}
     colorRange={['#88572C']}
     mode={'squarify'}
     padding={5}
/>
```
All the text labels are being drawn but not in the correct location, also the colorRange prop seems to have no effect.

**Comment by mcnuttandrew** [comment]
I'm gonna close this as we can't really help without more information. Feel free to reopen
