### ISSUE TITLE
Zoomable Typescirpt Chart

### ISSUE THREAD

**Issue by Domino987** [uber/react-vis#805]
Hello,
I try to incoperate the zoom ability into the flexible xychart in typescript  but I cant get it to work.
The useage of the  highlight.js does not work and throws the following errors:
[ts] JSX element type 'Highlight' is not a constructor function for JSX elements.
[ts]
JSX element type 'Highlight' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'Highlight'.
[ts] JSX element class does not support attributes because it does not have a 'props' property.
[ts] Property 'onBrushEnd' does not exist on type '{}'.

Is there a way to get it to work or to add the zoom directly to the XY- Chart so that it does not have to be configured externally?

Thanks in advance.

**Comment by chrisgervang** [comment]
Which Typescript definition are you using? It’s possible that it is incomplete and perfectly valid code still gives ts errors.

I recommend ignoring the type errors. Typescript by default still emits the code, so you should be able to debug it in the browser (like normal js development)

**Comment by mcnuttandrew** [comment]
@636 is relevant here

**Comment by Domino987** [comment]
I am using the definitions mentioned in #636 and it works fine except the Zoom add-on. I got it to work with nearest X and drawing the area myself, which seems to work fine. But the displayed zooming in the showcase works a little bit smoother.

**Comment by darbs** [comment]
Basic typescript definition im using in conjuction with #636 to define the Highlight component defined in the zoomable chart example.

export class ScaleUtils {
        static extractScalePropsFromProps: any;
        static getAttr0Functor: any;
        static getAttributeFunctor: any;
        static getAttributeScale(prop: any, dim: any): any;
        static getAttributeValue: any;
        static getDomainByAccessor: any;
        static getFontColorFromBackground: any;
        static getMissingScaleProps: any;
        static getOptionalScaleProps: any;
        static getScaleObjectFromProps: any;
        static getScalePropTypesByAttribute: any;
        static getXYPlotValues: any;
        static literalScale: any;
    }

**Comment by mcnuttandrew** [comment]
I'm closing this as #636 handles the request more broadly
