### ISSUE TITLE
Dead link to bar series doc

### ISSUE THREAD

**Issue by jtraviesor** [uber/react-vis#806]
While reading the documentation website, got a 404  https://uber.github.io/react-vis/website/dist/bar-series.md

**Comment by jeresch** [comment]
To add detail, I get the same issue by navigating to `Documentation > Api Reference > Series > [Any link to a type of series at the top of the page]`.

Those links are to urls like [https://uber.github.io/react-vis/website/dist/line-series.md](https://uber.github.io/react-vis/website/dist/line-series.md).

Navigating to the documentation by `Documentation > Series Reference > [Series type]` works, and has links like [https://uber.github.io/react-vis/documentation/series-reference/line-series](https://uber.github.io/react-vis/documentation/series-reference/line-series)
