### ISSUE TITLE
Can't resolve d3-shape

### ISSUE THREAD

**Issue by codewithsk** [uber/react-vis#807]
For some reason I'm getting the following error on install react-vis and trying to use the treemap component

> Failed to compile.
> 
> ./node_modules/d3-sankey/src/sankeyLinkHorizontal.js
> Module not found: Can't resolve 'd3-shape' in '/Users/sk/Projects/ladderlogic/src/maintmax/frontend/node_modules/d3-sankey/src'
> 

react-vis-force seems to work fine.

**Comment by mcnuttandrew** [comment]
react-vis-force and react-vis are really different libraries, so their installations don't really overlap. How are you installing react-vis? Can you post your package.json?

**Comment by mcnuttandrew** [comment]
We haven't heard anything else about this, so i'm marking this as resolved
