### ISSUE TITLE
Zoom and click handler

### ISSUE THREAD

**Issue by nehaverma8** [uber/react-vis#808]
I followed the example for zoom 
https://uber.github.io/react-vis/examples/charts/zoomable-chart 

In the same chart, I want to enable click ( for that I replaced LineSeries with LineMarkSeries in the above example) as I am creating a drill down chart  

However, the onValueClick event does not get fired at all. Would someone be able to help with it? 

Thanks!

**Comment by mcnuttandrew** [comment]
The new highlight component should address this!
