### ISSUE TITLE
Zoomable example has selection shifted on Firefox, making the right edge unzoomable

### ISSUE THREAD

**Issue by toddgardner** [uber/react-vis#809]
Tested on firefox 60.0.1 (64-bit), mac os 10.12.6.

When Zooming on firefox the selection is actually shifted over several ticks to the left of where you actually clicked, making it impossible to zoom in on the right edge of the graph. I have trouble capturing a screen shot mid zoom showing the misplaced selection, but here's before:

<img width="926" alt="screen shot 2018-05-16 at 5 04 52 pm" src="https://user-images.githubusercontent.com/7430154/40144117-7c459a30-592b-11e8-8ef3-a87ce68b7968.png">

and after; this is clicking above the 80 marker and dragging off the right side of the chart:

<img width="915" alt="screen shot 2018-05-16 at 5 07 33 pm" src="https://user-images.githubusercontent.com/7430154/40144168-a9a13a02-592b-11e8-943e-557cd779ee45.png">

Note instead of starting at 80 it's shifted over a few and the end behavior, where bananas goes below apples, isn't in the zoom. The grey highlight shows over that section, significantly to the left of the mouse cursor when you start dragging.

The same example works fine with chrome on the same machine. This is affecting one of my projects so I'm digging into it.

**Comment by mcnuttandrew** [comment]
If you get a solution I'd be hyped to see a PR

**Comment by Domino987** [comment]
I improved the component to zoom x an y and fixed the offset at #858

**Comment by mcnuttandrew** [comment]
See the new highlight component!
