### ISSUE TITLE
Dynamic styles for labels

### ISSUE THREAD

**Issue by matheusml** [uber/react-vis#810]
Hi,

thanks for this awesome lib!

I'm using a RadialChart, like this:

```javascript
<RadialChart
    colorType="literal"
    width={150}
    height={150}
    innerRadius={65}
    radius={57}
    data={parseData(assets)}
    labelsRadiusMultiplier={1.3}
    labelsStyle={{
        fontSize: 12,
        fontFamily: "Lato Bold, Lato",
        letterSpacing: 0.4
    }}
    showLabels
    animation
/>
```

Right now, all labels are simply painted black. What I want is for them to use different colors.

Is this possible?

**Comment by mcnuttandrew** [comment]
It appears that you can't currently style labels individually. I would accept a PR that adds an allowed (ie non required) property to the data called labelStyle, that way you can style each label individually. I also think there is a little bit of clean up on the labelsStyle to be done, (ie it doesn't work quite as desired), which I would also accept a PR for.

**Comment by matheusml** [comment]
Great to hear that!
