### ISSUE TITLE
Hint not working

### ISSUE THREAD

**Issue by matheusml** [uber/react-vis#811]
Hi,

I'm trying to setup a Hint just like this [example](https://github.com/uber/react-vis/blob/master/showcase/radial-chart/donut-chart.js), but I'm getthing this error:

![](https://i.imgur.com/sevVVX8.png)

Thanks!

**Comment by mcnuttandrew** [comment]
It sounds like you might have a syntax error, can you post your code?

**Comment by matheusml** [comment]
It was a typo :-1:

**Comment by RParvathi** [comment]
This issue persists for me. Is there a resolution ?
