### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#816]
It appears that an upstream dependency has broken with node 6 and 7 support (fsevents maybe?) and is causing the build to fail. This should be fixed asap!

**Comment by jckr** [comment]
Thanks Andrew. Will look into it as soon as I’m in front of a laptop.

**Comment by lzhuor** [comment]
Hi @mcnuttandrew and @jckr, thank you for maintaining. 

I got a chance to take a look at the build error. It's caused by `hoek` package. I suppose `5.0.3` is not supported by node versions below v8.9. So downgraded `hoek` to `4.2.1`. The build is a pass now. 

ref #817

**Comment by jckr** [comment]
Oh so that's what happened. hoek was reported as having a vulnerability which is why i had bumped it up. Turns out the vulnerability had been fixed even in earlier versions of the module so that wasn't necessary. All in all, we don't need to have hoek 5.0.3. Thanks @lzhuor

**Comment by lzhuor** [comment]
@jckr My pleasure :P

**Comment by lzhuor** [comment]
Hi @jckr Apologies, I guess the previous PR is not rebased properly so the master doesn't have the change. Recreating a PR for it. 

#819
