### ISSUE TITLE
Crosshair titleFormat

### ISSUE THREAD

**Issue by cvalmonte** [uber/react-vis#836]
From the [docs](https://uber.github.io/react-vis/documentation/api-reference/crosshair):
titleFormat (optional)
Type: function The function that formats the title for the crosshair. Receives the list of data points, should return an object containing title and value properties. Note: please pass custom contents in case if you need different look for the crosshair.

I pass an arrow function as a prop, which includes an object with `title` and `value` properties, like so:
```
<Crosshair
      values={crosshairValues}
      titleFormat={(d) => {{title: 'Date', value: new Date(d[0].x).toLocaleDateString()}}}
      itemsFormat={(d) => [{title: 'Queries made', value: d[0].y}, {title: 'Matches found', value: d[1].y}]}
/>
```
...and get this compilation error
<img width="831" alt="screen shot 2018-06-15 at 11 05 03 am" src="https://user-images.githubusercontent.com/39921506/41482966-24ff9938-708c-11e8-9e9a-a2a78df25a70.png">

**Comment by lzhuor** [comment]
Please understand that Arrow function returns object with this syntax
```
const getObj = () => ({ value: "hello world!" }); // instead of () => {{ ... }}
``` 

Your code should be:
```javascript
<Crosshair
      values={crosshairValues}
      titleFormat={(d) => ({title: 'Date', value: new Date(d[0].x).toLocaleDateString()})}
      itemsFormat={(d) => [{title: 'Queries made', value: d[0].y}, {title: 'Matches found', value: d[1].y}]}
/>
```

😉 I'd suggest finding a good IDE which will pop up warning/hint in such case.

**Comment by cvalmonte** [comment]
Doh! Thank you!

**Comment by manu1222** [comment]
How to pass title as blank, right now it's displaying `: valuehere`, how to get rid of `:` when title is `null` for `titleFormat`

**Comment by ma-e** [comment]
> How to pass title as blank, right now it's displaying `: valuehere`, how to get rid of `:` when title is `null` for `titleFormat`

I have the same issue, did you find out solution?
