### ISSUE TITLE
Style a single bar or rect

### ISSUE THREAD

**Issue by markov00** [uber/react-vis#838]
Hi I was wandering if it's possible to style a single bar or rect at mouseover. I want to be able to decrease the opacity of all the element in a series to highlight the hovered one.

Is it possible to do directly from the line series for e.g. specifying the opacity function without touching the data (like I see it's currently done in the hero component of the react-vis website?

If not what do you suggest as best practice for this?

**Comment by jckr** [comment]
sure. Here's one way to do this:
https://codesandbox.io/s/109xx5j08j
this shows how a bar chart can change colors on mouseover. 

Specifically with opacity, here's how this could look like:
https://codesandbox.io/s/916609lv0o

**Comment by jckr** [comment]
vis.academy has more on this. http://vis.academy/#/building-a-geospatial-app/5-interacting-with-charts

**Comment by markov00** [comment]
Thanks @jckr I will work in that way.

**Comment by stdmn** [comment]
@jckr Sorry to co-opt this thread, but I've seen quite a few other questions related to this without any clear answer: is it possible to style a single bar with more than just color? 

For instance, if I try to replace :
`const dataWithColor = data.map((d, i) => ({...d, color: Number(i !== index)}));
`

in your example with: 
`const dataWithColor = data.map((d, i) => ({...d, style: {width: i !== index ? '4px' : '8px' }}));
` 
or 
`const dataWithColor = data.map((d, i) => ({...d, width: i !== index ? '4px' : '8px' }));
`

...neither seems to work. I also tried replacing 
```
     <VerticalBarSeries
            data={dataWithColor}        
            onNearestX={(d, { index }) => this.setState({ index })}
          />
``` 
with:
```
     <VerticalBarSeries
            data={dataWithColor}  
            style={d => d.style}
            onNearestX={(d, { index }) => this.setState({ index })}
          />
```
...also with no luck. Am I attempting something that is impossible in the current build?
