### ISSUE TITLE
ReferenceError: ShowcaseButton is not defined in bar chart

### ISSUE THREAD

**Issue by emeery** [uber/react-vis#839]
ReferenceError: ShowcaseButton is not defined why in bar chart , why i have error 

`Module not found: Error: Can't resolve '../showcase-components/showcase-button'`
`
import ShowcaseButton from '../showcase-components/showcase-button';`

**Comment by mcnuttandrew** [comment]
Showcase button is a component from the showcase components, and unless you have that file created (ala https://github.com/uber/react-vis/tree/master/showcase/showcase-components) then it won't be defined. If you are just copy pasting an example, you can delete the showcase button part, (or you could copy it from the link above) without any trouble.
