### ISSUE TITLE
Warning: Received NaN for the `y` attribute. If this is expected, cast the value to a string

### ISSUE THREAD

**Issue by OmarKhattab** [uber/react-vis#855]
Getting this error for one of my plots, everything is working fine and the ui is being displayed correctly. How can I get rid of it?
```
       <FlexibleXYPlot
         margin={{bottom: 100, left: 70,}}
         xType="ordinal"
         height={500}>
         <VerticalGridLines />
         <HorizontalGridLines />
         <XAxis tickLabelAngle={-45} />
         <YAxis />
         <VerticalBarSeries
         colorType="literal"
         data={
           typeof this.state.data.point !== "undefined"
             ? this.state.data.point.total.map((item, index) => {
                 return {
                   x: item.label,
                   y: item.nodes,
                   color: colors[index]
                 };
               })
             : [{ y: "N/A ", x: 0 }]
         }/>
       </FlexibleXYPlot>
```

**Comment by mcnuttandrew** [comment]
It seems like you have a mismatch in types! It looks like some of the time your x's are ordinal type (they're strings) and in the second case it's a number. Are your x and y swapped in the false branch of your ternary?

**Comment by OmarKhattab** [comment]
Yeah they were swapped you can close this issue

**Comment by adybaby** [comment]
Here's an example use case which is analogous to my own (with some complexity removed!): 

Show the number of sightings each day for each of 10 different types of birds throughout a given year, as well as the total number of birds sighted on each day.  I thought I could show this in a stacked vertical bar chart with time as the x axis, #sightings as the y axis, and a vertical series for each different bird's data.  However, if any one of the birds has only been sighted on one day, the chart breaks (NaN.)

It's possible I'm going about this all the wrong way (I'm still learning react-vis), or that there's a better way to visualise this use case.  If so - I'm all ears!

In  any case, for those yet to encounter this issue, I think it would be useful if the error reported that the data for a time-based bar axis needs to contain at least 3 coordinates (which would have saved me the better part of a day!)
