### ISSUE TITLE
Scaling issues with conditional x/y Domain

### ISSUE THREAD

**Issue by jkerrwilson** [uber/react-vis#859]
If an x or y Domain is specified conditionally the library crashes.

eg.
``` javascript
var scaled = isTheGraphScaled();
<LineSeries ... yDomain={scaled ? d.yDomain : ''} />
```

I would guess there's a check somewhere which just looks to see if yDomain exists rather than checking if it has a meaningful value. This is obviously easily worked around by using external IF statements, but having the ability to conditionally apply things in this manner results in much compacter code,

**Comment by mcnuttandrew** [comment]
I would accept a PR to address this issue!

**Comment by mcnuttandrew** [comment]
After a little more investigation, I think your issue might be elsewhere? I just tried doing 

```javascript
        <XYPlot
          yDomain={!useCanvas ? [0, 15] : ''}
          width={300}
          height={300}>
......CONTENT
</XYPlot>
```

and that worked fine. I'd still be excited to accept a PR to fix this if you can provide some tests demonstrating it failing.

**Comment by jkerrwilson** [comment]
It still crashes for me, but I changed my usage to an if-else block as it doesn't seem worth the time to investigate.

**Comment by mcnuttandrew** [comment]
Weird, well I'm gonna close this issue. Feel free to reopen if you think it should be addressed more
