### ISSUE TITLE
Links in documentation site broken

### ISSUE THREAD

**Issue by sup** [uber/react-vis#862]
For example, go to http://uber.github.io/react-vis/documentation/api-reference/xy-plot and click on the first link `grids`. 

The link redirects to http://uber.github.io/react-vis/website/dist/grids.md which has no content. I'd expect it to link to http://uber.github.io/react-vis/documentation/api-reference/grids.

Similarly, some of the links in the markdown documentation are broken. For example, many of the links in https://github.com/uber/react-vis/blob/master/docs/xy-plot.md 404. I assume the links in the website are generated from these so I'd expect at least one of the two to be working if not both.

**Comment by sup** [comment]
Similarly, links in the markdown documentation are broken. For example, many of the links in https://github.com/uber/react-vis/blob/master/docs/xy-plot.md 404. I assume the links in the website are generated from these so I'd expect at least one of the two to be working if not both.

**Comment by mcnuttandrew** [comment]
I agree! I think making the docs correct on both would be a good long term plan, but I think change you in your PR are reasonable for now. I'll go accept it, sorry for the delay.
