### ISSUE TITLE
Name of the plot in the readme

### ISSUE THREAD

**Issue by MAliNaqvi** [uber/react-vis#866]
Hi
I have been looking at examples on the react-vis library, however I can't find the name of the plot in the readme, the one that has both a series plot overlaid on a bar chart.

https://raw.githubusercontent.com/uber/react-vis/master/docs/assets/react-vis.gif

**Comment by mcnuttandrew** [comment]
Hey @MAliNaqvi 

That example is drawn straight from the maybe poorly named "complex chart", you can see the code here https://github.com/uber/react-vis/blob/master/showcase/plot/complex-chart.js

**Comment by mcnuttandrew** [comment]
(Marking as resolved, feel free to ask more questions under the fold or reopen if you wish)
