### ISSUE TITLE
What is the 'theme' used in showcase examples to get colours ?

### ISSUE THREAD

**Issue by s8sachin** [uber/react-vis#872]
Hello, Thanks for this awesome library!, 
I am trying out your examples and i am trying to understand [this](https://github.com/uber/react-vis/blob/76e6e3cdac6dca63e0d6e599195c5a1ce33211c8/showcase/sunbursts/sunburst-with-tooltips.js#L30)
` import { EXTENDED_DISCRETE_COLOR_RANGE as COLORS } from 'theme'; `

where is this 'theme' ? is this an Npm package ? i am unable to find it.
I am new to this, so i might be missing out something. 
if this issue is highly irrelevant. i will close this.
Please help me understand this. thanks :relaxed:

**Comment by mcnuttandrew** [comment]
Theme is a file internal to the library (https://github.com/uber/react-vis/blob/76e6e3cdac6dca63e0d6e599195c5a1ce33211c8/src/theme.js). Looking at the index.js file it looks we don't export the components of the theme, which I think is an artifact of our intention to develop more themes later. For now, I'd encourage you to just copy paste the theme from the above listed file!

**Comment by s8sachin** [comment]
cool, thanks 👍
