### ISSUE TITLE
Styling line and marks on ParallelCoordinate graphs?

### ISSUE THREAD

**Issue by kevinxia787** [uber/react-vis#875]
Hi, I'm trying to change the default color of my line in Parallel Coordinates to red. I've tried changing the stroke, and adding lineStyle but nothing is working. Does anyone know how to change the line and mark colors?

Style code below.

          <ParallelCoordinates style={{
               axes: {
                  line: {},
                  ticks: {fontSize: 13},
                  text: {}
                },
                labels: {
                  fontSize: 17,
                  textAnchor: 'auto',
                  alignmentBaseline: 'before-edge',

                },
                line: {
                  strokeOpacity: 1,
                  /* lineStyle: {stroke: "red"} */
                  /* stroke: "red"
                }
              }}
            ....
          />

**Comment by mcnuttandrew** [comment]
You can set a color property on each row of data. There probably should be a greater degree of control enabled like you are highlighting tho

**Comment by kevinxia787** [comment]
Thanks @mcnuttandrew!
