### ISSUE TITLE
Adding Dashed lines to a Parallel Coordinates graph

### ISSUE THREAD

**Issue by kevinxia787** [uber/react-vis#876]
Is there a way to make a specific line dashed in a parallel coordinates graph?

**Comment by mcnuttandrew** [comment]
I don't think that is currently possible, but it'd be easy to add! The TLDR is each like should allow a style object as a property and then getLines should combine that the style from the top level style prop. I'd gladly accept a PR to this effect.

**Comment by mcnuttandrew** [comment]
I ended up cutting a PR about this (see above), it'll be up in the next version.
