### ISSUE TITLE
Adding yType of 'log' to graph throws d3.js errors

### ISSUE THREAD

**Issue by alphastorm** [uber/react-vis#88]
I'm using a `FlexibleXYPlot` that renders correctly when not specifying `yType`.  However, as soon as I add `yType: 'log',` to the definition it starts throwing these errors in the JS console:

<img width="1278" alt="screen shot 2016-05-19 at 5 56 00 pm" src="https://cloud.githubusercontent.com/assets/972382/15414024/54456448-1deb-11e6-9670-377c6980c52a.png">

**Comment by bulyonov** [comment]
@alphastorm , according to our face-to-face discussion, you are having zero values in your current chart. Either zero or negative values should not exist for a log scale.

I'm closing this issue.
