### ISSUE TITLE
XYPlot automatically compute margins based on axis labels

### ISSUE THREAD

**Issue by markov00** [uber/react-vis#884]
It's somewhat related to this issue https://github.com/uber/react-vis/issues/883 but more specific to margins.
Have you think about a way to automatically compute the chart margins to avoid axis labels overflows like in this example:
<img width="365" alt="screen shot 2018-07-18 at 09 45 54" src="https://user-images.githubusercontent.com/1421091/42867409-d44f193e-8a6f-11e8-91d2-5fb03f98343e.png">

Currently the margin is static, configured through the XYPlot, but it really depends on tick labels formatted values,  length, height, and styles. Compute the max width/height of a the axis labels is not an hard task and can be easily done inside the Axis components (they already have the number of labels, their values, their text formats and so on). The problem is how to pass these dimensions to XYPlot, what is the best practice to pass something to the parent.
Any thoughts on that?

**Comment by mcnuttandrew** [comment]
I actually think it's harder to automatically size than you think. Fonts might change based css or other styles which might make it hard to guess correctly. Maybe like add more documentation around setting a margin?

**Comment by markov00** [comment]
I currently can compute the right length creating an svg text element (with all the react-vis classes), attach it to the DOM and call "getBBox()" than remove the element.
It's a bit of overhead, but since we are adding no more than 20 labels, it's rather fast and useful.
The problem is that everything is connected with the margin like `getTicksTotalFromSize` that use the innerWidth (width - margins).
