### ISSUE TITLE
LineSeries onMouseOver not responding.

### ISSUE THREAD

**Issue by deepakrocks** [uber/react-vis#889]
OnMouseOver not triggered (: while hovering)when used inside LineSeries However, it is triggered as part of onClick event.
```jsx
 <LineSeries
                key={entry.title}
                data={entry.data}
                color={entry.color}
                onSeriesMouseOver={(event) => {
                  console.log('onSeriesMouseOver called')
                }}             
              />
``` 
Also facing issues populating Hint value.

**Comment by mcnuttandrew** [comment]
@deepakrocks there a number of issues that might be at play here, but maybe take a look here #919?

**Comment by mcnuttandrew** [comment]
I'm closing this as I think the above referenced PR addresses this? Feel free to reopen or ask more questions under the fold
