### ISSUE TITLE
Methods to position legend currently unavailable.

### ISSUE THREAD

**Issue by Oreki47** [uber/react-vis#893]
Hi. I have done some searching but it seems unable to position legend currently. In one of the [examples](https://github.com/uber/react-vis/blob/master/showcase/plot/clustered-stacked-bar-chart.js) it passed  style={{position: 'absolute', left: '40px', top: '0px'}}. 

However, now style is not an argument but a fixed value. 
https://github.com/uber/react-vis/blob/b35a463928c5e922393690efb1bd7a2c8b1777d0/src/legends/discrete-color-legend.js#L40

So is there any work-around to position legends?

**Comment by mcnuttandrew** [comment]
I'd welcome a PR addressing this issue! It should likely be around 1 line
