### ISSUE TITLE
Feature Request: Zoom and Dragging behaviour like Map Application

### ISSUE THREAD

**Issue by kenokenobingo** [uber/react-vis#894]
It would be great if `react-vis` had a map-like zoom and dragging behaviour implemented. I’d like to use a chart like [Google Maps](https://maps.google.com) or [OpenStreetMap](https://www.openstreetmap.org).

**Comment by mcnuttandrew** [comment]
While it's not quite what you are looking for, we have a demo of how to use zoom and drag in a chart context here https://uber.github.io/react-vis/examples/charts/zoomable-chart. I think it's probably possible to build a map in react-vis via PolygonSeries and d3-geo (in a similar manner as the ContourSeries), i think we are trying to stray away from introducing additional exotic series. If you are interested I would definitely encourage you to produce a demo of this functionality, as, again, I believe it's most likely possible to create using the above tools. If you do, I'd welcome a PR showing others how to do it as well.

**Comment by mcnuttandrew** [comment]
I'm going to mark this as closed as this is out of scope for the roadmap, though I would still accept demo as I described above
