### ISSUE TITLE
How to add different color to plots on hovering mark series?

### ISSUE THREAD

**Issue by ksairamya** [uber/react-vis#896]

**Comment by mcnuttandrew** [comment]
There are lots of approaches! Here are two:
- You could stack two XYPlots on top of each other and set the cursor events to none on the top one and only provide the selected data (you should use the dontCheckIfEmpty prop on XYPlot if you go that route https://uber.github.io/react-vis/documentation/api-reference/xy-plot). This is a good approach if you have lots of data and need to avoid redraws.
- If your data is smaller (say less than like 500 points (not a hard line in anyway)) you could change the data, or you could provide a getColor function like getColor={d => d.id === MY_SELECTED_POINT ? 'red' : d.color} and on hover do a set state on the containing component with the points id (or index if you don't want to define an id).

**Comment by ksairamya** [comment]
If you don't mind could you provide me a small example.

**Comment by mcnuttandrew** [comment]
@ksairamya I've provided almost what I described in the second option in the above PR. I also make use of a voronoi for additional insight, though you could totally get by without using a voronoi and just putting your listener on the markseries directly.

**Comment by mcnuttandrew** [comment]
Marking this as resolved, but feel free to re-open if you want

**Comment by dkalamar** [comment]
Theres an example of how to handle this [here](https://github.com/uber/react-vis/blob/master/docs/interaction.md#mousing-over-near-scatterplot-marks)
