### ISSUE TITLE
Is it possible to make the labels on Sankey plot either angled or vertical?

### ISSUE THREAD

**Issue by tayabsoomro** [uber/react-vis#900]
I am trying to make a Sankey plot, representing taxonomic tree but the labels in my data tend to be longer than usual and therefore they overlap one another, below are two snapshots explaining the behaviour. I was wondering if there was a possibility for the labels to be angled or vertical, or even alerting y axis so that it is easier to see using this library?

Thanks,
Tayab Soomro.

**EDIT**

My apologies for I forgot to attach the snapshots earlier, here they are:

> <img width="932" alt="screen shot 2018-08-15 at 6 17 26 pm" src="https://user-images.githubusercontent.com/19979068/44226460-67279080-a14d-11e8-971c-99c1374448d8.png">

Below is the one with less data: 
> <img width="931" alt="screen shot 2018-08-15 at 6 17 54 pm" src="https://user-images.githubusercontent.com/19979068/44226461-67279080-a14d-11e8-9882-e464dd2416fb.png">

**Comment by mcnuttandrew** [comment]
Missing snap shots?

**Comment by tayabsoomro** [comment]
I forgot to add them earlier, apologies. I've updated my comment above.

**Comment by mcnuttandrew** [comment]
Addressed in above PR

**Comment by tayabsoomro** [comment]
Could you please also update the `npm` library? It doesn't seem to download the latest code.

**Comment by mcnuttandrew** [comment]
@benshope @jckr etc will somebody do a patch?

**Comment by benshope** [comment]
@mcnuttandrew yep!

**Comment by benshope** [comment]
@tayabsoomro bumped to 1.10.5

**Comment by tayabsoomro** [comment]
This issue still continues...

**Comment by mcnuttandrew** [comment]
1.10.7 appears to have recent changes in it no?

**Comment by tayabsoomro** [comment]
Oh wait.. my bad. I was still at `1.10.5`. It's all good to go!
