### ISSUE TITLE
LineSeriesCanvas - onNearestXY not called

### ISSUE THREAD

**Issue by WildHorse19** [uber/react-vis#902]
Good day everyone. First of all i want to thank you guys for this awesome library. I'm having small issue, i know this is not a stack-overflow but i cant seems to find any solution.  Any advice would be greatly appreciated. I'm build data visualization application for my friend and it works with svg, but he demands performance improvement, so i found article of Mr. Andrew McNutt about performance optimization, he advice's there to use LineSeriesCanvas for static part of visualization, So i tried to use it but  onNearestXY is never called.  It seems like in _getClonedChildComponents function in xyplot.js file ref is not being preserved for canvas series

```
 ref: r => {
                this[`series${seriesProps[index].seriesIndex}`] = r; //never happens
                //const {ref} = child;
                //if(typeof ref === 'function'){
                //   ref(node);
                //}
                return r;
            }
```
So i have to do same small changes in order to make it works 
1) i changed render method of LineSeriesCanvas  to return empty div instead of null
2) in canvas wrapper i added children into render method
```
 <div style={{left: 0, top: 0}} className="rv-xy-canvas">
        <canvas
          className="rv-xy-canvas-element"
          height={height * pixelRatio}
          width={width * pixelRatio}
          style={{
            height: `${height}px`,
            width: `${width}px`
          }}
          ref={ref => (this.canvas = ref)}
        />
        {this.props.children} //here we go
      </div>
```
Now it seems like its working again, onNearestXY  called and i can zoom graph again. So my question is is there any way to avoid making changes into source code to make it works. My setup very simple XYPlot and list of plots inside nothing unusual. I'm using latest react 16.4.2 together with latest react-vis 1.10.4. Why this problem can occur, what could be the possible reason ? Thank you very much. Sorry for disturbance!

**Comment by mcnuttandrew** [comment]
Hey @WildHorse19 

Thanks for reading my article ☺️! These seem like reasonable changes, feel free to fire off a PR about them. It would be good if you could add some tests for this functionality so we could ensure future versions don't backslide.

**Comment by WildHorse19** [comment]
Thank you for response and great article! Sure, i will be able to do it tomorrow, One more question i have, there was problem with drawings going outside graph which i successfully solved with Borders component, but it seems like same didn't work for canvas because canvas separated into different layer from svg parts, it seems like it can be solved with filtering (LineSeriesCanvas method renderLayer under line instance) : 

`.defined(p => isNil(xDomain) || !enforceBorder ? true : p.x>=xDomain[0] && p.x<=xDomain[1]);`

So this supposed to keep things inside specified domain, but i think this maybe contradict some different functionalities, i was also thinking to create white divs and position them on top of canvas, maybe this will be better option from performance perspective.

**Comment by mcnuttandrew** [comment]
Oh also, as in the article mentioned an effective way to work around this problem is make your own voronoi overlay to trigger nearest xy. That way you can totally control the placement of the hover cells

**Comment by mcnuttandrew** [comment]
I think your PR addresses this, closing
