### ISSUE TITLE
sankey label position 

### ISSUE THREAD

**Issue by bindai** [uber/react-vis#906]
I created a sankey diagram with the below code .  

```
import {Sankey} from 'react-vis'; 

const nodes = [{name: 'AA'}, {name: 'BBBB'}, {name: 'CC'}];
const links = [
  {source: 0, target: 1, value: 10},
  {source: 0, target: 2, value: 20},
  {source: 1, target: 2, value: 20}
];

<Sankey
  nodes={nodes}
  links={links}
  width={200}
  height={200}
/>
```
![image](https://user-images.githubusercontent.com/5703598/44306784-3ef79600-a3c8-11e8-98bf-fb7660826e34.png)

You can see  the position of the label 'BBBB' isn't right.  Please use react-vis@1.10.4.

Could that be fixed? Thank you.

**Comment by mcnuttandrew** [comment]
I don't immediately have time to address this issue, but I would welcome a PR

**Comment by zachguo** [comment]
probably related #914
