### ISSUE TITLE
Documentation - Getting Started - Colors

### ISSUE THREAD

**Issue by classicmatsuo** [uber/react-vis#910]
https://uber.github.io/react-vis/documentation/general-principles/colors
The examples should show 3 different types of graphs: 

1. VerticalBarSeries
2. LineSeries
3. MarkSeries

The first two examples show these 3 different types, but after that all the examples are displaying:

1. VerticalBarSeries
2. LineSeries
3. LineSeries

(where the last one should be MarkSeries)

**Comment by mcnuttandrew** [comment]
Good catch! I've fixed it the markdown, the docs will come on line by and by
