### ISSUE TITLE
Be able to only view labels for terminal nodes in Sankey plot

### ISSUE THREAD

**Issue by tayabsoomro** [uber/react-vis#913]
Hi,
I am creating a Sankey plot (image below) and I was wondering if there is a way to make these branches farther apart from each other so that the labels are shown correctly?

Right now, it really hard to distinguish one from the other.

<img width="1243" alt="screen shot 2018-08-20 at 12 17 27 pm" src="https://user-images.githubusercontent.com/19979068/44358816-4fb11600-a473-11e8-98de-4783fe1c8ec8.png">

I looked at the documentation for the `layout` prop, and I have tried to randomly give it values like, `layout={...}` where `...` are different numbers, but I do not understand `layout` prop fully to be able to work with it. Any suggestions/ideas?

Thanks,
Tayab Soomro.

**Comment by mcnuttandrew** [comment]
Have you tried providing variations on the align prop? You can give it one of 'justify', 'left', 'right', 'center'. You might also try increasing the nodeWidth and nodePadding to space stuff out more?

**Comment by tayabsoomro** [comment]
Okay, I was able to make the visualization look presentable by aligning it to the `center`. Would it be possible to be able to only show the labels for terminal nodes? I tried just doing `name: ''`, but I would like the names to appear when they hover over a certain node/link.

Thanks,
Tayab Soomro.

**Comment by mcnuttandrew** [comment]
You totally can! See above PR.

**Comment by tayabsoomro** [comment]
Thanks a lot!
