### ISSUE TITLE
LineSeries and LineMarkSeries do not respond to the onNearestX prop. 

### ISSUE THREAD

**Issue by selemtei** [uber/react-vis#919]
I am currently working with react-vis version 1.10.3 and whenever I add the prop onNearestX on the LineMarkSeries and LineSeries it doesn't respond on the mouseOver effect. 

However when I add all the events that are associated with the LineSeries and LineMarkSeries they work perfectly fine! 

Any kind of help, will be appreciated with this issue!

**Comment by mcnuttandrew** [comment]
Can you provide some more context? I just tried using onNearestX on a lineseries and it seems to work fine?

**Comment by selemtei** [comment]
I am iterating through my data array, and return four LineSeries on my graph and I am attaching the prop onNearestX to each one of them. Then when I hover on the plot and series nothing happens. 
But when I use other event handlers I get to see the event that was triggered. 

**My objective is to display a crosshair with multiple y-values when a user hovers on an single X value.**

Here is my code snippet. 
![screen shot 2018-08-20 at 4 55 47 pm](https://user-images.githubusercontent.com/13815299/44372688-ebee1380-a499-11e8-9a13-a57fc9138f2b.png)

**Comment by mcnuttandrew** [comment]
Well assuming that your data doesn't have any gaps, the trick that i've used in the past is pivot my data, so that i have an object with one key per x value which correspond to arrays of points, ala:

```
const pivotedData = data.reduce((row, acc) => {
acc[row.x] = (acc[row.x] || []).concat([row.y]);
return acc;
},
```
And then put an invisible lineseries along the chart somewhere, maybe in the middle, and only listen for onNearestX on that one.

**Comment by selemtei** [comment]
Thank you Andrew for the help, it worked!
