### ISSUE TITLE
Data size property doesn't work 

### ISSUE THREAD

**Issue by Stianhn** [uber/react-vis#922]
I'm trying to set the size of a data point using the property "size" on the datapoint, but it doesn't seem to care about the value of size. It does change the size when I add this property but I'm only getting one size no matter what the value I pass in. 

https://github.com/uber/react-vis/blob/master/docs/mark-series.md

https://codepen.io/anon/pen/zJYyjZ

**Comment by mcnuttandrew** [comment]
The default size behaviour is not unlike the default x and y behaviour. react-vis tries to compute a domain over that variable and tries to match it to the default range. You can tune the specific sizes that marks take by specifing sizeRange={[1, 10]}. This approach can be useful if you don't necessarily want to tie your data to it's visual representation.

In contrast, if you just want to directly control the size, you can set sizeType="literal" on your markSeries which cause the markseries to read the variable exactly as you intend.

**Comment by Stianhn** [comment]
Thanks for the fast feedback @mcnuttandrew .

That works if you want the same size on all your points in the series. But what if you want to set the size on just one point for highlighting?

**Comment by mcnuttandrew** [comment]
Have you taken a look at the scales docs, i think it covers what you are looking for? https://github.com/uber/react-vis/blob/master/docs/scales-and-data.md

As for highlighting, i'd suggest using a pattern of something like https://github.com/uber/react-vis/blob/master/showcase/axes/dynamic-crosshair-scatterplot.js Instead of setting the color, set the size instead, again using sizeType="literal" maybe

**Comment by mberneti** [comment]
No, It doesn't cover because I had this issue.

**Comment by Rowansdabomb** [comment]
> As for highlighting, i'd suggest using a pattern of something like https://github.com/uber/react-vis/blob/master/showcase/axes/dynamic-crosshair-scatterplot.js Instead of setting the color, set the size instead, again using sizeType="literal" maybe

Adding the prop `sizeType="literal"` to my `MarkSeries` component  was required for the size property on my data points to register. Thanks
