### ISSUE TITLE
Documentation site not linking to appropriate files

### ISSUE THREAD

**Issue by mathewleland** [uber/react-vis#928]
When trying to look at the API references for a lot of materials, the pages are not appropriately referenced.

For example, on [this API Reference page](https://uber.github.io/react-vis/documentation/api-reference/series), 
the link for the "rect-series" is given as 
https://uber.github.io/react-vis/website/dist/rect-series.md 
=> which gives an empty container, when I assume we want it to serve the contents of https://github.com/uber/react-vis/blob/master/docs/rect-series.md

This page is appropriately rendered at 
https://uber.github.io/react-vis/documentation/series-reference/rect-series

There are instances of this throughout the documentation, such as the General-Principles page providing the same incorrect links to Arc Series, Line Series, etc.

I hope this is as simple as changing all of those links from /website/dist/ARTICLE_NAME to /documentation/series-reference/ARTICLE_NAME

**Comment by mcnuttandrew** [comment]
Closed due to valiant work of @gsas2
