### ISSUE TITLE
Sankey onLinkMouseOver and onLinkMouseOut behaviour

### ISSUE THREAD

**Issue by dumboluzz** [uber/react-vis#930]
Using the sankey diagram I noticed that onLinkMouseOver event doesnt get triggered while hovering the links label, but instead onLinkMouseOut is fired. Seemed counterintuitive to me, if someone wanted to style the links based on hover events.

Is this intended behaviour?

**Comment by mcnuttandrew** [comment]
I don't quite understand what you mean? The sankeys here http://uber.github.io/react-vis/examples/showcases/sankeys appear to be working as I might expect, but I could be wrong?

**Comment by mcnuttandrew** [comment]
Closing, but feel free to reopen
