### ISSUE TITLE
Highlight OnDrag is Interrupted with A MarkSeries's onValueMouseOver event trigger

### ISSUE THREAD

**Issue by adamchenwei** [uber/react-vis#945]
How can I make sure a onDrag for the Zoom-in component to not interrupted by an onValueMouseOver triggered function in a MarkSeries?

I tried to play around the ordering of the two, but if I place ZoomIn Component After MarkSeries, the onValueMouseOver won't trigger at all.

Any hint will be appreciated! thanks

**Comment by mcnuttandrew** [comment]
A new version of the highlight component is in progress (see #939). Check out my bidirection drag chart in there for more details
