### ISSUE TITLE
Misleading link on the website

### ISSUE THREAD

**Issue by tayabsoomro** [uber/react-vis#946]
Hi, this is a minor issue that almost got me last night. In the plot showcase page ([https://uber.github.io/react-vis/examples/showcases/plots](https://uber.github.io/react-vis/examples/showcases/plots)) the view code link for the BarSeries plot is wrong, it leads to line-chart instead of bar-chart, which I had to find by digging into the GitHub repo. See below for more info:

![screen shot 2018-09-04 at 8 25 27 am](https://user-images.githubusercontent.com/19979068/45037795-01784700-b01d-11e8-8c4c-40e903efde74.png)

Thanks,
Tayab Soomro.

**Comment by mcnuttandrew** [comment]
Thanks for pointing that out! I would welcome a PR if your up for it. I believe the error is somewhere in this file https://github.com/uber/react-vis/blob/master/showcase/showcase-links.js

**Comment by tayabsoomro** [comment]
Definitely! I will create a PR soon. Thanks!

**Comment by tayabsoomro** [comment]
Pulled to master. PR #947. Thanks to @mcnuttandrew 👍
