### ISSUE TITLE
zoomable-chart-example

### ISSUE THREAD

**Issue by azmahmad** [uber/react-vis#950]
I'm new for React graph
can you help me how can I use zoomable-chart-example 
I downloaded the library but not working
can you tell what files I need to download
thank you

**Comment by mcnuttandrew** [comment]
Hey @azmahmad 
The zoomable-chart-example is in the process of changing! The code that is in the code base is an example of how you might make a zoomable chart, if you want to use it you need to copy paste those files out of the [here](https://github.com/uber/react-vis/tree/master/showcase/examples/zoomable-chart). I'm in the process of creating a component that you can use as you'd expect here: #939

**Comment by azmahmad** [comment]
thank you @mcnuttandrew , 
I downloaded [here](https://github.com/uber/react-vis/tree/master/showcase/examples/zoomable-chart) 
it show I've a problem with index file, because it's include a lot of files (showcase)
can you help me 
if you download just the highlight.js and zoomable-chart-example.js 
will face it
thank you for your time

**Comment by mcnuttandrew** [comment]
if you switch 'index' to 'react-vis' in the import it should work

**Comment by azmahmad** [comment]
t show me an error because I dont use index.js
in my files

which index.js I should use with highlight.js and zoomable-chart-example.js 
thank you

**Comment by mcnuttandrew** [comment]
The pr I discussed above is now merged in! You should be able to use the highlight component directly from the library.

**Comment by mcnuttandrew** [comment]
Closing because there is a new thread about this
