### ISSUE TITLE
Sunburst chart

### ISSUE THREAD

**Issue by hemanth09** [uber/react-vis#952]
Hi,

Can we hide the child nodes and only display them onHover or onClick??

**Comment by mcnuttandrew** [comment]
You totally can, however that functionality is not built into the library you'll need to build it as part of your containing component. The sunburst chart offers onClick and onHover components, so one approach to achieving your task would be to use those to set state on a container component and hand that state back to the sunburst. If your data isn't terribly big (like say < a few hundred nodes) it'll probably be fast enough to feel nice.

Interesting idea, if you work out how to do it I'd love to see it in action!
