### ISSUE TITLE
zoomable chart

### ISSUE THREAD

**Issue by azmahmad** [uber/react-vis#953]
hey I'm new for react chart
I face a problem I only want [zoomable chart](https://github.com/uber/react-vis/blob/master/showcase/misc/zoomable-chart-example.js) to work
can someone told me the steps or the files I need to use it
thank you

**Comment by mcnuttandrew** [comment]
Hey @azmahmad 
All you should need to do to get that example to run locally is change the imports to look like

```js
import {
  XAxis,
  YAxis,
  HorizontalGridLines,
  XYPlot,
  LineSeries,
  Highlight
} from 'react-vis';
```

And to change seededRandom() to Math.random()

**Comment by Igosuki** [comment]
Highlight was not released with the latest release on npm it seems. 
```
 wget https://registry.yarnpkg.com/react-vis/-/react-vis-1.11.0.tgz\#58f61179b65a2de338911ec799f806423b5936ff
```

Highlight is nowhere to be found.

**Comment by mcnuttandrew** [comment]
@benshope ?

**Comment by benshope** [comment]
@mcnuttandrew it looks published to me https://www.npmjs.com/package/react-vis

**Comment by mcnuttandrew** [comment]
@benshope i think the version that was cut may have missed some commits. I pulled down 1.11 and found the same thing as the @Igosuki, that highlight was not part of the release

**Comment by benshope** [comment]
@mcnuttandrew I think we may have run into this before.  Perhaps I am missing a step in the process.   I've been running something like:
1. `git pull`
2. `npm version minor`
3. `git push && git push --tags`
4. `npm publish --registry=https://registry.npmjs.org`
Perhaps this ignores yarnpkg registry or something?  Or there is a build step?

**Comment by benshope** [comment]
I'm also happy to try these steps again with a patch and see if it includes highlight?

**Comment by mcnuttandrew** [comment]
!!! I think there's a missing step in that procedure. 

1. git pull
2. npm run build
3. npm version minor
4. git push && git push --tags
5. npm publish --registry=https://registry.npmjs.org

**Comment by benshope** [comment]
@mcnuttandrew haha welp that would explain the issue - I will bump a patch to fix it

**Comment by benshope** [comment]
Oh, just looked it up, guess that untracked files are a part of npm publishes.  Guess that makes sense

**Comment by benshope** [comment]
@Igosuki @mcnuttandrew thanks for your patience!  I have bumped to `1.11.1` and it should include the latest

**Comment by Igosuki** [comment]
Thank you, I'll try it out.

Le lun. 10 sept. 2018 à 20:44, Ben Shope <notifications@github.com> a
écrit :

**Comment by mcnuttandrew** [comment]
@benshope thanks for handling all this build stuff, you continue to be a hero

**Comment by benshope** [comment]
@mcnuttandrew aw thanks but you're the batman to my robin

**Comment by mcnuttandrew** [comment]
Alright, I've just checked and everything appears to be well in v1.11.1 (make a computer wish!). I'm going close this issue. Anyone should feel free to ask for more help under the fold if they want
