### ISSUE TITLE
How to add a label on top of VerticalBarSeries bars with a category x?

### ISSUE THREAD

**Issue by vibl** [uber/react-vis#954]
I cannot find a way to add labels on top of VerticalBarSeries bars with a category x.

Something like this:
https://formidable.com/open-source/victory/docs/victory-bar/#labels

Both Hint and LabelSeries need values with numerical x and y, but x is not numerical here.

I have been trying many solutions for hours now. I even tried getting the bar coordinates with refs (which is pretty hack).

This seems a pretty basic need to me. Can it be done with react-vis?

**Comment by mcnuttandrew** [comment]
Hint and LabelSeries dont actually need numerical values to be placed correctly! You just need to make sure to set the appropriate scale type on the root component (XYPlot). Eg if you are using ordinal data you need to set xType="ordinal".  I expanded one of the examples as a helpful hint https://github.com/uber/react-vis/blob/51aa38da2e01c9ad17ae4cb7594943349e87e687/showcase/plot/bar-chart.js

**Comment by mcnuttandrew** [comment]
I'm gonna close this, but feel free to ask more questions under the fold if you like
