### ISSUE TITLE
RadarChart - onValueMouseEnter/onValueMouseLeave for Hints

### ISSUE THREAD

**Issue by emilyjeppson** [uber/react-vis#959]
I have a `RadarChart` implemented and I would like to add Hints/tooltips. I was looking at the `Sunburst` example (https://github.com/uber/react-vis/blob/master/showcase/sunbursts/sunburst-with-tooltips.js), and I was hoping to do something similar. However, it looks like the `RadarChart` does not support `onValueMouseEnter` or `onValueMouseLeave` events.

Would it be possible to add them? And is this the best way to go about adding Hints to the RadarChart?

**Comment by mcnuttandrew** [comment]
Hey @emilyjeppson 

I think that certainly can be done! If i'm understanding you right, you want to be able to attached listeners to the lines in the radar chart right? I think a simple version of that feature would be pretty easy to implement. Just add listeners props to the top of the radar chart and let them filter down to the line series that it has as children. I am somewhat short on time right now, but I would delightedly invite you to file a PR to this effect.

**Comment by emilyjeppson** [comment]
@mcnuttandrew that sounds great! I'll dig into it and see if I can figure it out.

**Comment by mcnuttandrew** [comment]
@benshope wanna do me a big favor and cut a patch?

**Comment by benshope** [comment]
@mcnuttandrew yep no problem, patched to 1.11.3
