### ISSUE TITLE
[Question] Modified Labeled Heatmap

### ISSUE THREAD

**Issue by thinhly197** [uber/react-vis#967]
Hi team,
I saw your showcase about Labeled Heatmap, it's so good.
I intend to make the correlation matrix base on this example, and the result should be like this example:
http://saurfang.github.io/d3-corrplot/doc/

However, I wonder can I only draw only haft of the square (it means the triangle), and custom the size of datapoint as its value..
Thanks

**Comment by mcnuttandrew** [comment]
Hey @thinhly197 

Couple questions:
- are you asking to only draw the upper half of the the labeled heatmap, eg above diagonal?
- are you asking for tooltips on that show the value of the cell?

**Comment by mcnuttandrew** [comment]
gotcha! For question 1, if you dont want those cells to be there you don't have to pass them in, for instance here is a modification to the data set up from my Labeled Heatmap example

```jsx
const data = alphabet.reduce((acc, letter1, idx) => {
  return acc.concat(
    alphabet.map((letter2, jdx) => ({
      x: `${letter1}1`,
      y: `${letter2}2`,
      color: (idx + jdx) % Math.floor(jdx / idx) || idx
    }).filter((letter2, jdx) => jdx >= idx))
  );
}, []);
```
(note the filter!) You could also do it by setting the colorType on XYPlot to be "literal" and then specifying the color on the cell to be something like color: 'rgba(255, 255, 255, 0)'. 


Can you say more about this line from your original question?
>custom the size of datapoint as its value

**Comment by thinhly197** [comment]
Thanks for your remind.
It likes the attached image
![capture](https://user-images.githubusercontent.com/16750515/45859421-374b5880-bd9d-11e8-86c8-f8a6ef353dd7.PNG)

The value of each cell is the long float number. I tried to style it, but it cannot affect.
`<LabelSeries
          data={data}
          labelAnchorX="middle"
          labelAnchorY="baseline"
          getLabel={d => `${d.value}`}
          style={{
            width: '60%',
            overflow: 'hidden',
            whiteSpace: 'nowrap',
            textOverflow: 'ellipsis',
          }}
        />`

**Comment by mcnuttandrew** [comment]
i think there might be a bug in the way labelSeries does some things. You might changing your style prop to 

```jsx
style={{style: { width: '60%', overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis', }}}
```

**Comment by thinhly197** [comment]
it still lost the style prop. Anyway, thanks for your support!
