### ISSUE TITLE
Zoom example has been removed, link is dead on website

### ISSUE THREAD

**Issue by gwitwer** [uber/react-vis#972]
Hi, the link to the source code for the chart shown [here](https://uber.github.io/react-vis/examples/charts/zoomable-chart) is broken.
The link currently points to [an example](https://github.com/uber/react-vis/blob/master/showcase/examples/zoomable-chart/zoomable-chart-example.js) that does not exist in the project.

**Comment by mcnuttandrew** [comment]
Good catch! I'll file a pr about that shortly. In the meantime check out the highlight component if you haven't found it already!

**Comment by mcnuttandrew** [comment]
Docs deployed! Checkout [this example](https://uber.github.io/react-vis/examples/charts/dynamic-dashboard) which has been put up in place of the zoomable chart and [the highlight component](https://uber.github.io/react-vis/documentation/api-reference/brushing-and-dragging) for what became of the zoomable chart.
