### ISSUE TITLE
Error: "xScale.invert is not a function" when handling Highlight component onBrush / onBrushEnded events 

### ISSUE THREAD

**Issue by bognikol** [uber/react-vis#987]
Not sure if this is a defect, but I get following error when trying to handle onBrush / onBrushEnded events  on Highlight component:

![image](https://user-images.githubusercontent.com/33101206/46350231-84a8af00-c654-11e8-9535-7d8916f0e3c8.png)

while using Highlight component like this:

![image](https://user-images.githubusercontent.com/33101206/46350278-a86bf500-c654-11e8-88d8-db11f81dceb6.png)

Any ideas?
Thanks in advance :-)

**Comment by mcnuttandrew** [comment]
Hey @bognikol 

Unfortunately the Highlight component does not current support brushing across ordinal or categorical axes. This is because we rely on d3-scale which does not support inverses for those sorts of scales. I would be happy to accept a PR adjusting them here, or, maybe more engineeringly applaud a PR to d3-scale adding that functionality (though I kinda assume there is a reason it is not supported?). 

You can sort of  get around this in the same way that we do in the parallel coordinates chart.

**Comment by bognikol** [comment]
I created new pull request to d3-scale where I added band.inverse(). Hopefully it will be merged soon.
https://github.com/d3/d3-scale/pull/151

Cheers

**Comment by bognikol** [comment]
Hi @mcnuttandrew,

I need https://github.com/d3/d3-scale/pull/151 to be merged rather quickly. What is your previous experience, is anyone going to look at it any time soon? What is the status of d3-scale repo in general? Is it better approach to make a workaround is react-vis?

Thanks :-)

**Comment by mcnuttandrew** [comment]
Hey @bognikol 

In my experience d3 can sometimes be slow moving. That said looking at the other PRs open on that repo, there is exactly a PR covering this problem that hasn't been merged in two years.

So this looks bad but there is a light. Specifically, it appears vega-scale (https://github.com/vega/vega-scale) supports exactly this usage. I would support a PR that brings in vega-scale just for your use case, but with a follow up issue to stop using d3-scale and use vega-scale instead. 

Sorry I pointed you in the wrong direction about PRing d3-scale initially, mea culpa.

**Comment by bognikol** [comment]
Hi @mcnuttandrew,

No problem for wrong directions :-)

As I was tight in time, I had to fork react-vis and to implement a workaround directly.
Is it viable to merge this workaround to uber/react-vis as a temporary solution?
https://github.com/bognikol/react-vis/commit/353b98a5b55e2ef1a82921536ce81813ba937801

Cheers,
Bogdan

**Comment by mcnuttandrew** [comment]
Hey @bognikol 

Write some tests and throw that branch through our linter and I think it'll be good to go!

**Comment by bognikol** [comment]
https://github.com/uber/react-vis/pull/1046
